/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.ipaccesscontrollist;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.RequestOptions;
import core.VobizApiApiException;
import core.VobizApiException;
import core.VobizApiHttpResponse;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import resources.ipaccesscontrollist.requests.CreateIpAclRequest;
import resources.ipaccesscontrollist.requests.DeleteIpAclRequest;
import resources.ipaccesscontrollist.requests.ListIpAclsRequest;
import resources.ipaccesscontrollist.requests.UpdateIpAclRequest;
import resources.ipaccesscontrollist.types.CreateIpAclResponse;
import resources.ipaccesscontrollist.types.ListIpAclsResponse;
import resources.ipaccesscontrollist.types.UpdateIpAclResponse;

public class AsyncRawIpAccessControlListClient {
  protected final ClientOptions clientOptions;

  public AsyncRawIpAccessControlListClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Add an IP access control rule to restrict SIP trunk access.
   */
  public CompletableFuture<VobizApiHttpResponse<CreateIpAclResponse>> createIpAcl(String authId,
      CreateIpAclRequest request) {
    return createIpAcl(authId,request,null);
  }

  /**
   * Add an IP access control rule to restrict SIP trunk access.
   */
  public CompletableFuture<VobizApiHttpResponse<CreateIpAclResponse>> createIpAcl(String authId,
      CreateIpAclRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api/v1/Account")
      .addPathSegment(authId)
      .addPathSegments("ip-acl");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
      }
      catch(JsonProcessingException e) {
        throw new VobizApiException("Failed to serialize request", e);
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<VobizApiHttpResponse<CreateIpAclResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new VobizApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CreateIpAclResponse.class), response));
              return;
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new VobizApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new VobizApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Retrieve all IP access control rules on the account.
     */
    public CompletableFuture<VobizApiHttpResponse<ListIpAclsResponse>> listIpAcls(String authId) {
      return listIpAcls(authId,ListIpAclsRequest.builder().build());
    }

    /**
     * Retrieve all IP access control rules on the account.
     */
    public CompletableFuture<VobizApiHttpResponse<ListIpAclsResponse>> listIpAcls(String authId,
        RequestOptions requestOptions) {
      return listIpAcls(authId,ListIpAclsRequest.builder().build(),requestOptions);
    }

    /**
     * Retrieve all IP access control rules on the account.
     */
    public CompletableFuture<VobizApiHttpResponse<ListIpAclsResponse>> listIpAcls(String authId,
        ListIpAclsRequest request) {
      return listIpAcls(authId,request,null);
    }

    /**
     * Retrieve all IP access control rules on the account.
     */
    public CompletableFuture<VobizApiHttpResponse<ListIpAclsResponse>> listIpAcls(String authId,
        ListIpAclsRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("api/v1/Account")
        .addPathSegment(authId)
        .addPathSegments("trunks")
        .addPathSegments("ip-acl");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<VobizApiHttpResponse<ListIpAclsResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                future.complete(new VobizApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListIpAclsResponse.class), response));
                return;
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              future.completeExceptionally(new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new VobizApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new VobizApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * Update an existing IP access control rule.
       */
      public CompletableFuture<VobizApiHttpResponse<UpdateIpAclResponse>> updateIpAcl(String authId,
          String ipAclId, UpdateIpAclRequest request) {
        return updateIpAcl(authId,ipAclId,request,null);
      }

      /**
       * Update an existing IP access control rule.
       */
      public CompletableFuture<VobizApiHttpResponse<UpdateIpAclResponse>> updateIpAcl(String authId,
          String ipAclId, UpdateIpAclRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("api/v1/Account")
          .addPathSegment(authId)
          .addPathSegments("ip-acl")
          .addPathSegment(ipAclId);if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
          }
          catch(JsonProcessingException e) {
            throw new VobizApiException("Failed to serialize request", e);
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl.build())
            .method("PUT", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<VobizApiHttpResponse<UpdateIpAclResponse>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  future.complete(new VobizApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UpdateIpAclResponse.class), response));
                  return;
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                future.completeExceptionally(new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new VobizApiException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new VobizApiException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        /**
         * Remove an IP access control rule.
         */
        public CompletableFuture<VobizApiHttpResponse<Optional<String>>> deleteIpAcl(String authId,
            String ipAclId) {
          return deleteIpAcl(authId,ipAclId,DeleteIpAclRequest.builder().build());
        }

        /**
         * Remove an IP access control rule.
         */
        public CompletableFuture<VobizApiHttpResponse<Optional<String>>> deleteIpAcl(String authId,
            String ipAclId, RequestOptions requestOptions) {
          return deleteIpAcl(authId,ipAclId,DeleteIpAclRequest.builder().build(),requestOptions);
        }

        /**
         * Remove an IP access control rule.
         */
        public CompletableFuture<VobizApiHttpResponse<Optional<String>>> deleteIpAcl(String authId,
            String ipAclId, DeleteIpAclRequest request) {
          return deleteIpAcl(authId,ipAclId,request,null);
        }

        /**
         * Remove an IP access control rule.
         */
        public CompletableFuture<VobizApiHttpResponse<Optional<String>>> deleteIpAcl(String authId,
            String ipAclId, DeleteIpAclRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("api/v1/Account")
            .addPathSegment(authId)
            .addPathSegments("ip-acl")
            .addPathSegment(ipAclId);if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("DELETE", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<VobizApiHttpResponse<Optional<String>>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    future.complete(new VobizApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, new TypeReference<Optional<String>>() {}), response));
                    return;
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  future.completeExceptionally(new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new VobizApiException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new VobizApiException("Network error executing HTTP request", e));
              }
            });
            return future;
          }
        }
