/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.trunks.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateTrunkRequest.Builder.class
)
public final class CreateTrunkRequest {
  private final String name;

  private final String trunkType;

  private final int maxConcurrentCalls;

  private final Map<String, Object> additionalProperties;

  private CreateTrunkRequest(String name, String trunkType, int maxConcurrentCalls,
      Map<String, Object> additionalProperties) {
    this.name = name;
    this.trunkType = trunkType;
    this.maxConcurrentCalls = maxConcurrentCalls;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("trunk_type")
  public String getTrunkType() {
    return trunkType;
  }

  @JsonProperty("max_concurrent_calls")
  public int getMaxConcurrentCalls() {
    return maxConcurrentCalls;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateTrunkRequest && equalTo((CreateTrunkRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateTrunkRequest other) {
    return name.equals(other.name) && trunkType.equals(other.trunkType) && maxConcurrentCalls == other.maxConcurrentCalls;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.trunkType, this.maxConcurrentCalls);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    TrunkTypeStage name(@NotNull String name);

    Builder from(CreateTrunkRequest other);
  }

  public interface TrunkTypeStage {
    MaxConcurrentCallsStage trunkType(@NotNull String trunkType);
  }

  public interface MaxConcurrentCallsStage {
    _FinalStage maxConcurrentCalls(int maxConcurrentCalls);
  }

  public interface _FinalStage {
    CreateTrunkRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, TrunkTypeStage, MaxConcurrentCallsStage, _FinalStage {
    private String name;

    private String trunkType;

    private int maxConcurrentCalls;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateTrunkRequest other) {
      name(other.getName());
      trunkType(other.getTrunkType());
      maxConcurrentCalls(other.getMaxConcurrentCalls());
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public TrunkTypeStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("trunk_type")
    public MaxConcurrentCallsStage trunkType(@NotNull String trunkType) {
      this.trunkType = Objects.requireNonNull(trunkType, "trunkType must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("max_concurrent_calls")
    public _FinalStage maxConcurrentCalls(int maxConcurrentCalls) {
      this.maxConcurrentCalls = maxConcurrentCalls;
      return this;
    }

    @java.lang.Override
    public CreateTrunkRequest build() {
      return new CreateTrunkRequest(name, trunkType, maxConcurrentCalls, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
