/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.trunks.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdateTrunkRequest.Builder.class
)
public final class UpdateTrunkRequest {
  private final String name;

  private final int maxConcurrentCalls;

  private final boolean enabled;

  private final Map<String, Object> additionalProperties;

  private UpdateTrunkRequest(String name, int maxConcurrentCalls, boolean enabled,
      Map<String, Object> additionalProperties) {
    this.name = name;
    this.maxConcurrentCalls = maxConcurrentCalls;
    this.enabled = enabled;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("max_concurrent_calls")
  public int getMaxConcurrentCalls() {
    return maxConcurrentCalls;
  }

  @JsonProperty("enabled")
  public boolean getEnabled() {
    return enabled;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdateTrunkRequest && equalTo((UpdateTrunkRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpdateTrunkRequest other) {
    return name.equals(other.name) && maxConcurrentCalls == other.maxConcurrentCalls && enabled == other.enabled;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.maxConcurrentCalls, this.enabled);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    MaxConcurrentCallsStage name(@NotNull String name);

    Builder from(UpdateTrunkRequest other);
  }

  public interface MaxConcurrentCallsStage {
    EnabledStage maxConcurrentCalls(int maxConcurrentCalls);
  }

  public interface EnabledStage {
    _FinalStage enabled(boolean enabled);
  }

  public interface _FinalStage {
    UpdateTrunkRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, MaxConcurrentCallsStage, EnabledStage, _FinalStage {
    private String name;

    private int maxConcurrentCalls;

    private boolean enabled;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(UpdateTrunkRequest other) {
      name(other.getName());
      maxConcurrentCalls(other.getMaxConcurrentCalls());
      enabled(other.getEnabled());
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public MaxConcurrentCallsStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("max_concurrent_calls")
    public EnabledStage maxConcurrentCalls(int maxConcurrentCalls) {
      this.maxConcurrentCalls = maxConcurrentCalls;
      return this;
    }

    @java.lang.Override
    @JsonSetter("enabled")
    public _FinalStage enabled(boolean enabled) {
      this.enabled = enabled;
      return this;
    }

    @java.lang.Override
    public UpdateTrunkRequest build() {
      return new UpdateTrunkRequest(name, maxConcurrentCalls, enabled, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
