/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.account;

import core.ClientOptions;
import core.RequestOptions;
import java.lang.String;
import resources.account.requests.ChannelSubscriptionRequest;
import resources.account.requests.GetConcurrencyRequest;
import resources.account.requests.PreviewChannelPricingRequest;
import resources.account.types.GetConcurrencyResponse;
import resources.account.types.RetrieveAccountResponse;
import types.ChannelPricingPreview;
import types.ChannelSubscription;

public class AccountClient {
  protected final ClientOptions clientOptions;

  private final RawAccountClient rawClient;

  public AccountClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawAccountClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawAccountClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Retrieve complete account details including pricing tier and credentials.
   */
  public RetrieveAccountResponse retrieveAccount() {
    return this.rawClient.retrieveAccount().body();
  }

  /**
   * Retrieve complete account details including pricing tier and credentials.
   */
  public RetrieveAccountResponse retrieveAccount(RequestOptions requestOptions) {
    return this.rawClient.retrieveAccount(requestOptions).body();
  }

  /**
   * Retrieve the current concurrent call usage and configured limits.
   */
  public GetConcurrencyResponse getConcurrency(String authId) {
    return this.rawClient.getConcurrency(authId).body();
  }

  /**
   * Retrieve the current concurrent call usage and configured limits.
   */
  public GetConcurrencyResponse getConcurrency(String authId, RequestOptions requestOptions) {
    return this.rawClient.getConcurrency(authId, requestOptions).body();
  }

  /**
   * Retrieve the current concurrent call usage and configured limits.
   */
  public GetConcurrencyResponse getConcurrency(String authId, GetConcurrencyRequest request) {
    return this.rawClient.getConcurrency(authId, request).body();
  }

  /**
   * Retrieve the current concurrent call usage and configured limits.
   */
  public GetConcurrencyResponse getConcurrency(String authId, GetConcurrencyRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getConcurrency(authId, request, requestOptions).body();
  }

  /**
   * Calculate the monthly price for CPS or concurrent-call capacity without purchasing capacity or debiting the account.
   */
  public ChannelPricingPreview previewChannelPricing(String authId,
      PreviewChannelPricingRequest request) {
    return this.rawClient.previewChannelPricing(authId, request).body();
  }

  /**
   * Calculate the monthly price for CPS or concurrent-call capacity without purchasing capacity or debiting the account.
   */
  public ChannelPricingPreview previewChannelPricing(String authId,
      PreviewChannelPricingRequest request, RequestOptions requestOptions) {
    return this.rawClient.previewChannelPricing(authId, request, requestOptions).body();
  }

  /**
   * Purchase recurring CPS or concurrent-call capacity. A successful request immediately debits the first monthly charge and activates a subscription that renews every 30 days.
   */
  public ChannelSubscription createChannelSubscription(String authId,
      ChannelSubscriptionRequest request) {
    return this.rawClient.createChannelSubscription(authId, request).body();
  }

  /**
   * Purchase recurring CPS or concurrent-call capacity. A successful request immediately debits the first monthly charge and activates a subscription that renews every 30 days.
   */
  public ChannelSubscription createChannelSubscription(String authId,
      ChannelSubscriptionRequest request, RequestOptions requestOptions) {
    return this.rawClient.createChannelSubscription(authId, request, requestOptions).body();
  }
}
