/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.subaccountkyctestmode.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = MockVerifySubaccountGstRequest.Builder.class
)
public final class MockVerifySubaccountGstRequest {
  private final String gstin;

  private final Map<String, Object> additionalProperties;

  private MockVerifySubaccountGstRequest(String gstin, Map<String, Object> additionalProperties) {
    this.gstin = gstin;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("gstin")
  public String getGstin() {
    return gstin;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof MockVerifySubaccountGstRequest && equalTo((MockVerifySubaccountGstRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(MockVerifySubaccountGstRequest other) {
    return gstin.equals(other.gstin);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.gstin);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static GstinStage builder() {
    return new Builder();
  }

  public interface GstinStage {
    _FinalStage gstin(@NotNull String gstin);

    Builder from(MockVerifySubaccountGstRequest other);
  }

  public interface _FinalStage {
    MockVerifySubaccountGstRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements GstinStage, _FinalStage {
    private String gstin;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(MockVerifySubaccountGstRequest other) {
      gstin(other.getGstin());
      return this;
    }

    @java.lang.Override
    @JsonSetter("gstin")
    public _FinalStage gstin(@NotNull String gstin) {
      this.gstin = Objects.requireNonNull(gstin, "gstin must not be null");
      return this;
    }

    @java.lang.Override
    public MockVerifySubaccountGstRequest build() {
      return new MockVerifySubaccountGstRequest(gstin, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
