/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.cdr;

import core.ClientOptions;
import core.RequestOptions;
import java.io.InputStream;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import resources.cdr.requests.ExportCdrsRequest;
import resources.cdr.requests.GetCdrRequest;
import resources.cdr.requests.ListCdrsRequest;
import resources.cdr.requests.ListRecentCdrsRequest;
import resources.cdr.requests.SearchCdrsRequest;
import resources.cdr.types.GetCdrResponse;
import resources.cdr.types.ListCdrsResponse;
import resources.cdr.types.ListRecentCdrsResponse;
import resources.cdr.types.SearchCdrsResponse;

public class AsyncCdrClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawCdrClient rawClient;

  public AsyncCdrClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawCdrClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawCdrClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Returns all CDRs for your account. Supports filtering by phone numbers,
   * date range, call direction, duration, and pagination.
   */
  public CompletableFuture<ListCdrsResponse> listCdrs(String authId) {
    return this.rawClient.listCdrs(authId).thenApply(response -> response.body());
  }

  /**
   * Returns all CDRs for your account. Supports filtering by phone numbers,
   * date range, call direction, duration, and pagination.
   */
  public CompletableFuture<ListCdrsResponse> listCdrs(String authId,
      RequestOptions requestOptions) {
    return this.rawClient.listCdrs(authId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns all CDRs for your account. Supports filtering by phone numbers,
   * date range, call direction, duration, and pagination.
   */
  public CompletableFuture<ListCdrsResponse> listCdrs(String authId, ListCdrsRequest request) {
    return this.rawClient.listCdrs(authId, request).thenApply(response -> response.body());
  }

  /**
   * Returns all CDRs for your account. Supports filtering by phone numbers,
   * date range, call direction, duration, and pagination.
   */
  public CompletableFuture<ListCdrsResponse> listCdrs(String authId, ListCdrsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.listCdrs(authId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Identical filters to the list endpoint, but the response also includes a
   * <code>filter_summary</code> object describing the active filters applied.
   */
  public CompletableFuture<SearchCdrsResponse> searchCdrs(String authId) {
    return this.rawClient.searchCdrs(authId).thenApply(response -> response.body());
  }

  /**
   * Identical filters to the list endpoint, but the response also includes a
   * <code>filter_summary</code> object describing the active filters applied.
   */
  public CompletableFuture<SearchCdrsResponse> searchCdrs(String authId,
      RequestOptions requestOptions) {
    return this.rawClient.searchCdrs(authId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Identical filters to the list endpoint, but the response also includes a
   * <code>filter_summary</code> object describing the active filters applied.
   */
  public CompletableFuture<SearchCdrsResponse> searchCdrs(String authId,
      SearchCdrsRequest request) {
    return this.rawClient.searchCdrs(authId, request).thenApply(response -> response.body());
  }

  /**
   * Identical filters to the list endpoint, but the response also includes a
   * <code>filter_summary</code> object describing the active filters applied.
   */
  public CompletableFuture<SearchCdrsResponse> searchCdrs(String authId, SearchCdrsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.searchCdrs(authId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the most recent CDRs for your account without requiring a date range.
   * Default 20 records; use <code>limit</code> to retrieve more.
   */
  public CompletableFuture<ListRecentCdrsResponse> listRecentCdrs(String authId) {
    return this.rawClient.listRecentCdrs(authId).thenApply(response -> response.body());
  }

  /**
   * Returns the most recent CDRs for your account without requiring a date range.
   * Default 20 records; use <code>limit</code> to retrieve more.
   */
  public CompletableFuture<ListRecentCdrsResponse> listRecentCdrs(String authId,
      RequestOptions requestOptions) {
    return this.rawClient.listRecentCdrs(authId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the most recent CDRs for your account without requiring a date range.
   * Default 20 records; use <code>limit</code> to retrieve more.
   */
  public CompletableFuture<ListRecentCdrsResponse> listRecentCdrs(String authId,
      ListRecentCdrsRequest request) {
    return this.rawClient.listRecentCdrs(authId, request).thenApply(response -> response.body());
  }

  /**
   * Returns the most recent CDRs for your account without requiring a date range.
   * Default 20 records; use <code>limit</code> to retrieve more.
   */
  public CompletableFuture<ListRecentCdrsResponse> listRecentCdrs(String authId,
      ListRecentCdrsRequest request, RequestOptions requestOptions) {
    return this.rawClient.listRecentCdrs(authId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns CDR data as a downloadable CSV file. Same filters as the list endpoint.
   * <p><strong>Note:</strong> Do NOT send <code>Accept: application/json</code> on this endpoint - the response is <code>text/csv</code>.</p>
   */
  public CompletableFuture<InputStream> exportCdrs(String authId) {
    return this.rawClient.exportCdrs(authId).thenApply(response -> response.body());
  }

  /**
   * Returns CDR data as a downloadable CSV file. Same filters as the list endpoint.
   * <p><strong>Note:</strong> Do NOT send <code>Accept: application/json</code> on this endpoint - the response is <code>text/csv</code>.</p>
   */
  public CompletableFuture<InputStream> exportCdrs(String authId, RequestOptions requestOptions) {
    return this.rawClient.exportCdrs(authId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns CDR data as a downloadable CSV file. Same filters as the list endpoint.
   * <p><strong>Note:</strong> Do NOT send <code>Accept: application/json</code> on this endpoint - the response is <code>text/csv</code>.</p>
   */
  public CompletableFuture<InputStream> exportCdrs(String authId, ExportCdrsRequest request) {
    return this.rawClient.exportCdrs(authId, request).thenApply(response -> response.body());
  }

  /**
   * Returns CDR data as a downloadable CSV file. Same filters as the list endpoint.
   * <p><strong>Note:</strong> Do NOT send <code>Accept: application/json</code> on this endpoint - the response is <code>text/csv</code>.</p>
   */
  public CompletableFuture<InputStream> exportCdrs(String authId, ExportCdrsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.exportCdrs(authId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieve the CDR for a specific completed call using its <code>call_id</code>.
   * Useful when you have a <code>call_id</code> from a callback or previous API response.
   */
  public CompletableFuture<GetCdrResponse> getCdr(String authId, String callId) {
    return this.rawClient.getCdr(authId, callId).thenApply(response -> response.body());
  }

  /**
   * Retrieve the CDR for a specific completed call using its <code>call_id</code>.
   * Useful when you have a <code>call_id</code> from a callback or previous API response.
   */
  public CompletableFuture<GetCdrResponse> getCdr(String authId, String callId,
      RequestOptions requestOptions) {
    return this.rawClient.getCdr(authId, callId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieve the CDR for a specific completed call using its <code>call_id</code>.
   * Useful when you have a <code>call_id</code> from a callback or previous API response.
   */
  public CompletableFuture<GetCdrResponse> getCdr(String authId, String callId,
      GetCdrRequest request) {
    return this.rawClient.getCdr(authId, callId, request).thenApply(response -> response.body());
  }

  /**
   * Retrieve the CDR for a specific completed call using its <code>call_id</code>.
   * Useful when you have a <code>call_id</code> from a callback or previous API response.
   */
  public CompletableFuture<GetCdrResponse> getCdr(String authId, String callId,
      GetCdrRequest request, RequestOptions requestOptions) {
    return this.rawClient.getCdr(authId, callId, request, requestOptions).thenApply(response -> response.body());
  }
}
