/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.cdr;

import com.fasterxml.jackson.core.JsonProcessingException;
import core.ClientOptions;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import core.ResponseBodyInputStream;
import core.VobizApiApiException;
import core.VobizApiException;
import core.VobizApiHttpResponse;
import errors.NotFoundError;
import java.io.IOException;
import java.io.InputStream;
import java.lang.Object;
import java.lang.String;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.cdr.requests.ExportCdrsRequest;
import resources.cdr.requests.GetCdrRequest;
import resources.cdr.requests.ListCdrsRequest;
import resources.cdr.requests.ListRecentCdrsRequest;
import resources.cdr.requests.SearchCdrsRequest;
import resources.cdr.types.GetCdrResponse;
import resources.cdr.types.ListCdrsResponse;
import resources.cdr.types.ListRecentCdrsResponse;
import resources.cdr.types.SearchCdrsResponse;

public class RawCdrClient {
  protected final ClientOptions clientOptions;

  public RawCdrClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Returns all CDRs for your account. Supports filtering by phone numbers,
   * date range, call direction, duration, and pagination.
   */
  public VobizApiHttpResponse<ListCdrsResponse> listCdrs(String authId) {
    return listCdrs(authId,ListCdrsRequest.builder().build());
  }

  /**
   * Returns all CDRs for your account. Supports filtering by phone numbers,
   * date range, call direction, duration, and pagination.
   */
  public VobizApiHttpResponse<ListCdrsResponse> listCdrs(String authId,
      RequestOptions requestOptions) {
    return listCdrs(authId,ListCdrsRequest.builder().build(),requestOptions);
  }

  /**
   * Returns all CDRs for your account. Supports filtering by phone numbers,
   * date range, call direction, duration, and pagination.
   */
  public VobizApiHttpResponse<ListCdrsResponse> listCdrs(String authId, ListCdrsRequest request) {
    return listCdrs(authId,request,null);
  }

  /**
   * Returns all CDRs for your account. Supports filtering by phone numbers,
   * date range, call direction, duration, and pagination.
   */
  public VobizApiHttpResponse<ListCdrsResponse> listCdrs(String authId, ListCdrsRequest request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api/v1/Account")
      .addPathSegment(authId)
      .addPathSegments("cdr");if (request.getFromNumber().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "from_number", request.getFromNumber().get(), false);
      }
      if (request.getToNumber().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "to_number", request.getToNumber().get(), false);
      }
      if (request.getStartDate().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "start_date", request.getStartDate().get(), false);
      }
      if (request.getEndDate().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "end_date", request.getEndDate().get(), false);
      }
      if (request.getCallDirection().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "call_direction", request.getCallDirection().get(), false);
      }
      if (request.getMinDuration().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "min_duration", request.getMinDuration().get(), false);
      }
      if (request.getPage().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
      }
      if (request.getPerPage().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "per_page", request.getPerPage().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new VobizApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListCdrsResponse.class), response);
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new VobizApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Identical filters to the list endpoint, but the response also includes a
     * <code>filter_summary</code> object describing the active filters applied.
     */
    public VobizApiHttpResponse<SearchCdrsResponse> searchCdrs(String authId) {
      return searchCdrs(authId,SearchCdrsRequest.builder().build());
    }

    /**
     * Identical filters to the list endpoint, but the response also includes a
     * <code>filter_summary</code> object describing the active filters applied.
     */
    public VobizApiHttpResponse<SearchCdrsResponse> searchCdrs(String authId,
        RequestOptions requestOptions) {
      return searchCdrs(authId,SearchCdrsRequest.builder().build(),requestOptions);
    }

    /**
     * Identical filters to the list endpoint, but the response also includes a
     * <code>filter_summary</code> object describing the active filters applied.
     */
    public VobizApiHttpResponse<SearchCdrsResponse> searchCdrs(String authId,
        SearchCdrsRequest request) {
      return searchCdrs(authId,request,null);
    }

    /**
     * Identical filters to the list endpoint, but the response also includes a
     * <code>filter_summary</code> object describing the active filters applied.
     */
    public VobizApiHttpResponse<SearchCdrsResponse> searchCdrs(String authId,
        SearchCdrsRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("api/v1/Account")
        .addPathSegment(authId)
        .addPathSegments("cdr")
        .addPathSegments("search");if (request.getFromNumber().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "from_number", request.getFromNumber().get(), false);
        }
        if (request.getToNumber().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "to_number", request.getToNumber().get(), false);
        }
        if (request.getStartDate().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "start_date", request.getStartDate().get(), false);
        }
        if (request.getEndDate().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "end_date", request.getEndDate().get(), false);
        }
        if (request.getCallDirection().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "call_direction", request.getCallDirection().get(), false);
        }
        if (request.getMinDuration().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "min_duration", request.getMinDuration().get(), false);
        }
        if (request.getPage().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getPerPage().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "per_page", request.getPerPage().get(), false);
        }
        if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new VobizApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SearchCdrsResponse.class), response);
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new VobizApiException("Network error executing HTTP request", e);
        }
      }

      /**
       * Returns the most recent CDRs for your account without requiring a date range.
       * Default 20 records; use <code>limit</code> to retrieve more.
       */
      public VobizApiHttpResponse<ListRecentCdrsResponse> listRecentCdrs(String authId) {
        return listRecentCdrs(authId,ListRecentCdrsRequest.builder().build());
      }

      /**
       * Returns the most recent CDRs for your account without requiring a date range.
       * Default 20 records; use <code>limit</code> to retrieve more.
       */
      public VobizApiHttpResponse<ListRecentCdrsResponse> listRecentCdrs(String authId,
          RequestOptions requestOptions) {
        return listRecentCdrs(authId,ListRecentCdrsRequest.builder().build(),requestOptions);
      }

      /**
       * Returns the most recent CDRs for your account without requiring a date range.
       * Default 20 records; use <code>limit</code> to retrieve more.
       */
      public VobizApiHttpResponse<ListRecentCdrsResponse> listRecentCdrs(String authId,
          ListRecentCdrsRequest request) {
        return listRecentCdrs(authId,request,null);
      }

      /**
       * Returns the most recent CDRs for your account without requiring a date range.
       * Default 20 records; use <code>limit</code> to retrieve more.
       */
      public VobizApiHttpResponse<ListRecentCdrsResponse> listRecentCdrs(String authId,
          ListRecentCdrsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("api/v1/Account")
          .addPathSegment(authId)
          .addPathSegments("cdr")
          .addPathSegments("recent");if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
          }
          if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              return new VobizApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListRecentCdrsResponse.class), response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (IOException e) {
            throw new VobizApiException("Network error executing HTTP request", e);
          }
        }

        /**
         * Returns CDR data as a downloadable CSV file. Same filters as the list endpoint.
         * <p><strong>Note:</strong> Do NOT send <code>Accept: application/json</code> on this endpoint - the response is <code>text/csv</code>.</p>
         */
        public VobizApiHttpResponse<InputStream> exportCdrs(String authId) {
          return exportCdrs(authId,ExportCdrsRequest.builder().build());
        }

        /**
         * Returns CDR data as a downloadable CSV file. Same filters as the list endpoint.
         * <p><strong>Note:</strong> Do NOT send <code>Accept: application/json</code> on this endpoint - the response is <code>text/csv</code>.</p>
         */
        public VobizApiHttpResponse<InputStream> exportCdrs(String authId,
            RequestOptions requestOptions) {
          return exportCdrs(authId,ExportCdrsRequest.builder().build(),requestOptions);
        }

        /**
         * Returns CDR data as a downloadable CSV file. Same filters as the list endpoint.
         * <p><strong>Note:</strong> Do NOT send <code>Accept: application/json</code> on this endpoint - the response is <code>text/csv</code>.</p>
         */
        public VobizApiHttpResponse<InputStream> exportCdrs(String authId,
            ExportCdrsRequest request) {
          return exportCdrs(authId,request,null);
        }

        /**
         * Returns CDR data as a downloadable CSV file. Same filters as the list endpoint.
         * <p><strong>Note:</strong> Do NOT send <code>Accept: application/json</code> on this endpoint - the response is <code>text/csv</code>.</p>
         */
        public VobizApiHttpResponse<InputStream> exportCdrs(String authId,
            ExportCdrsRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("api/v1/Account")
            .addPathSegment(authId)
            .addPathSegments("cdr")
            .addPathSegments("export");if (request.getFromNumber().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "from_number", request.getFromNumber().get(), false);
            }
            if (request.getToNumber().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "to_number", request.getToNumber().get(), false);
            }
            if (request.getStartDate().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "start_date", request.getStartDate().get(), false);
            }
            if (request.getEndDate().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "end_date", request.getEndDate().get(), false);
            }
            if (request.getCallDirection().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "call_direction", request.getCallDirection().get(), false);
            }
            if (request.getMinDuration().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "min_duration", request.getMinDuration().get(), false);
            }
            if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("GET", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)));
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            try {
              Response response = client.newCall(okhttpRequest).execute();
              ResponseBody responseBody = response.body();
              if (response.isSuccessful()) {
                return new VobizApiHttpResponse<>(new ResponseBodyInputStream(response), response);
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (IOException e) {
              throw new VobizApiException("Network error executing HTTP request", e);
            }
          }

          /**
           * Retrieve the CDR for a specific completed call using its <code>call_id</code>.
           * Useful when you have a <code>call_id</code> from a callback or previous API response.
           */
          public VobizApiHttpResponse<GetCdrResponse> getCdr(String authId, String callId) {
            return getCdr(authId,callId,GetCdrRequest.builder().build());
          }

          /**
           * Retrieve the CDR for a specific completed call using its <code>call_id</code>.
           * Useful when you have a <code>call_id</code> from a callback or previous API response.
           */
          public VobizApiHttpResponse<GetCdrResponse> getCdr(String authId, String callId,
              RequestOptions requestOptions) {
            return getCdr(authId,callId,GetCdrRequest.builder().build(),requestOptions);
          }

          /**
           * Retrieve the CDR for a specific completed call using its <code>call_id</code>.
           * Useful when you have a <code>call_id</code> from a callback or previous API response.
           */
          public VobizApiHttpResponse<GetCdrResponse> getCdr(String authId, String callId,
              GetCdrRequest request) {
            return getCdr(authId,callId,request,null);
          }

          /**
           * Retrieve the CDR for a specific completed call using its <code>call_id</code>.
           * Useful when you have a <code>call_id</code> from a callback or previous API response.
           */
          public VobizApiHttpResponse<GetCdrResponse> getCdr(String authId, String callId,
              GetCdrRequest request, RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("api/v1/Account")
              .addPathSegment(authId)
              .addPathSegments("cdr")
              .addPathSegment(callId);if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
              Request okhttpRequest = _requestBuilder.build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              try (Response response = client.newCall(okhttpRequest).execute()) {
                ResponseBody responseBody = response.body();
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  return new VobizApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetCdrResponse.class), response);
                }
                try {
                  if (response.code() == 404) {
                    throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                throw new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
              }
              catch (IOException e) {
                throw new VobizApiException("Network error executing HTTP request", e);
              }
            }
          }
