/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.cdr.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ExportCdrsRequestCallDirection {
  public static final ExportCdrsRequestCallDirection INBOUND = new ExportCdrsRequestCallDirection(Value.INBOUND, "inbound");

  public static final ExportCdrsRequestCallDirection OUTBOUND = new ExportCdrsRequestCallDirection(Value.OUTBOUND, "outbound");

  private final Value value;

  private final String string;

  ExportCdrsRequestCallDirection(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ExportCdrsRequestCallDirection && this.string.equals(((ExportCdrsRequestCallDirection) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case INBOUND:
        return visitor.visitInbound();
      case OUTBOUND:
        return visitor.visitOutbound();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ExportCdrsRequestCallDirection valueOf(String value) {
    switch (value) {
      case "inbound":
        return INBOUND;
      case "outbound":
        return OUTBOUND;
      default:
        return new ExportCdrsRequestCallDirection(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    INBOUND,

    OUTBOUND,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitInbound();

    T visitOutbound();

    T visitUnknown(String unknownType);
  }
}
