/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.cdr.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.Nullable;
import core.NullableNonemptyFilter;
import core.ObjectMappers;
import java.lang.Double;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SearchCdrsResponseDataItem.Builder.class
)
public final class SearchCdrsResponseDataItem {
  private final String accountId;

  private final Optional<String> answerTime;

  private final int billsec;

  private final Optional<String> bridgeUuid;

  private final String callDirection;

  private final String callerIdName;

  private final String callerIdNumber;

  private final Optional<Object> campaignId;

  private final Optional<Object> carrierIp;

  private final Optional<String> codec;

  private final String context;

  private final double cost;

  private final String createdAt;

  private final String currency;

  private final Optional<Object> customerEndpoint;

  private final String destinationNumber;

  private final int duration;

  private final String endTime;

  private final Optional<String> failureCode;

  private final Optional<String> failureReason;

  private final Optional<String> hangupCause;

  private final Optional<Integer> hangupCauseCode;

  private final Optional<String> hangupCauseName;

  private final Optional<String> hangupDisposition;

  private final Optional<String> hangupSource;

  private final int id;

  private final Optional<Double> jitter;

  private final Optional<Double> mos;

  private final Optional<String> networkAddr;

  private final String originationRegion;

  private final Optional<Double> packetLoss;

  private final Optional<String> progressTime;

  private final String region;

  private final int ringTime;

  private final String sipCallId;

  private final Optional<String> sipUserAgent;

  private final String startTime;

  private final double streamingCost;

  private final Optional<String> terminatedTo;

  private final double totalCost;

  private final Optional<String> trunkId;

  private final String updatedAt;

  private final String uuid;

  private final Map<String, Object> additionalProperties;

  private SearchCdrsResponseDataItem(String accountId, Optional<String> answerTime, int billsec,
      Optional<String> bridgeUuid, String callDirection, String callerIdName, String callerIdNumber,
      Optional<Object> campaignId, Optional<Object> carrierIp, Optional<String> codec,
      String context, double cost, String createdAt, String currency,
      Optional<Object> customerEndpoint, String destinationNumber, int duration, String endTime,
      Optional<String> failureCode, Optional<String> failureReason, Optional<String> hangupCause,
      Optional<Integer> hangupCauseCode, Optional<String> hangupCauseName,
      Optional<String> hangupDisposition, Optional<String> hangupSource, int id,
      Optional<Double> jitter, Optional<Double> mos, Optional<String> networkAddr,
      String originationRegion, Optional<Double> packetLoss, Optional<String> progressTime,
      String region, int ringTime, String sipCallId, Optional<String> sipUserAgent,
      String startTime, double streamingCost, Optional<String> terminatedTo, double totalCost,
      Optional<String> trunkId, String updatedAt, String uuid,
      Map<String, Object> additionalProperties) {
    this.accountId = accountId;
    this.answerTime = answerTime;
    this.billsec = billsec;
    this.bridgeUuid = bridgeUuid;
    this.callDirection = callDirection;
    this.callerIdName = callerIdName;
    this.callerIdNumber = callerIdNumber;
    this.campaignId = campaignId;
    this.carrierIp = carrierIp;
    this.codec = codec;
    this.context = context;
    this.cost = cost;
    this.createdAt = createdAt;
    this.currency = currency;
    this.customerEndpoint = customerEndpoint;
    this.destinationNumber = destinationNumber;
    this.duration = duration;
    this.endTime = endTime;
    this.failureCode = failureCode;
    this.failureReason = failureReason;
    this.hangupCause = hangupCause;
    this.hangupCauseCode = hangupCauseCode;
    this.hangupCauseName = hangupCauseName;
    this.hangupDisposition = hangupDisposition;
    this.hangupSource = hangupSource;
    this.id = id;
    this.jitter = jitter;
    this.mos = mos;
    this.networkAddr = networkAddr;
    this.originationRegion = originationRegion;
    this.packetLoss = packetLoss;
    this.progressTime = progressTime;
    this.region = region;
    this.ringTime = ringTime;
    this.sipCallId = sipCallId;
    this.sipUserAgent = sipUserAgent;
    this.startTime = startTime;
    this.streamingCost = streamingCost;
    this.terminatedTo = terminatedTo;
    this.totalCost = totalCost;
    this.trunkId = trunkId;
    this.updatedAt = updatedAt;
    this.uuid = uuid;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("account_id")
  public String getAccountId() {
    return accountId;
  }

  @JsonIgnore
  public Optional<String> getAnswerTime() {
    if (answerTime == null) {
      return Optional.empty();
    }
    return answerTime;
  }

  @JsonProperty("billsec")
  public int getBillsec() {
    return billsec;
  }

  @JsonIgnore
  public Optional<String> getBridgeUuid() {
    if (bridgeUuid == null) {
      return Optional.empty();
    }
    return bridgeUuid;
  }

  @JsonProperty("call_direction")
  public String getCallDirection() {
    return callDirection;
  }

  @JsonProperty("caller_id_name")
  public String getCallerIdName() {
    return callerIdName;
  }

  @JsonProperty("caller_id_number")
  public String getCallerIdNumber() {
    return callerIdNumber;
  }

  @JsonIgnore
  public Optional<Object> getCampaignId() {
    if (campaignId == null) {
      return Optional.empty();
    }
    return campaignId;
  }

  @JsonIgnore
  public Optional<Object> getCarrierIp() {
    if (carrierIp == null) {
      return Optional.empty();
    }
    return carrierIp;
  }

  @JsonIgnore
  public Optional<String> getCodec() {
    if (codec == null) {
      return Optional.empty();
    }
    return codec;
  }

  @JsonProperty("context")
  public String getContext() {
    return context;
  }

  @JsonProperty("cost")
  public double getCost() {
    return cost;
  }

  @JsonProperty("created_at")
  public String getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("currency")
  public String getCurrency() {
    return currency;
  }

  @JsonIgnore
  public Optional<Object> getCustomerEndpoint() {
    if (customerEndpoint == null) {
      return Optional.empty();
    }
    return customerEndpoint;
  }

  @JsonProperty("destination_number")
  public String getDestinationNumber() {
    return destinationNumber;
  }

  @JsonProperty("duration")
  public int getDuration() {
    return duration;
  }

  @JsonProperty("end_time")
  public String getEndTime() {
    return endTime;
  }

  @JsonIgnore
  public Optional<String> getFailureCode() {
    if (failureCode == null) {
      return Optional.empty();
    }
    return failureCode;
  }

  @JsonIgnore
  public Optional<String> getFailureReason() {
    if (failureReason == null) {
      return Optional.empty();
    }
    return failureReason;
  }

  @JsonIgnore
  public Optional<String> getHangupCause() {
    if (hangupCause == null) {
      return Optional.empty();
    }
    return hangupCause;
  }

  @JsonIgnore
  public Optional<Integer> getHangupCauseCode() {
    if (hangupCauseCode == null) {
      return Optional.empty();
    }
    return hangupCauseCode;
  }

  @JsonIgnore
  public Optional<String> getHangupCauseName() {
    if (hangupCauseName == null) {
      return Optional.empty();
    }
    return hangupCauseName;
  }

  @JsonIgnore
  public Optional<String> getHangupDisposition() {
    if (hangupDisposition == null) {
      return Optional.empty();
    }
    return hangupDisposition;
  }

  @JsonIgnore
  public Optional<String> getHangupSource() {
    if (hangupSource == null) {
      return Optional.empty();
    }
    return hangupSource;
  }

  @JsonProperty("id")
  public int getId() {
    return id;
  }

  @JsonIgnore
  public Optional<Double> getJitter() {
    if (jitter == null) {
      return Optional.empty();
    }
    return jitter;
  }

  @JsonIgnore
  public Optional<Double> getMos() {
    if (mos == null) {
      return Optional.empty();
    }
    return mos;
  }

  @JsonIgnore
  public Optional<String> getNetworkAddr() {
    if (networkAddr == null) {
      return Optional.empty();
    }
    return networkAddr;
  }

  @JsonProperty("origination_region")
  public String getOriginationRegion() {
    return originationRegion;
  }

  @JsonIgnore
  public Optional<Double> getPacketLoss() {
    if (packetLoss == null) {
      return Optional.empty();
    }
    return packetLoss;
  }

  @JsonIgnore
  public Optional<String> getProgressTime() {
    if (progressTime == null) {
      return Optional.empty();
    }
    return progressTime;
  }

  @JsonProperty("region")
  public String getRegion() {
    return region;
  }

  @JsonProperty("ring_time")
  public int getRingTime() {
    return ringTime;
  }

  @JsonProperty("sip_call_id")
  public String getSipCallId() {
    return sipCallId;
  }

  @JsonIgnore
  public Optional<String> getSipUserAgent() {
    if (sipUserAgent == null) {
      return Optional.empty();
    }
    return sipUserAgent;
  }

  @JsonProperty("start_time")
  public String getStartTime() {
    return startTime;
  }

  @JsonProperty("streaming_cost")
  public double getStreamingCost() {
    return streamingCost;
  }

  @JsonIgnore
  public Optional<String> getTerminatedTo() {
    if (terminatedTo == null) {
      return Optional.empty();
    }
    return terminatedTo;
  }

  @JsonProperty("total_cost")
  public double getTotalCost() {
    return totalCost;
  }

  @JsonIgnore
  public Optional<String> getTrunkId() {
    if (trunkId == null) {
      return Optional.empty();
    }
    return trunkId;
  }

  @JsonProperty("updated_at")
  public String getUpdatedAt() {
    return updatedAt;
  }

  @JsonProperty("uuid")
  public String getUuid() {
    return uuid;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("answer_time")
  private Optional<String> _getAnswerTime() {
    return answerTime;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("bridge_uuid")
  private Optional<String> _getBridgeUuid() {
    return bridgeUuid;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("campaign_id")
  private Optional<Object> _getCampaignId() {
    return campaignId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("carrier_ip")
  private Optional<Object> _getCarrierIp() {
    return carrierIp;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("codec")
  private Optional<String> _getCodec() {
    return codec;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("customer_endpoint")
  private Optional<Object> _getCustomerEndpoint() {
    return customerEndpoint;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("failure_code")
  private Optional<String> _getFailureCode() {
    return failureCode;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("failure_reason")
  private Optional<String> _getFailureReason() {
    return failureReason;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("hangup_cause")
  private Optional<String> _getHangupCause() {
    return hangupCause;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("hangup_cause_code")
  private Optional<Integer> _getHangupCauseCode() {
    return hangupCauseCode;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("hangup_cause_name")
  private Optional<String> _getHangupCauseName() {
    return hangupCauseName;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("hangup_disposition")
  private Optional<String> _getHangupDisposition() {
    return hangupDisposition;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("hangup_source")
  private Optional<String> _getHangupSource() {
    return hangupSource;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("jitter")
  private Optional<Double> _getJitter() {
    return jitter;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("mos")
  private Optional<Double> _getMos() {
    return mos;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("network_addr")
  private Optional<String> _getNetworkAddr() {
    return networkAddr;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("packet_loss")
  private Optional<Double> _getPacketLoss() {
    return packetLoss;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("progress_time")
  private Optional<String> _getProgressTime() {
    return progressTime;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("sip_user_agent")
  private Optional<String> _getSipUserAgent() {
    return sipUserAgent;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("terminated_to")
  private Optional<String> _getTerminatedTo() {
    return terminatedTo;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("trunk_id")
  private Optional<String> _getTrunkId() {
    return trunkId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SearchCdrsResponseDataItem && equalTo((SearchCdrsResponseDataItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SearchCdrsResponseDataItem other) {
    return accountId.equals(other.accountId) && answerTime.equals(other.answerTime) && billsec == other.billsec && bridgeUuid.equals(other.bridgeUuid) && callDirection.equals(other.callDirection) && callerIdName.equals(other.callerIdName) && callerIdNumber.equals(other.callerIdNumber) && campaignId.equals(other.campaignId) && carrierIp.equals(other.carrierIp) && codec.equals(other.codec) && context.equals(other.context) && cost == other.cost && createdAt.equals(other.createdAt) && currency.equals(other.currency) && customerEndpoint.equals(other.customerEndpoint) && destinationNumber.equals(other.destinationNumber) && duration == other.duration && endTime.equals(other.endTime) && failureCode.equals(other.failureCode) && failureReason.equals(other.failureReason) && hangupCause.equals(other.hangupCause) && hangupCauseCode.equals(other.hangupCauseCode) && hangupCauseName.equals(other.hangupCauseName) && hangupDisposition.equals(other.hangupDisposition) && hangupSource.equals(other.hangupSource) && id == other.id && jitter.equals(other.jitter) && mos.equals(other.mos) && networkAddr.equals(other.networkAddr) && originationRegion.equals(other.originationRegion) && packetLoss.equals(other.packetLoss) && progressTime.equals(other.progressTime) && region.equals(other.region) && ringTime == other.ringTime && sipCallId.equals(other.sipCallId) && sipUserAgent.equals(other.sipUserAgent) && startTime.equals(other.startTime) && streamingCost == other.streamingCost && terminatedTo.equals(other.terminatedTo) && totalCost == other.totalCost && trunkId.equals(other.trunkId) && updatedAt.equals(other.updatedAt) && uuid.equals(other.uuid);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.accountId, this.answerTime, this.billsec, this.bridgeUuid, this.callDirection, this.callerIdName, this.callerIdNumber, this.campaignId, this.carrierIp, this.codec, this.context, this.cost, this.createdAt, this.currency, this.customerEndpoint, this.destinationNumber, this.duration, this.endTime, this.failureCode, this.failureReason, this.hangupCause, this.hangupCauseCode, this.hangupCauseName, this.hangupDisposition, this.hangupSource, this.id, this.jitter, this.mos, this.networkAddr, this.originationRegion, this.packetLoss, this.progressTime, this.region, this.ringTime, this.sipCallId, this.sipUserAgent, this.startTime, this.streamingCost, this.terminatedTo, this.totalCost, this.trunkId, this.updatedAt, this.uuid);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static AccountIdStage builder() {
    return new Builder();
  }

  public interface AccountIdStage {
    BillsecStage accountId(@NotNull String accountId);

    Builder from(SearchCdrsResponseDataItem other);
  }

  public interface BillsecStage {
    CallDirectionStage billsec(int billsec);
  }

  public interface CallDirectionStage {
    CallerIdNameStage callDirection(@NotNull String callDirection);
  }

  public interface CallerIdNameStage {
    CallerIdNumberStage callerIdName(@NotNull String callerIdName);
  }

  public interface CallerIdNumberStage {
    ContextStage callerIdNumber(@NotNull String callerIdNumber);
  }

  public interface ContextStage {
    CostStage context(@NotNull String context);
  }

  public interface CostStage {
    CreatedAtStage cost(double cost);
  }

  public interface CreatedAtStage {
    CurrencyStage createdAt(@NotNull String createdAt);
  }

  public interface CurrencyStage {
    DestinationNumberStage currency(@NotNull String currency);
  }

  public interface DestinationNumberStage {
    DurationStage destinationNumber(@NotNull String destinationNumber);
  }

  public interface DurationStage {
    EndTimeStage duration(int duration);
  }

  public interface EndTimeStage {
    IdStage endTime(@NotNull String endTime);
  }

  public interface IdStage {
    OriginationRegionStage id(int id);
  }

  public interface OriginationRegionStage {
    RegionStage originationRegion(@NotNull String originationRegion);
  }

  public interface RegionStage {
    RingTimeStage region(@NotNull String region);
  }

  public interface RingTimeStage {
    SipCallIdStage ringTime(int ringTime);
  }

  public interface SipCallIdStage {
    StartTimeStage sipCallId(@NotNull String sipCallId);
  }

  public interface StartTimeStage {
    StreamingCostStage startTime(@NotNull String startTime);
  }

  public interface StreamingCostStage {
    TotalCostStage streamingCost(double streamingCost);
  }

  public interface TotalCostStage {
    UpdatedAtStage totalCost(double totalCost);
  }

  public interface UpdatedAtStage {
    UuidStage updatedAt(@NotNull String updatedAt);
  }

  public interface UuidStage {
    _FinalStage uuid(@NotNull String uuid);
  }

  public interface _FinalStage {
    SearchCdrsResponseDataItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage answerTime(Optional<String> answerTime);

    _FinalStage answerTime(String answerTime);

    _FinalStage answerTime(Nullable<String> answerTime);

    _FinalStage bridgeUuid(Optional<String> bridgeUuid);

    _FinalStage bridgeUuid(String bridgeUuid);

    _FinalStage bridgeUuid(Nullable<String> bridgeUuid);

    _FinalStage campaignId(Optional<Object> campaignId);

    _FinalStage campaignId(Object campaignId);

    _FinalStage campaignId(Nullable<Object> campaignId);

    _FinalStage carrierIp(Optional<Object> carrierIp);

    _FinalStage carrierIp(Object carrierIp);

    _FinalStage carrierIp(Nullable<Object> carrierIp);

    _FinalStage codec(Optional<String> codec);

    _FinalStage codec(String codec);

    _FinalStage codec(Nullable<String> codec);

    _FinalStage customerEndpoint(Optional<Object> customerEndpoint);

    _FinalStage customerEndpoint(Object customerEndpoint);

    _FinalStage customerEndpoint(Nullable<Object> customerEndpoint);

    _FinalStage failureCode(Optional<String> failureCode);

    _FinalStage failureCode(String failureCode);

    _FinalStage failureCode(Nullable<String> failureCode);

    _FinalStage failureReason(Optional<String> failureReason);

    _FinalStage failureReason(String failureReason);

    _FinalStage failureReason(Nullable<String> failureReason);

    _FinalStage hangupCause(Optional<String> hangupCause);

    _FinalStage hangupCause(String hangupCause);

    _FinalStage hangupCause(Nullable<String> hangupCause);

    _FinalStage hangupCauseCode(Optional<Integer> hangupCauseCode);

    _FinalStage hangupCauseCode(Integer hangupCauseCode);

    _FinalStage hangupCauseCode(Nullable<Integer> hangupCauseCode);

    _FinalStage hangupCauseName(Optional<String> hangupCauseName);

    _FinalStage hangupCauseName(String hangupCauseName);

    _FinalStage hangupCauseName(Nullable<String> hangupCauseName);

    _FinalStage hangupDisposition(Optional<String> hangupDisposition);

    _FinalStage hangupDisposition(String hangupDisposition);

    _FinalStage hangupDisposition(Nullable<String> hangupDisposition);

    _FinalStage hangupSource(Optional<String> hangupSource);

    _FinalStage hangupSource(String hangupSource);

    _FinalStage hangupSource(Nullable<String> hangupSource);

    _FinalStage jitter(Optional<Double> jitter);

    _FinalStage jitter(Double jitter);

    _FinalStage jitter(Nullable<Double> jitter);

    _FinalStage mos(Optional<Double> mos);

    _FinalStage mos(Double mos);

    _FinalStage mos(Nullable<Double> mos);

    _FinalStage networkAddr(Optional<String> networkAddr);

    _FinalStage networkAddr(String networkAddr);

    _FinalStage networkAddr(Nullable<String> networkAddr);

    _FinalStage packetLoss(Optional<Double> packetLoss);

    _FinalStage packetLoss(Double packetLoss);

    _FinalStage packetLoss(Nullable<Double> packetLoss);

    _FinalStage progressTime(Optional<String> progressTime);

    _FinalStage progressTime(String progressTime);

    _FinalStage progressTime(Nullable<String> progressTime);

    _FinalStage sipUserAgent(Optional<String> sipUserAgent);

    _FinalStage sipUserAgent(String sipUserAgent);

    _FinalStage sipUserAgent(Nullable<String> sipUserAgent);

    _FinalStage terminatedTo(Optional<String> terminatedTo);

    _FinalStage terminatedTo(String terminatedTo);

    _FinalStage terminatedTo(Nullable<String> terminatedTo);

    _FinalStage trunkId(Optional<String> trunkId);

    _FinalStage trunkId(String trunkId);

    _FinalStage trunkId(Nullable<String> trunkId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements AccountIdStage, BillsecStage, CallDirectionStage, CallerIdNameStage, CallerIdNumberStage, ContextStage, CostStage, CreatedAtStage, CurrencyStage, DestinationNumberStage, DurationStage, EndTimeStage, IdStage, OriginationRegionStage, RegionStage, RingTimeStage, SipCallIdStage, StartTimeStage, StreamingCostStage, TotalCostStage, UpdatedAtStage, UuidStage, _FinalStage {
    private String accountId;

    private int billsec;

    private String callDirection;

    private String callerIdName;

    private String callerIdNumber;

    private String context;

    private double cost;

    private String createdAt;

    private String currency;

    private String destinationNumber;

    private int duration;

    private String endTime;

    private int id;

    private String originationRegion;

    private String region;

    private int ringTime;

    private String sipCallId;

    private String startTime;

    private double streamingCost;

    private double totalCost;

    private String updatedAt;

    private String uuid;

    private Optional<String> trunkId = Optional.empty();

    private Optional<String> terminatedTo = Optional.empty();

    private Optional<String> sipUserAgent = Optional.empty();

    private Optional<String> progressTime = Optional.empty();

    private Optional<Double> packetLoss = Optional.empty();

    private Optional<String> networkAddr = Optional.empty();

    private Optional<Double> mos = Optional.empty();

    private Optional<Double> jitter = Optional.empty();

    private Optional<String> hangupSource = Optional.empty();

    private Optional<String> hangupDisposition = Optional.empty();

    private Optional<String> hangupCauseName = Optional.empty();

    private Optional<Integer> hangupCauseCode = Optional.empty();

    private Optional<String> hangupCause = Optional.empty();

    private Optional<String> failureReason = Optional.empty();

    private Optional<String> failureCode = Optional.empty();

    private Optional<Object> customerEndpoint = Optional.empty();

    private Optional<String> codec = Optional.empty();

    private Optional<Object> carrierIp = Optional.empty();

    private Optional<Object> campaignId = Optional.empty();

    private Optional<String> bridgeUuid = Optional.empty();

    private Optional<String> answerTime = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(SearchCdrsResponseDataItem other) {
      accountId(other.getAccountId());
      answerTime(other.getAnswerTime());
      billsec(other.getBillsec());
      bridgeUuid(other.getBridgeUuid());
      callDirection(other.getCallDirection());
      callerIdName(other.getCallerIdName());
      callerIdNumber(other.getCallerIdNumber());
      campaignId(other.getCampaignId());
      carrierIp(other.getCarrierIp());
      codec(other.getCodec());
      context(other.getContext());
      cost(other.getCost());
      createdAt(other.getCreatedAt());
      currency(other.getCurrency());
      customerEndpoint(other.getCustomerEndpoint());
      destinationNumber(other.getDestinationNumber());
      duration(other.getDuration());
      endTime(other.getEndTime());
      failureCode(other.getFailureCode());
      failureReason(other.getFailureReason());
      hangupCause(other.getHangupCause());
      hangupCauseCode(other.getHangupCauseCode());
      hangupCauseName(other.getHangupCauseName());
      hangupDisposition(other.getHangupDisposition());
      hangupSource(other.getHangupSource());
      id(other.getId());
      jitter(other.getJitter());
      mos(other.getMos());
      networkAddr(other.getNetworkAddr());
      originationRegion(other.getOriginationRegion());
      packetLoss(other.getPacketLoss());
      progressTime(other.getProgressTime());
      region(other.getRegion());
      ringTime(other.getRingTime());
      sipCallId(other.getSipCallId());
      sipUserAgent(other.getSipUserAgent());
      startTime(other.getStartTime());
      streamingCost(other.getStreamingCost());
      terminatedTo(other.getTerminatedTo());
      totalCost(other.getTotalCost());
      trunkId(other.getTrunkId());
      updatedAt(other.getUpdatedAt());
      uuid(other.getUuid());
      return this;
    }

    @java.lang.Override
    @JsonSetter("account_id")
    public BillsecStage accountId(@NotNull String accountId) {
      this.accountId = Objects.requireNonNull(accountId, "accountId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("billsec")
    public CallDirectionStage billsec(int billsec) {
      this.billsec = billsec;
      return this;
    }

    @java.lang.Override
    @JsonSetter("call_direction")
    public CallerIdNameStage callDirection(@NotNull String callDirection) {
      this.callDirection = Objects.requireNonNull(callDirection, "callDirection must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("caller_id_name")
    public CallerIdNumberStage callerIdName(@NotNull String callerIdName) {
      this.callerIdName = Objects.requireNonNull(callerIdName, "callerIdName must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("caller_id_number")
    public ContextStage callerIdNumber(@NotNull String callerIdNumber) {
      this.callerIdNumber = Objects.requireNonNull(callerIdNumber, "callerIdNumber must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("context")
    public CostStage context(@NotNull String context) {
      this.context = Objects.requireNonNull(context, "context must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("cost")
    public CreatedAtStage cost(double cost) {
      this.cost = cost;
      return this;
    }

    @java.lang.Override
    @JsonSetter("created_at")
    public CurrencyStage createdAt(@NotNull String createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("currency")
    public DestinationNumberStage currency(@NotNull String currency) {
      this.currency = Objects.requireNonNull(currency, "currency must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("destination_number")
    public DurationStage destinationNumber(@NotNull String destinationNumber) {
      this.destinationNumber = Objects.requireNonNull(destinationNumber, "destinationNumber must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("duration")
    public EndTimeStage duration(int duration) {
      this.duration = duration;
      return this;
    }

    @java.lang.Override
    @JsonSetter("end_time")
    public IdStage endTime(@NotNull String endTime) {
      this.endTime = Objects.requireNonNull(endTime, "endTime must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public OriginationRegionStage id(int id) {
      this.id = id;
      return this;
    }

    @java.lang.Override
    @JsonSetter("origination_region")
    public RegionStage originationRegion(@NotNull String originationRegion) {
      this.originationRegion = Objects.requireNonNull(originationRegion, "originationRegion must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("region")
    public RingTimeStage region(@NotNull String region) {
      this.region = Objects.requireNonNull(region, "region must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("ring_time")
    public SipCallIdStage ringTime(int ringTime) {
      this.ringTime = ringTime;
      return this;
    }

    @java.lang.Override
    @JsonSetter("sip_call_id")
    public StartTimeStage sipCallId(@NotNull String sipCallId) {
      this.sipCallId = Objects.requireNonNull(sipCallId, "sipCallId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("start_time")
    public StreamingCostStage startTime(@NotNull String startTime) {
      this.startTime = Objects.requireNonNull(startTime, "startTime must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("streaming_cost")
    public TotalCostStage streamingCost(double streamingCost) {
      this.streamingCost = streamingCost;
      return this;
    }

    @java.lang.Override
    @JsonSetter("total_cost")
    public UpdatedAtStage totalCost(double totalCost) {
      this.totalCost = totalCost;
      return this;
    }

    @java.lang.Override
    @JsonSetter("updated_at")
    public UuidStage updatedAt(@NotNull String updatedAt) {
      this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("uuid")
    public _FinalStage uuid(@NotNull String uuid) {
      this.uuid = Objects.requireNonNull(uuid, "uuid must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage trunkId(Nullable<String> trunkId) {
      if (trunkId.isNull()) {
        this.trunkId = null;
      }
      else if (trunkId.isEmpty()) {
        this.trunkId = Optional.empty();
      }
      else {
        this.trunkId = Optional.of(trunkId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage trunkId(String trunkId) {
      this.trunkId = Optional.ofNullable(trunkId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "trunk_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage trunkId(Optional<String> trunkId) {
      this.trunkId = trunkId;
      return this;
    }

    @java.lang.Override
    public _FinalStage terminatedTo(Nullable<String> terminatedTo) {
      if (terminatedTo.isNull()) {
        this.terminatedTo = null;
      }
      else if (terminatedTo.isEmpty()) {
        this.terminatedTo = Optional.empty();
      }
      else {
        this.terminatedTo = Optional.of(terminatedTo.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage terminatedTo(String terminatedTo) {
      this.terminatedTo = Optional.ofNullable(terminatedTo);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "terminated_to",
        nulls = Nulls.SKIP
    )
    public _FinalStage terminatedTo(Optional<String> terminatedTo) {
      this.terminatedTo = terminatedTo;
      return this;
    }

    @java.lang.Override
    public _FinalStage sipUserAgent(Nullable<String> sipUserAgent) {
      if (sipUserAgent.isNull()) {
        this.sipUserAgent = null;
      }
      else if (sipUserAgent.isEmpty()) {
        this.sipUserAgent = Optional.empty();
      }
      else {
        this.sipUserAgent = Optional.of(sipUserAgent.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage sipUserAgent(String sipUserAgent) {
      this.sipUserAgent = Optional.ofNullable(sipUserAgent);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "sip_user_agent",
        nulls = Nulls.SKIP
    )
    public _FinalStage sipUserAgent(Optional<String> sipUserAgent) {
      this.sipUserAgent = sipUserAgent;
      return this;
    }

    @java.lang.Override
    public _FinalStage progressTime(Nullable<String> progressTime) {
      if (progressTime.isNull()) {
        this.progressTime = null;
      }
      else if (progressTime.isEmpty()) {
        this.progressTime = Optional.empty();
      }
      else {
        this.progressTime = Optional.of(progressTime.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage progressTime(String progressTime) {
      this.progressTime = Optional.ofNullable(progressTime);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "progress_time",
        nulls = Nulls.SKIP
    )
    public _FinalStage progressTime(Optional<String> progressTime) {
      this.progressTime = progressTime;
      return this;
    }

    @java.lang.Override
    public _FinalStage packetLoss(Nullable<Double> packetLoss) {
      if (packetLoss.isNull()) {
        this.packetLoss = null;
      }
      else if (packetLoss.isEmpty()) {
        this.packetLoss = Optional.empty();
      }
      else {
        this.packetLoss = Optional.of(packetLoss.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage packetLoss(Double packetLoss) {
      this.packetLoss = Optional.ofNullable(packetLoss);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "packet_loss",
        nulls = Nulls.SKIP
    )
    public _FinalStage packetLoss(Optional<Double> packetLoss) {
      this.packetLoss = packetLoss;
      return this;
    }

    @java.lang.Override
    public _FinalStage networkAddr(Nullable<String> networkAddr) {
      if (networkAddr.isNull()) {
        this.networkAddr = null;
      }
      else if (networkAddr.isEmpty()) {
        this.networkAddr = Optional.empty();
      }
      else {
        this.networkAddr = Optional.of(networkAddr.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage networkAddr(String networkAddr) {
      this.networkAddr = Optional.ofNullable(networkAddr);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "network_addr",
        nulls = Nulls.SKIP
    )
    public _FinalStage networkAddr(Optional<String> networkAddr) {
      this.networkAddr = networkAddr;
      return this;
    }

    @java.lang.Override
    public _FinalStage mos(Nullable<Double> mos) {
      if (mos.isNull()) {
        this.mos = null;
      }
      else if (mos.isEmpty()) {
        this.mos = Optional.empty();
      }
      else {
        this.mos = Optional.of(mos.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage mos(Double mos) {
      this.mos = Optional.ofNullable(mos);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "mos",
        nulls = Nulls.SKIP
    )
    public _FinalStage mos(Optional<Double> mos) {
      this.mos = mos;
      return this;
    }

    @java.lang.Override
    public _FinalStage jitter(Nullable<Double> jitter) {
      if (jitter.isNull()) {
        this.jitter = null;
      }
      else if (jitter.isEmpty()) {
        this.jitter = Optional.empty();
      }
      else {
        this.jitter = Optional.of(jitter.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage jitter(Double jitter) {
      this.jitter = Optional.ofNullable(jitter);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "jitter",
        nulls = Nulls.SKIP
    )
    public _FinalStage jitter(Optional<Double> jitter) {
      this.jitter = jitter;
      return this;
    }

    @java.lang.Override
    public _FinalStage hangupSource(Nullable<String> hangupSource) {
      if (hangupSource.isNull()) {
        this.hangupSource = null;
      }
      else if (hangupSource.isEmpty()) {
        this.hangupSource = Optional.empty();
      }
      else {
        this.hangupSource = Optional.of(hangupSource.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage hangupSource(String hangupSource) {
      this.hangupSource = Optional.ofNullable(hangupSource);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "hangup_source",
        nulls = Nulls.SKIP
    )
    public _FinalStage hangupSource(Optional<String> hangupSource) {
      this.hangupSource = hangupSource;
      return this;
    }

    @java.lang.Override
    public _FinalStage hangupDisposition(Nullable<String> hangupDisposition) {
      if (hangupDisposition.isNull()) {
        this.hangupDisposition = null;
      }
      else if (hangupDisposition.isEmpty()) {
        this.hangupDisposition = Optional.empty();
      }
      else {
        this.hangupDisposition = Optional.of(hangupDisposition.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage hangupDisposition(String hangupDisposition) {
      this.hangupDisposition = Optional.ofNullable(hangupDisposition);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "hangup_disposition",
        nulls = Nulls.SKIP
    )
    public _FinalStage hangupDisposition(Optional<String> hangupDisposition) {
      this.hangupDisposition = hangupDisposition;
      return this;
    }

    @java.lang.Override
    public _FinalStage hangupCauseName(Nullable<String> hangupCauseName) {
      if (hangupCauseName.isNull()) {
        this.hangupCauseName = null;
      }
      else if (hangupCauseName.isEmpty()) {
        this.hangupCauseName = Optional.empty();
      }
      else {
        this.hangupCauseName = Optional.of(hangupCauseName.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage hangupCauseName(String hangupCauseName) {
      this.hangupCauseName = Optional.ofNullable(hangupCauseName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "hangup_cause_name",
        nulls = Nulls.SKIP
    )
    public _FinalStage hangupCauseName(Optional<String> hangupCauseName) {
      this.hangupCauseName = hangupCauseName;
      return this;
    }

    @java.lang.Override
    public _FinalStage hangupCauseCode(Nullable<Integer> hangupCauseCode) {
      if (hangupCauseCode.isNull()) {
        this.hangupCauseCode = null;
      }
      else if (hangupCauseCode.isEmpty()) {
        this.hangupCauseCode = Optional.empty();
      }
      else {
        this.hangupCauseCode = Optional.of(hangupCauseCode.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage hangupCauseCode(Integer hangupCauseCode) {
      this.hangupCauseCode = Optional.ofNullable(hangupCauseCode);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "hangup_cause_code",
        nulls = Nulls.SKIP
    )
    public _FinalStage hangupCauseCode(Optional<Integer> hangupCauseCode) {
      this.hangupCauseCode = hangupCauseCode;
      return this;
    }

    @java.lang.Override
    public _FinalStage hangupCause(Nullable<String> hangupCause) {
      if (hangupCause.isNull()) {
        this.hangupCause = null;
      }
      else if (hangupCause.isEmpty()) {
        this.hangupCause = Optional.empty();
      }
      else {
        this.hangupCause = Optional.of(hangupCause.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage hangupCause(String hangupCause) {
      this.hangupCause = Optional.ofNullable(hangupCause);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "hangup_cause",
        nulls = Nulls.SKIP
    )
    public _FinalStage hangupCause(Optional<String> hangupCause) {
      this.hangupCause = hangupCause;
      return this;
    }

    @java.lang.Override
    public _FinalStage failureReason(Nullable<String> failureReason) {
      if (failureReason.isNull()) {
        this.failureReason = null;
      }
      else if (failureReason.isEmpty()) {
        this.failureReason = Optional.empty();
      }
      else {
        this.failureReason = Optional.of(failureReason.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage failureReason(String failureReason) {
      this.failureReason = Optional.ofNullable(failureReason);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "failure_reason",
        nulls = Nulls.SKIP
    )
    public _FinalStage failureReason(Optional<String> failureReason) {
      this.failureReason = failureReason;
      return this;
    }

    @java.lang.Override
    public _FinalStage failureCode(Nullable<String> failureCode) {
      if (failureCode.isNull()) {
        this.failureCode = null;
      }
      else if (failureCode.isEmpty()) {
        this.failureCode = Optional.empty();
      }
      else {
        this.failureCode = Optional.of(failureCode.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage failureCode(String failureCode) {
      this.failureCode = Optional.ofNullable(failureCode);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "failure_code",
        nulls = Nulls.SKIP
    )
    public _FinalStage failureCode(Optional<String> failureCode) {
      this.failureCode = failureCode;
      return this;
    }

    @java.lang.Override
    public _FinalStage customerEndpoint(Nullable<Object> customerEndpoint) {
      if (customerEndpoint.isNull()) {
        this.customerEndpoint = null;
      }
      else if (customerEndpoint.isEmpty()) {
        this.customerEndpoint = Optional.empty();
      }
      else {
        this.customerEndpoint = Optional.of(customerEndpoint.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage customerEndpoint(Object customerEndpoint) {
      this.customerEndpoint = Optional.ofNullable(customerEndpoint);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "customer_endpoint",
        nulls = Nulls.SKIP
    )
    public _FinalStage customerEndpoint(Optional<Object> customerEndpoint) {
      this.customerEndpoint = customerEndpoint;
      return this;
    }

    @java.lang.Override
    public _FinalStage codec(Nullable<String> codec) {
      if (codec.isNull()) {
        this.codec = null;
      }
      else if (codec.isEmpty()) {
        this.codec = Optional.empty();
      }
      else {
        this.codec = Optional.of(codec.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage codec(String codec) {
      this.codec = Optional.ofNullable(codec);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "codec",
        nulls = Nulls.SKIP
    )
    public _FinalStage codec(Optional<String> codec) {
      this.codec = codec;
      return this;
    }

    @java.lang.Override
    public _FinalStage carrierIp(Nullable<Object> carrierIp) {
      if (carrierIp.isNull()) {
        this.carrierIp = null;
      }
      else if (carrierIp.isEmpty()) {
        this.carrierIp = Optional.empty();
      }
      else {
        this.carrierIp = Optional.of(carrierIp.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage carrierIp(Object carrierIp) {
      this.carrierIp = Optional.ofNullable(carrierIp);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "carrier_ip",
        nulls = Nulls.SKIP
    )
    public _FinalStage carrierIp(Optional<Object> carrierIp) {
      this.carrierIp = carrierIp;
      return this;
    }

    @java.lang.Override
    public _FinalStage campaignId(Nullable<Object> campaignId) {
      if (campaignId.isNull()) {
        this.campaignId = null;
      }
      else if (campaignId.isEmpty()) {
        this.campaignId = Optional.empty();
      }
      else {
        this.campaignId = Optional.of(campaignId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage campaignId(Object campaignId) {
      this.campaignId = Optional.ofNullable(campaignId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "campaign_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage campaignId(Optional<Object> campaignId) {
      this.campaignId = campaignId;
      return this;
    }

    @java.lang.Override
    public _FinalStage bridgeUuid(Nullable<String> bridgeUuid) {
      if (bridgeUuid.isNull()) {
        this.bridgeUuid = null;
      }
      else if (bridgeUuid.isEmpty()) {
        this.bridgeUuid = Optional.empty();
      }
      else {
        this.bridgeUuid = Optional.of(bridgeUuid.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage bridgeUuid(String bridgeUuid) {
      this.bridgeUuid = Optional.ofNullable(bridgeUuid);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "bridge_uuid",
        nulls = Nulls.SKIP
    )
    public _FinalStage bridgeUuid(Optional<String> bridgeUuid) {
      this.bridgeUuid = bridgeUuid;
      return this;
    }

    @java.lang.Override
    public _FinalStage answerTime(Nullable<String> answerTime) {
      if (answerTime.isNull()) {
        this.answerTime = null;
      }
      else if (answerTime.isEmpty()) {
        this.answerTime = Optional.empty();
      }
      else {
        this.answerTime = Optional.of(answerTime.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage answerTime(String answerTime) {
      this.answerTime = Optional.ofNullable(answerTime);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "answer_time",
        nulls = Nulls.SKIP
    )
    public _FinalStage answerTime(Optional<String> answerTime) {
      this.answerTime = answerTime;
      return this;
    }

    @java.lang.Override
    public SearchCdrsResponseDataItem build() {
      return new SearchCdrsResponseDataItem(accountId, answerTime, billsec, bridgeUuid, callDirection, callerIdName, callerIdNumber, campaignId, carrierIp, codec, context, cost, createdAt, currency, customerEndpoint, destinationNumber, duration, endTime, failureCode, failureReason, hangupCause, hangupCauseCode, hangupCauseName, hangupDisposition, hangupSource, id, jitter, mos, networkAddr, originationRegion, packetLoss, progressTime, region, ringTime, sipCallId, sipUserAgent, startTime, streamingCost, terminatedTo, totalCost, trunkId, updatedAt, uuid, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
