/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.subaccountkyc.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SearchSubaccountCinRequest.Builder.class
)
public final class SearchSubaccountCinRequest {
  private final String companyName;

  private final Map<String, Object> additionalProperties;

  private SearchSubaccountCinRequest(String companyName, Map<String, Object> additionalProperties) {
    this.companyName = companyName;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("company_name")
  public String getCompanyName() {
    return companyName;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SearchSubaccountCinRequest && equalTo((SearchSubaccountCinRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SearchSubaccountCinRequest other) {
    return companyName.equals(other.companyName);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.companyName);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CompanyNameStage builder() {
    return new Builder();
  }

  public interface CompanyNameStage {
    _FinalStage companyName(@NotNull String companyName);

    Builder from(SearchSubaccountCinRequest other);
  }

  public interface _FinalStage {
    SearchSubaccountCinRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CompanyNameStage, _FinalStage {
    private String companyName;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(SearchSubaccountCinRequest other) {
      companyName(other.getCompanyName());
      return this;
    }

    @java.lang.Override
    @JsonSetter("company_name")
    public _FinalStage companyName(@NotNull String companyName) {
      this.companyName = Objects.requireNonNull(companyName, "companyName must not be null");
      return this;
    }

    @java.lang.Override
    public SearchSubaccountCinRequest build() {
      return new SearchSubaccountCinRequest(companyName, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
