/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.speaktext.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import resources.speaktext.types.SpeakTextCallRequestLegs;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SpeakTextCallRequest.Builder.class
)
public final class SpeakTextCallRequest {
  private final String text;

  private final Optional<String> voice;

  private final Optional<String> language;

  private final Optional<SpeakTextCallRequestLegs> legs;

  private final Map<String, Object> additionalProperties;

  private SpeakTextCallRequest(String text, Optional<String> voice, Optional<String> language,
      Optional<SpeakTextCallRequestLegs> legs, Map<String, Object> additionalProperties) {
    this.text = text;
    this.voice = voice;
    this.language = language;
    this.legs = legs;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("text")
  public String getText() {
    return text;
  }

  @JsonProperty("voice")
  public Optional<String> getVoice() {
    return voice;
  }

  @JsonProperty("language")
  public Optional<String> getLanguage() {
    return language;
  }

  @JsonProperty("legs")
  public Optional<SpeakTextCallRequestLegs> getLegs() {
    return legs;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SpeakTextCallRequest && equalTo((SpeakTextCallRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SpeakTextCallRequest other) {
    return text.equals(other.text) && voice.equals(other.voice) && language.equals(other.language) && legs.equals(other.legs);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.text, this.voice, this.language, this.legs);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TextStage builder() {
    return new Builder();
  }

  public interface TextStage {
    _FinalStage text(@NotNull String text);

    Builder from(SpeakTextCallRequest other);
  }

  public interface _FinalStage {
    SpeakTextCallRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage voice(Optional<String> voice);

    _FinalStage voice(String voice);

    _FinalStage language(Optional<String> language);

    _FinalStage language(String language);

    _FinalStage legs(Optional<SpeakTextCallRequestLegs> legs);

    _FinalStage legs(SpeakTextCallRequestLegs legs);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TextStage, _FinalStage {
    private String text;

    private Optional<SpeakTextCallRequestLegs> legs = Optional.empty();

    private Optional<String> language = Optional.empty();

    private Optional<String> voice = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(SpeakTextCallRequest other) {
      text(other.getText());
      voice(other.getVoice());
      language(other.getLanguage());
      legs(other.getLegs());
      return this;
    }

    @java.lang.Override
    @JsonSetter("text")
    public _FinalStage text(@NotNull String text) {
      this.text = Objects.requireNonNull(text, "text must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage legs(SpeakTextCallRequestLegs legs) {
      this.legs = Optional.ofNullable(legs);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "legs",
        nulls = Nulls.SKIP
    )
    public _FinalStage legs(Optional<SpeakTextCallRequestLegs> legs) {
      this.legs = legs;
      return this;
    }

    @java.lang.Override
    public _FinalStage language(String language) {
      this.language = Optional.ofNullable(language);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "language",
        nulls = Nulls.SKIP
    )
    public _FinalStage language(Optional<String> language) {
      this.language = language;
      return this;
    }

    @java.lang.Override
    public _FinalStage voice(String voice) {
      this.voice = Optional.ofNullable(voice);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "voice",
        nulls = Nulls.SKIP
    )
    public _FinalStage voice(Optional<String> voice) {
      this.voice = voice;
      return this;
    }

    @java.lang.Override
    public SpeakTextCallRequest build() {
      return new SpeakTextCallRequest(text, voice, language, legs, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
