/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.subaccounts.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import resources.subaccounts.types.UpdateSubaccountRequestKycMode;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdateSubaccountRequest.Builder.class
)
public final class UpdateSubaccountRequest {
  private final Optional<String> name;

  private final Optional<Boolean> enabled;

  private final Optional<UpdateSubaccountRequestKycMode> kycMode;

  private final Map<String, Object> additionalProperties;

  private UpdateSubaccountRequest(Optional<String> name, Optional<Boolean> enabled,
      Optional<UpdateSubaccountRequestKycMode> kycMode, Map<String, Object> additionalProperties) {
    this.name = name;
    this.enabled = enabled;
    this.kycMode = kycMode;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  @JsonProperty("enabled")
  public Optional<Boolean> getEnabled() {
    return enabled;
  }

  /**
   * @return Change the verification mode. Promoting to <code>customer_use</code> requires the sub-account to have an <code>email</code>.
   */
  @JsonProperty("kyc_mode")
  public Optional<UpdateSubaccountRequestKycMode> getKycMode() {
    return kycMode;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdateSubaccountRequest && equalTo((UpdateSubaccountRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpdateSubaccountRequest other) {
    return name.equals(other.name) && enabled.equals(other.enabled) && kycMode.equals(other.kycMode);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.enabled, this.kycMode);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> name = Optional.empty();

    private Optional<Boolean> enabled = Optional.empty();

    private Optional<UpdateSubaccountRequestKycMode> kycMode = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(UpdateSubaccountRequest other) {
      name(other.getName());
      enabled(other.getEnabled());
      kycMode(other.getKycMode());
      return this;
    }

    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @JsonSetter(
        value = "enabled",
        nulls = Nulls.SKIP
    )
    public Builder enabled(Optional<Boolean> enabled) {
      this.enabled = enabled;
      return this;
    }

    public Builder enabled(Boolean enabled) {
      this.enabled = Optional.ofNullable(enabled);
      return this;
    }

    /**
     * <p>Change the verification mode. Promoting to <code>customer_use</code> requires the sub-account to have an <code>email</code>.</p>
     */
    @JsonSetter(
        value = "kyc_mode",
        nulls = Nulls.SKIP
    )
    public Builder kycMode(Optional<UpdateSubaccountRequestKycMode> kycMode) {
      this.kycMode = kycMode;
      return this;
    }

    public Builder kycMode(UpdateSubaccountRequestKycMode kycMode) {
      this.kycMode = Optional.ofNullable(kycMode);
      return this;
    }

    public UpdateSubaccountRequest build() {
      return new UpdateSubaccountRequest(name, enabled, kycMode, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
