/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.conferences.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListConferencesResponse.Builder.class
)
public final class ListConferencesResponse {
  private final String apiId;

  private final List<Object> conferences;

  private final Map<String, Object> additionalProperties;

  private ListConferencesResponse(String apiId, List<Object> conferences,
      Map<String, Object> additionalProperties) {
    this.apiId = apiId;
    this.conferences = conferences;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("api_id")
  public String getApiId() {
    return apiId;
  }

  @JsonProperty("conferences")
  public List<Object> getConferences() {
    return conferences;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListConferencesResponse && equalTo((ListConferencesResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListConferencesResponse other) {
    return apiId.equals(other.apiId) && conferences.equals(other.conferences);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.apiId, this.conferences);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ApiIdStage builder() {
    return new Builder();
  }

  public interface ApiIdStage {
    _FinalStage apiId(@NotNull String apiId);

    Builder from(ListConferencesResponse other);
  }

  public interface _FinalStage {
    ListConferencesResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage conferences(List<Object> conferences);

    _FinalStage addConferences(Object conferences);

    _FinalStage addAllConferences(List<Object> conferences);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ApiIdStage, _FinalStage {
    private String apiId;

    private List<Object> conferences = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ListConferencesResponse other) {
      apiId(other.getApiId());
      conferences(other.getConferences());
      return this;
    }

    @java.lang.Override
    @JsonSetter("api_id")
    public _FinalStage apiId(@NotNull String apiId) {
      this.apiId = Objects.requireNonNull(apiId, "apiId must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllConferences(List<Object> conferences) {
      if (conferences != null) {
        this.conferences.addAll(conferences);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addConferences(Object conferences) {
      this.conferences.add(conferences);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "conferences",
        nulls = Nulls.SKIP
    )
    public _FinalStage conferences(List<Object> conferences) {
      this.conferences.clear();
      if (conferences != null) {
        this.conferences.addAll(conferences);
      }
      return this;
    }

    @java.lang.Override
    public ListConferencesResponse build() {
      return new ListConferencesResponse(apiId, conferences, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
