/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.speaktext.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class SpeakTextCallRequestLegs {
  public static final SpeakTextCallRequestLegs BLEG = new SpeakTextCallRequestLegs(Value.BLEG, "bleg");

  public static final SpeakTextCallRequestLegs BOTH = new SpeakTextCallRequestLegs(Value.BOTH, "both");

  public static final SpeakTextCallRequestLegs ALEG = new SpeakTextCallRequestLegs(Value.ALEG, "aleg");

  private final Value value;

  private final String string;

  SpeakTextCallRequestLegs(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof SpeakTextCallRequestLegs && this.string.equals(((SpeakTextCallRequestLegs) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case BLEG:
        return visitor.visitBleg();
      case BOTH:
        return visitor.visitBoth();
      case ALEG:
        return visitor.visitAleg();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static SpeakTextCallRequestLegs valueOf(String value) {
    switch (value) {
      case "bleg":
        return BLEG;
      case "both":
        return BOTH;
      case "aleg":
        return ALEG;
      default:
        return new SpeakTextCallRequestLegs(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    ALEG,

    BLEG,

    BOTH,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitAleg();

    T visitBleg();

    T visitBoth();

    T visitUnknown(String unknownType);
  }
}
