/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.applications;

import core.ClientOptions;
import core.RequestOptions;
import java.lang.String;
import java.util.Optional;
import resources.applications.requests.CreateApplicationRequest;
import resources.applications.requests.DeleteApplicationRequest;
import resources.applications.requests.ListApplicationsRequest;
import resources.applications.requests.RetrieveApplicationRequest;
import resources.applications.requests.UpdateApplicationRequest;
import resources.applications.types.CreateApplicationResponse;
import resources.applications.types.ListApplicationsResponse;
import resources.applications.types.RetrieveApplicationResponse;
import resources.applications.types.UpdateApplicationResponse;

public class ApplicationsClient {
  protected final ClientOptions clientOptions;

  private final RawApplicationsClient rawClient;

  public ApplicationsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawApplicationsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawApplicationsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Get details of all applications created under your Vobiz account.
   */
  public ListApplicationsResponse listApplications(String authId) {
    return this.rawClient.listApplications(authId).body();
  }

  /**
   * Get details of all applications created under your Vobiz account.
   */
  public ListApplicationsResponse listApplications(String authId, RequestOptions requestOptions) {
    return this.rawClient.listApplications(authId, requestOptions).body();
  }

  /**
   * Get details of all applications created under your Vobiz account.
   */
  public ListApplicationsResponse listApplications(String authId, ListApplicationsRequest request) {
    return this.rawClient.listApplications(authId, request).body();
  }

  /**
   * Get details of all applications created under your Vobiz account.
   */
  public ListApplicationsResponse listApplications(String authId, ListApplicationsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.listApplications(authId, request, requestOptions).body();
  }

  /**
   * Creates an Application with webhook URLs for call handling.
   * Creating an application is usually a first step, after which you
   * attach the application to either a number or an endpoint.
   */
  public CreateApplicationResponse createApplication(String authId,
      CreateApplicationRequest request) {
    return this.rawClient.createApplication(authId, request).body();
  }

  /**
   * Creates an Application with webhook URLs for call handling.
   * Creating an application is usually a first step, after which you
   * attach the application to either a number or an endpoint.
   */
  public CreateApplicationResponse createApplication(String authId,
      CreateApplicationRequest request, RequestOptions requestOptions) {
    return this.rawClient.createApplication(authId, request, requestOptions).body();
  }

  /**
   * Get details of a particular application by passing the app_id.
   */
  public RetrieveApplicationResponse retrieveApplication(String authId, String appId) {
    return this.rawClient.retrieveApplication(authId, appId).body();
  }

  /**
   * Get details of a particular application by passing the app_id.
   */
  public RetrieveApplicationResponse retrieveApplication(String authId, String appId,
      RequestOptions requestOptions) {
    return this.rawClient.retrieveApplication(authId, appId, requestOptions).body();
  }

  /**
   * Get details of a particular application by passing the app_id.
   */
  public RetrieveApplicationResponse retrieveApplication(String authId, String appId,
      RetrieveApplicationRequest request) {
    return this.rawClient.retrieveApplication(authId, appId, request).body();
  }

  /**
   * Get details of a particular application by passing the app_id.
   */
  public RetrieveApplicationResponse retrieveApplication(String authId, String appId,
      RetrieveApplicationRequest request, RequestOptions requestOptions) {
    return this.rawClient.retrieveApplication(authId, appId, request, requestOptions).body();
  }

  /**
   * Modify an application using this API. You can update any subset of
   * fields (partial update). Fields not provided will remain unchanged.
   */
  public UpdateApplicationResponse updateApplication(String authId, String appId,
      UpdateApplicationRequest request) {
    return this.rawClient.updateApplication(authId, appId, request).body();
  }

  /**
   * Modify an application using this API. You can update any subset of
   * fields (partial update). Fields not provided will remain unchanged.
   */
  public UpdateApplicationResponse updateApplication(String authId, String appId,
      UpdateApplicationRequest request, RequestOptions requestOptions) {
    return this.rawClient.updateApplication(authId, appId, request, requestOptions).body();
  }

  /**
   * Permanently delete an Application. If the application is associated
   * with phone numbers, the deletion may be blocked unless those
   * associations are removed first.
   */
  public Optional<String> deleteApplication(String authId, String appId) {
    return this.rawClient.deleteApplication(authId, appId).body();
  }

  /**
   * Permanently delete an Application. If the application is associated
   * with phone numbers, the deletion may be blocked unless those
   * associations are removed first.
   */
  public Optional<String> deleteApplication(String authId, String appId,
      RequestOptions requestOptions) {
    return this.rawClient.deleteApplication(authId, appId, requestOptions).body();
  }

  /**
   * Permanently delete an Application. If the application is associated
   * with phone numbers, the deletion may be blocked unless those
   * associations are removed first.
   */
  public Optional<String> deleteApplication(String authId, String appId,
      DeleteApplicationRequest request) {
    return this.rawClient.deleteApplication(authId, appId, request).body();
  }

  /**
   * Permanently delete an Application. If the application is associated
   * with phone numbers, the deletion may be blocked unless those
   * associations are removed first.
   */
  public Optional<String> deleteApplication(String authId, String appId,
      DeleteApplicationRequest request, RequestOptions requestOptions) {
    return this.rawClient.deleteApplication(authId, appId, request, requestOptions).body();
  }
}
