/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.calls;

import core.ClientOptions;
import core.RequestOptions;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import resources.calls.requests.MakeCallRequest;
import resources.calls.types.MakeCallResponse;

public class AsyncCallsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawCallsClient rawClient;

  public AsyncCallsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawCallsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawCallsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Initiate an outbound call to a PSTN number or SIP endpoint.
   * Use <code>&lt;</code> to separate multiple destinations (max 1000).
   */
  public CompletableFuture<MakeCallResponse> makeCall(String authId, MakeCallRequest request) {
    return this.rawClient.makeCall(authId, request).thenApply(response -> response.body());
  }

  /**
   * Initiate an outbound call to a PSTN number or SIP endpoint.
   * Use <code>&lt;</code> to separate multiple destinations (max 1000).
   */
  public CompletableFuture<MakeCallResponse> makeCall(String authId, MakeCallRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.makeCall(authId, request, requestOptions).thenApply(response -> response.body());
  }
}
