/**
 * This file was auto-generated by Fern from our API Definition.
 */

package errors;

import core.VobizApiApiException;
import okhttp3.Response;
import types.Error;

public final class InternalServerError extends VobizApiApiException {
  /**
   * The body of the response that triggered the exception.
   */
  private final Error body;

  public InternalServerError(Error body) {
    super("InternalServerError", 500, body);
    this.body = body;
  }

  public InternalServerError(Error body, Response rawResponse) {
    super("InternalServerError", 500, body, rawResponse);
    this.body = body;
  }

  /**
   * @return the body
   */
  @java.lang.Override
  public Error body() {
    return this.body;
  }
}
