/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.playaudio;

import com.fasterxml.jackson.core.JsonProcessingException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.RequestOptions;
import core.VobizApiApiException;
import core.VobizApiException;
import core.VobizApiHttpResponse;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.Void;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import resources.playaudio.requests.PlayAudioCallRequest;
import resources.playaudio.requests.StopAudioCallRequest;

public class AsyncRawPlayAudioClient {
  protected final ClientOptions clientOptions;

  public AsyncRawPlayAudioClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Play an audio file to a live call leg.
   */
  public CompletableFuture<VobizApiHttpResponse<Void>> call(String authId, String callUuid,
      PlayAudioCallRequest request) {
    return call(authId,callUuid,request,null);
  }

  /**
   * Play an audio file to a live call leg.
   */
  public CompletableFuture<VobizApiHttpResponse<Void>> call(String authId, String callUuid,
      PlayAudioCallRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api/v1/Account")
      .addPathSegment(authId)
      .addPathSegments("Call")
      .addPathSegment(callUuid)
      .addPathSegments("Play");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
      }
      catch(JsonProcessingException e) {
        throw new VobizApiException("Failed to serialize request", e);
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<VobizApiHttpResponse<Void>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(new VobizApiHttpResponse<>(null, response));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new VobizApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new VobizApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Stop audio playing on a live call.
     */
    public CompletableFuture<VobizApiHttpResponse<Void>> stopAudioCall(String authId,
        String callUuid) {
      return stopAudioCall(authId,callUuid,StopAudioCallRequest.builder().build());
    }

    /**
     * Stop audio playing on a live call.
     */
    public CompletableFuture<VobizApiHttpResponse<Void>> stopAudioCall(String authId,
        String callUuid, RequestOptions requestOptions) {
      return stopAudioCall(authId,callUuid,StopAudioCallRequest.builder().build(),requestOptions);
    }

    /**
     * Stop audio playing on a live call.
     */
    public CompletableFuture<VobizApiHttpResponse<Void>> stopAudioCall(String authId,
        String callUuid, StopAudioCallRequest request) {
      return stopAudioCall(authId,callUuid,request,null);
    }

    /**
     * Stop audio playing on a live call.
     */
    public CompletableFuture<VobizApiHttpResponse<Void>> stopAudioCall(String authId,
        String callUuid, StopAudioCallRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("api/v1/Account")
        .addPathSegment(authId)
        .addPathSegments("Call")
        .addPathSegment(callUuid)
        .addPathSegments("Play");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("DELETE", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)));
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<VobizApiHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(new VobizApiHttpResponse<>(null, response));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              future.completeExceptionally(new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new VobizApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new VobizApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }
    }
