/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.subaccounts.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateSubaccountResponse.Builder.class
)
public final class CreateSubaccountResponse {
  private final String message;

  private final CreateSubaccountResponseSubAccount subAccount;

  private final CreateSubaccountResponseAuthCredentials authCredentials;

  private final CreateSubaccountResponseTokens tokens;

  private final Map<String, Object> additionalProperties;

  private CreateSubaccountResponse(String message, CreateSubaccountResponseSubAccount subAccount,
      CreateSubaccountResponseAuthCredentials authCredentials,
      CreateSubaccountResponseTokens tokens, Map<String, Object> additionalProperties) {
    this.message = message;
    this.subAccount = subAccount;
    this.authCredentials = authCredentials;
    this.tokens = tokens;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("message")
  public String getMessage() {
    return message;
  }

  @JsonProperty("sub_account")
  public CreateSubaccountResponseSubAccount getSubAccount() {
    return subAccount;
  }

  @JsonProperty("auth_credentials")
  public CreateSubaccountResponseAuthCredentials getAuthCredentials() {
    return authCredentials;
  }

  @JsonProperty("tokens")
  public CreateSubaccountResponseTokens getTokens() {
    return tokens;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateSubaccountResponse && equalTo((CreateSubaccountResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateSubaccountResponse other) {
    return message.equals(other.message) && subAccount.equals(other.subAccount) && authCredentials.equals(other.authCredentials) && tokens.equals(other.tokens);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.message, this.subAccount, this.authCredentials, this.tokens);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static MessageStage builder() {
    return new Builder();
  }

  public interface MessageStage {
    SubAccountStage message(@NotNull String message);

    Builder from(CreateSubaccountResponse other);
  }

  public interface SubAccountStage {
    AuthCredentialsStage subAccount(@NotNull CreateSubaccountResponseSubAccount subAccount);
  }

  public interface AuthCredentialsStage {
    TokensStage authCredentials(@NotNull CreateSubaccountResponseAuthCredentials authCredentials);
  }

  public interface TokensStage {
    _FinalStage tokens(@NotNull CreateSubaccountResponseTokens tokens);
  }

  public interface _FinalStage {
    CreateSubaccountResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements MessageStage, SubAccountStage, AuthCredentialsStage, TokensStage, _FinalStage {
    private String message;

    private CreateSubaccountResponseSubAccount subAccount;

    private CreateSubaccountResponseAuthCredentials authCredentials;

    private CreateSubaccountResponseTokens tokens;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateSubaccountResponse other) {
      message(other.getMessage());
      subAccount(other.getSubAccount());
      authCredentials(other.getAuthCredentials());
      tokens(other.getTokens());
      return this;
    }

    @java.lang.Override
    @JsonSetter("message")
    public SubAccountStage message(@NotNull String message) {
      this.message = Objects.requireNonNull(message, "message must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("sub_account")
    public AuthCredentialsStage subAccount(@NotNull CreateSubaccountResponseSubAccount subAccount) {
      this.subAccount = Objects.requireNonNull(subAccount, "subAccount must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("auth_credentials")
    public TokensStage authCredentials(
        @NotNull CreateSubaccountResponseAuthCredentials authCredentials) {
      this.authCredentials = Objects.requireNonNull(authCredentials, "authCredentials must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("tokens")
    public _FinalStage tokens(@NotNull CreateSubaccountResponseTokens tokens) {
      this.tokens = Objects.requireNonNull(tokens, "tokens must not be null");
      return this;
    }

    @java.lang.Override
    public CreateSubaccountResponse build() {
      return new CreateSubaccountResponse(message, subAccount, authCredentials, tokens, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
