/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = Account.Builder.class
)
public final class Account {
  private final Optional<String> id;

  private final Optional<String> name;

  private final Optional<String> email;

  private final Optional<String> authId;

  private final Optional<AccountAccountType> accountType;

  private final Optional<Boolean> enabled;

  private final Optional<Boolean> isActive;

  private final Optional<Integer> cpsLimit;

  private final Optional<Integer> concurrentCallsLimit;

  private final Optional<OffsetDateTime> createdAt;

  private final Map<String, Object> additionalProperties;

  private Account(Optional<String> id, Optional<String> name, Optional<String> email,
      Optional<String> authId, Optional<AccountAccountType> accountType, Optional<Boolean> enabled,
      Optional<Boolean> isActive, Optional<Integer> cpsLimit,
      Optional<Integer> concurrentCallsLimit, Optional<OffsetDateTime> createdAt,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.email = email;
    this.authId = authId;
    this.accountType = accountType;
    this.enabled = enabled;
    this.isActive = isActive;
    this.cpsLimit = cpsLimit;
    this.concurrentCallsLimit = concurrentCallsLimit;
    this.createdAt = createdAt;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public Optional<String> getId() {
    return id;
  }

  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  @JsonProperty("email")
  public Optional<String> getEmail() {
    return email;
  }

  @JsonProperty("auth_id")
  public Optional<String> getAuthId() {
    return authId;
  }

  @JsonProperty("account_type")
  public Optional<AccountAccountType> getAccountType() {
    return accountType;
  }

  @JsonProperty("enabled")
  public Optional<Boolean> getEnabled() {
    return enabled;
  }

  @JsonProperty("is_active")
  public Optional<Boolean> getIsActive() {
    return isActive;
  }

  @JsonProperty("cps_limit")
  public Optional<Integer> getCpsLimit() {
    return cpsLimit;
  }

  @JsonProperty("concurrent_calls_limit")
  public Optional<Integer> getConcurrentCallsLimit() {
    return concurrentCallsLimit;
  }

  @JsonProperty("created_at")
  public Optional<OffsetDateTime> getCreatedAt() {
    return createdAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Account && equalTo((Account) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Account other) {
    return id.equals(other.id) && name.equals(other.name) && email.equals(other.email) && authId.equals(other.authId) && accountType.equals(other.accountType) && enabled.equals(other.enabled) && isActive.equals(other.isActive) && cpsLimit.equals(other.cpsLimit) && concurrentCallsLimit.equals(other.concurrentCallsLimit) && createdAt.equals(other.createdAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name, this.email, this.authId, this.accountType, this.enabled, this.isActive, this.cpsLimit, this.concurrentCallsLimit, this.createdAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> id = Optional.empty();

    private Optional<String> name = Optional.empty();

    private Optional<String> email = Optional.empty();

    private Optional<String> authId = Optional.empty();

    private Optional<AccountAccountType> accountType = Optional.empty();

    private Optional<Boolean> enabled = Optional.empty();

    private Optional<Boolean> isActive = Optional.empty();

    private Optional<Integer> cpsLimit = Optional.empty();

    private Optional<Integer> concurrentCallsLimit = Optional.empty();

    private Optional<OffsetDateTime> createdAt = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(Account other) {
      id(other.getId());
      name(other.getName());
      email(other.getEmail());
      authId(other.getAuthId());
      accountType(other.getAccountType());
      enabled(other.getEnabled());
      isActive(other.getIsActive());
      cpsLimit(other.getCpsLimit());
      concurrentCallsLimit(other.getConcurrentCallsLimit());
      createdAt(other.getCreatedAt());
      return this;
    }

    @JsonSetter(
        value = "id",
        nulls = Nulls.SKIP
    )
    public Builder id(Optional<String> id) {
      this.id = id;
      return this;
    }

    public Builder id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @JsonSetter(
        value = "email",
        nulls = Nulls.SKIP
    )
    public Builder email(Optional<String> email) {
      this.email = email;
      return this;
    }

    public Builder email(String email) {
      this.email = Optional.ofNullable(email);
      return this;
    }

    @JsonSetter(
        value = "auth_id",
        nulls = Nulls.SKIP
    )
    public Builder authId(Optional<String> authId) {
      this.authId = authId;
      return this;
    }

    public Builder authId(String authId) {
      this.authId = Optional.ofNullable(authId);
      return this;
    }

    @JsonSetter(
        value = "account_type",
        nulls = Nulls.SKIP
    )
    public Builder accountType(Optional<AccountAccountType> accountType) {
      this.accountType = accountType;
      return this;
    }

    public Builder accountType(AccountAccountType accountType) {
      this.accountType = Optional.ofNullable(accountType);
      return this;
    }

    @JsonSetter(
        value = "enabled",
        nulls = Nulls.SKIP
    )
    public Builder enabled(Optional<Boolean> enabled) {
      this.enabled = enabled;
      return this;
    }

    public Builder enabled(Boolean enabled) {
      this.enabled = Optional.ofNullable(enabled);
      return this;
    }

    @JsonSetter(
        value = "is_active",
        nulls = Nulls.SKIP
    )
    public Builder isActive(Optional<Boolean> isActive) {
      this.isActive = isActive;
      return this;
    }

    public Builder isActive(Boolean isActive) {
      this.isActive = Optional.ofNullable(isActive);
      return this;
    }

    @JsonSetter(
        value = "cps_limit",
        nulls = Nulls.SKIP
    )
    public Builder cpsLimit(Optional<Integer> cpsLimit) {
      this.cpsLimit = cpsLimit;
      return this;
    }

    public Builder cpsLimit(Integer cpsLimit) {
      this.cpsLimit = Optional.ofNullable(cpsLimit);
      return this;
    }

    @JsonSetter(
        value = "concurrent_calls_limit",
        nulls = Nulls.SKIP
    )
    public Builder concurrentCallsLimit(Optional<Integer> concurrentCallsLimit) {
      this.concurrentCallsLimit = concurrentCallsLimit;
      return this;
    }

    public Builder concurrentCallsLimit(Integer concurrentCallsLimit) {
      this.concurrentCallsLimit = Optional.ofNullable(concurrentCallsLimit);
      return this;
    }

    @JsonSetter(
        value = "created_at",
        nulls = Nulls.SKIP
    )
    public Builder createdAt(Optional<OffsetDateTime> createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    public Builder createdAt(OffsetDateTime createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }

    public Account build() {
      return new Account(id, name, email, authId, accountType, enabled, isActive, cpsLimit, concurrentCallsLimit, createdAt, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
