/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = Balance.Builder.class
)
public final class Balance {
  private final Optional<String> authId;

  private final Optional<String> balance;

  private final Optional<String> currency;

  private final Optional<Boolean> autoRecharge;

  private final Map<String, Object> additionalProperties;

  private Balance(Optional<String> authId, Optional<String> balance, Optional<String> currency,
      Optional<Boolean> autoRecharge, Map<String, Object> additionalProperties) {
    this.authId = authId;
    this.balance = balance;
    this.currency = currency;
    this.autoRecharge = autoRecharge;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("auth_id")
  public Optional<String> getAuthId() {
    return authId;
  }

  @JsonProperty("balance")
  public Optional<String> getBalance() {
    return balance;
  }

  @JsonProperty("currency")
  public Optional<String> getCurrency() {
    return currency;
  }

  @JsonProperty("auto_recharge")
  public Optional<Boolean> getAutoRecharge() {
    return autoRecharge;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Balance && equalTo((Balance) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Balance other) {
    return authId.equals(other.authId) && balance.equals(other.balance) && currency.equals(other.currency) && autoRecharge.equals(other.autoRecharge);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.authId, this.balance, this.currency, this.autoRecharge);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> authId = Optional.empty();

    private Optional<String> balance = Optional.empty();

    private Optional<String> currency = Optional.empty();

    private Optional<Boolean> autoRecharge = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(Balance other) {
      authId(other.getAuthId());
      balance(other.getBalance());
      currency(other.getCurrency());
      autoRecharge(other.getAutoRecharge());
      return this;
    }

    @JsonSetter(
        value = "auth_id",
        nulls = Nulls.SKIP
    )
    public Builder authId(Optional<String> authId) {
      this.authId = authId;
      return this;
    }

    public Builder authId(String authId) {
      this.authId = Optional.ofNullable(authId);
      return this;
    }

    @JsonSetter(
        value = "balance",
        nulls = Nulls.SKIP
    )
    public Builder balance(Optional<String> balance) {
      this.balance = balance;
      return this;
    }

    public Builder balance(String balance) {
      this.balance = Optional.ofNullable(balance);
      return this;
    }

    @JsonSetter(
        value = "currency",
        nulls = Nulls.SKIP
    )
    public Builder currency(Optional<String> currency) {
      this.currency = currency;
      return this;
    }

    public Builder currency(String currency) {
      this.currency = Optional.ofNullable(currency);
      return this;
    }

    @JsonSetter(
        value = "auto_recharge",
        nulls = Nulls.SKIP
    )
    public Builder autoRecharge(Optional<Boolean> autoRecharge) {
      this.autoRecharge = autoRecharge;
      return this;
    }

    public Builder autoRecharge(Boolean autoRecharge) {
      this.autoRecharge = Optional.ofNullable(autoRecharge);
      return this;
    }

    public Balance build() {
      return new Balance(authId, balance, currency, autoRecharge, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
