/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class CapacityResourceType {
  public static final CapacityResourceType CPS = new CapacityResourceType(Value.CPS, "cps");

  public static final CapacityResourceType CONCURRENT_CALLS = new CapacityResourceType(Value.CONCURRENT_CALLS, "concurrent_calls");

  private final Value value;

  private final String string;

  CapacityResourceType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof CapacityResourceType && this.string.equals(((CapacityResourceType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CPS:
        return visitor.visitCps();
      case CONCURRENT_CALLS:
        return visitor.visitConcurrentCalls();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static CapacityResourceType valueOf(String value) {
    switch (value) {
      case "cps":
        return CPS;
      case "concurrent_calls":
        return CONCURRENT_CALLS;
      default:
        return new CapacityResourceType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    CONCURRENT_CALLS,

    CPS,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitConcurrentCalls();

    T visitCps();

    T visitUnknown(String unknownType);
  }
}
