/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = KycVerificationResult.Builder.class
)
public final class KycVerificationResult {
  private final KycVerificationResultVerificationType verificationType;

  private final KycVerificationResultStatus status;

  private final Optional<Boolean> kycCallsBlocked;

  private final Optional<Boolean> mock;

  private final Map<String, Object> additionalProperties;

  private KycVerificationResult(KycVerificationResultVerificationType verificationType,
      KycVerificationResultStatus status, Optional<Boolean> kycCallsBlocked, Optional<Boolean> mock,
      Map<String, Object> additionalProperties) {
    this.verificationType = verificationType;
    this.status = status;
    this.kycCallsBlocked = kycCallsBlocked;
    this.mock = mock;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("verification_type")
  public KycVerificationResultVerificationType getVerificationType() {
    return verificationType;
  }

  @JsonProperty("status")
  public KycVerificationResultStatus getStatus() {
    return status;
  }

  /**
   * @return Recomputed sub-account call-blocking state after this verification.
   */
  @JsonProperty("kyc_calls_blocked")
  public Optional<Boolean> getKycCallsBlocked() {
    return kycCallsBlocked;
  }

  /**
   * @return Present and <code>true</code> on responses from the test-mode endpoints.
   */
  @JsonProperty("mock")
  public Optional<Boolean> getMock() {
    return mock;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof KycVerificationResult && equalTo((KycVerificationResult) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(KycVerificationResult other) {
    return verificationType.equals(other.verificationType) && status.equals(other.status) && kycCallsBlocked.equals(other.kycCallsBlocked) && mock.equals(other.mock);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.verificationType, this.status, this.kycCallsBlocked, this.mock);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static VerificationTypeStage builder() {
    return new Builder();
  }

  public interface VerificationTypeStage {
    StatusStage verificationType(@NotNull KycVerificationResultVerificationType verificationType);

    Builder from(KycVerificationResult other);
  }

  public interface StatusStage {
    _FinalStage status(@NotNull KycVerificationResultStatus status);
  }

  public interface _FinalStage {
    KycVerificationResult build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Recomputed sub-account call-blocking state after this verification.</p>
     */
    _FinalStage kycCallsBlocked(Optional<Boolean> kycCallsBlocked);

    _FinalStage kycCallsBlocked(Boolean kycCallsBlocked);

    /**
     * <p>Present and <code>true</code> on responses from the test-mode endpoints.</p>
     */
    _FinalStage mock(Optional<Boolean> mock);

    _FinalStage mock(Boolean mock);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements VerificationTypeStage, StatusStage, _FinalStage {
    private KycVerificationResultVerificationType verificationType;

    private KycVerificationResultStatus status;

    private Optional<Boolean> mock = Optional.empty();

    private Optional<Boolean> kycCallsBlocked = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(KycVerificationResult other) {
      verificationType(other.getVerificationType());
      status(other.getStatus());
      kycCallsBlocked(other.getKycCallsBlocked());
      mock(other.getMock());
      return this;
    }

    @java.lang.Override
    @JsonSetter("verification_type")
    public StatusStage verificationType(
        @NotNull KycVerificationResultVerificationType verificationType) {
      this.verificationType = Objects.requireNonNull(verificationType, "verificationType must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("status")
    public _FinalStage status(@NotNull KycVerificationResultStatus status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    /**
     * <p>Present and <code>true</code> on responses from the test-mode endpoints.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage mock(Boolean mock) {
      this.mock = Optional.ofNullable(mock);
      return this;
    }

    /**
     * <p>Present and <code>true</code> on responses from the test-mode endpoints.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "mock",
        nulls = Nulls.SKIP
    )
    public _FinalStage mock(Optional<Boolean> mock) {
      this.mock = mock;
      return this;
    }

    /**
     * <p>Recomputed sub-account call-blocking state after this verification.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage kycCallsBlocked(Boolean kycCallsBlocked) {
      this.kycCallsBlocked = Optional.ofNullable(kycCallsBlocked);
      return this;
    }

    /**
     * <p>Recomputed sub-account call-blocking state after this verification.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "kyc_calls_blocked",
        nulls = Nulls.SKIP
    )
    public _FinalStage kycCallsBlocked(Optional<Boolean> kycCallsBlocked) {
      this.kycCallsBlocked = kycCallsBlocked;
      return this;
    }

    @java.lang.Override
    public KycVerificationResult build() {
      return new KycVerificationResult(verificationType, status, kycCallsBlocked, mock, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
