/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = NotFoundErrorBody.Builder.class
)
public final class NotFoundErrorBody {
  private final String error;

  private final String apiId;

  private final Map<String, Object> additionalProperties;

  private NotFoundErrorBody(String error, String apiId, Map<String, Object> additionalProperties) {
    this.error = error;
    this.apiId = apiId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("error")
  public String getError() {
    return error;
  }

  @JsonProperty("api_id")
  public String getApiId() {
    return apiId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof NotFoundErrorBody && equalTo((NotFoundErrorBody) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(NotFoundErrorBody other) {
    return error.equals(other.error) && apiId.equals(other.apiId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.error, this.apiId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ErrorStage builder() {
    return new Builder();
  }

  public interface ErrorStage {
    ApiIdStage error(@NotNull String error);

    Builder from(NotFoundErrorBody other);
  }

  public interface ApiIdStage {
    _FinalStage apiId(@NotNull String apiId);
  }

  public interface _FinalStage {
    NotFoundErrorBody build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ErrorStage, ApiIdStage, _FinalStage {
    private String error;

    private String apiId;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(NotFoundErrorBody other) {
      error(other.getError());
      apiId(other.getApiId());
      return this;
    }

    @java.lang.Override
    @JsonSetter("error")
    public ApiIdStage error(@NotNull String error) {
      this.error = Objects.requireNonNull(error, "error must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("api_id")
    public _FinalStage apiId(@NotNull String apiId) {
      this.apiId = Objects.requireNonNull(apiId, "apiId must not be null");
      return this;
    }

    @java.lang.Override
    public NotFoundErrorBody build() {
      return new NotFoundErrorBody(error, apiId, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
