/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Float;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PartnerProfile.Builder.class
)
public final class PartnerProfile {
  private final Optional<String> id;

  private final Optional<String> name;

  private final Optional<String> email;

  private final Optional<String> phone;

  private final Optional<String> company;

  private final Optional<Float> balance;

  private final Optional<String> currency;

  private final Optional<String> gstin;

  private final Optional<String> gstStatus;

  private final Optional<Boolean> tdsApplicable;

  private final Optional<Float> tdsPercentage;

  private final Optional<String> accountType;

  private final Optional<String> status;

  private final Optional<OffsetDateTime> createdAt;

  private final Optional<OffsetDateTime> updatedAt;

  private final Map<String, Object> additionalProperties;

  private PartnerProfile(Optional<String> id, Optional<String> name, Optional<String> email,
      Optional<String> phone, Optional<String> company, Optional<Float> balance,
      Optional<String> currency, Optional<String> gstin, Optional<String> gstStatus,
      Optional<Boolean> tdsApplicable, Optional<Float> tdsPercentage, Optional<String> accountType,
      Optional<String> status, Optional<OffsetDateTime> createdAt,
      Optional<OffsetDateTime> updatedAt, Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.email = email;
    this.phone = phone;
    this.company = company;
    this.balance = balance;
    this.currency = currency;
    this.gstin = gstin;
    this.gstStatus = gstStatus;
    this.tdsApplicable = tdsApplicable;
    this.tdsPercentage = tdsPercentage;
    this.accountType = accountType;
    this.status = status;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Permanent partner ID - required as a filter parameter for Transaction and CDR queries.
   */
  @JsonProperty("id")
  public Optional<String> getId() {
    return id;
  }

  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  @JsonProperty("email")
  public Optional<String> getEmail() {
    return email;
  }

  @JsonProperty("phone")
  public Optional<String> getPhone() {
    return phone;
  }

  @JsonProperty("company")
  public Optional<String> getCompany() {
    return company;
  }

  @JsonProperty("balance")
  public Optional<Float> getBalance() {
    return balance;
  }

  @JsonProperty("currency")
  public Optional<String> getCurrency() {
    return currency;
  }

  @JsonProperty("gstin")
  public Optional<String> getGstin() {
    return gstin;
  }

  @JsonProperty("gst_status")
  public Optional<String> getGstStatus() {
    return gstStatus;
  }

  @JsonProperty("tds_applicable")
  public Optional<Boolean> getTdsApplicable() {
    return tdsApplicable;
  }

  @JsonProperty("tds_percentage")
  public Optional<Float> getTdsPercentage() {
    return tdsPercentage;
  }

  @JsonProperty("account_type")
  public Optional<String> getAccountType() {
    return accountType;
  }

  @JsonProperty("status")
  public Optional<String> getStatus() {
    return status;
  }

  @JsonProperty("created_at")
  public Optional<OffsetDateTime> getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("updated_at")
  public Optional<OffsetDateTime> getUpdatedAt() {
    return updatedAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PartnerProfile && equalTo((PartnerProfile) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PartnerProfile other) {
    return id.equals(other.id) && name.equals(other.name) && email.equals(other.email) && phone.equals(other.phone) && company.equals(other.company) && balance.equals(other.balance) && currency.equals(other.currency) && gstin.equals(other.gstin) && gstStatus.equals(other.gstStatus) && tdsApplicable.equals(other.tdsApplicable) && tdsPercentage.equals(other.tdsPercentage) && accountType.equals(other.accountType) && status.equals(other.status) && createdAt.equals(other.createdAt) && updatedAt.equals(other.updatedAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name, this.email, this.phone, this.company, this.balance, this.currency, this.gstin, this.gstStatus, this.tdsApplicable, this.tdsPercentage, this.accountType, this.status, this.createdAt, this.updatedAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> id = Optional.empty();

    private Optional<String> name = Optional.empty();

    private Optional<String> email = Optional.empty();

    private Optional<String> phone = Optional.empty();

    private Optional<String> company = Optional.empty();

    private Optional<Float> balance = Optional.empty();

    private Optional<String> currency = Optional.empty();

    private Optional<String> gstin = Optional.empty();

    private Optional<String> gstStatus = Optional.empty();

    private Optional<Boolean> tdsApplicable = Optional.empty();

    private Optional<Float> tdsPercentage = Optional.empty();

    private Optional<String> accountType = Optional.empty();

    private Optional<String> status = Optional.empty();

    private Optional<OffsetDateTime> createdAt = Optional.empty();

    private Optional<OffsetDateTime> updatedAt = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(PartnerProfile other) {
      id(other.getId());
      name(other.getName());
      email(other.getEmail());
      phone(other.getPhone());
      company(other.getCompany());
      balance(other.getBalance());
      currency(other.getCurrency());
      gstin(other.getGstin());
      gstStatus(other.getGstStatus());
      tdsApplicable(other.getTdsApplicable());
      tdsPercentage(other.getTdsPercentage());
      accountType(other.getAccountType());
      status(other.getStatus());
      createdAt(other.getCreatedAt());
      updatedAt(other.getUpdatedAt());
      return this;
    }

    /**
     * <p>Permanent partner ID - required as a filter parameter for Transaction and CDR queries.</p>
     */
    @JsonSetter(
        value = "id",
        nulls = Nulls.SKIP
    )
    public Builder id(Optional<String> id) {
      this.id = id;
      return this;
    }

    public Builder id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @JsonSetter(
        value = "email",
        nulls = Nulls.SKIP
    )
    public Builder email(Optional<String> email) {
      this.email = email;
      return this;
    }

    public Builder email(String email) {
      this.email = Optional.ofNullable(email);
      return this;
    }

    @JsonSetter(
        value = "phone",
        nulls = Nulls.SKIP
    )
    public Builder phone(Optional<String> phone) {
      this.phone = phone;
      return this;
    }

    public Builder phone(String phone) {
      this.phone = Optional.ofNullable(phone);
      return this;
    }

    @JsonSetter(
        value = "company",
        nulls = Nulls.SKIP
    )
    public Builder company(Optional<String> company) {
      this.company = company;
      return this;
    }

    public Builder company(String company) {
      this.company = Optional.ofNullable(company);
      return this;
    }

    @JsonSetter(
        value = "balance",
        nulls = Nulls.SKIP
    )
    public Builder balance(Optional<Float> balance) {
      this.balance = balance;
      return this;
    }

    public Builder balance(Float balance) {
      this.balance = Optional.ofNullable(balance);
      return this;
    }

    @JsonSetter(
        value = "currency",
        nulls = Nulls.SKIP
    )
    public Builder currency(Optional<String> currency) {
      this.currency = currency;
      return this;
    }

    public Builder currency(String currency) {
      this.currency = Optional.ofNullable(currency);
      return this;
    }

    @JsonSetter(
        value = "gstin",
        nulls = Nulls.SKIP
    )
    public Builder gstin(Optional<String> gstin) {
      this.gstin = gstin;
      return this;
    }

    public Builder gstin(String gstin) {
      this.gstin = Optional.ofNullable(gstin);
      return this;
    }

    @JsonSetter(
        value = "gst_status",
        nulls = Nulls.SKIP
    )
    public Builder gstStatus(Optional<String> gstStatus) {
      this.gstStatus = gstStatus;
      return this;
    }

    public Builder gstStatus(String gstStatus) {
      this.gstStatus = Optional.ofNullable(gstStatus);
      return this;
    }

    @JsonSetter(
        value = "tds_applicable",
        nulls = Nulls.SKIP
    )
    public Builder tdsApplicable(Optional<Boolean> tdsApplicable) {
      this.tdsApplicable = tdsApplicable;
      return this;
    }

    public Builder tdsApplicable(Boolean tdsApplicable) {
      this.tdsApplicable = Optional.ofNullable(tdsApplicable);
      return this;
    }

    @JsonSetter(
        value = "tds_percentage",
        nulls = Nulls.SKIP
    )
    public Builder tdsPercentage(Optional<Float> tdsPercentage) {
      this.tdsPercentage = tdsPercentage;
      return this;
    }

    public Builder tdsPercentage(Float tdsPercentage) {
      this.tdsPercentage = Optional.ofNullable(tdsPercentage);
      return this;
    }

    @JsonSetter(
        value = "account_type",
        nulls = Nulls.SKIP
    )
    public Builder accountType(Optional<String> accountType) {
      this.accountType = accountType;
      return this;
    }

    public Builder accountType(String accountType) {
      this.accountType = Optional.ofNullable(accountType);
      return this;
    }

    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<String> status) {
      this.status = status;
      return this;
    }

    public Builder status(String status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    @JsonSetter(
        value = "created_at",
        nulls = Nulls.SKIP
    )
    public Builder createdAt(Optional<OffsetDateTime> createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    public Builder createdAt(OffsetDateTime createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }

    @JsonSetter(
        value = "updated_at",
        nulls = Nulls.SKIP
    )
    public Builder updatedAt(Optional<OffsetDateTime> updatedAt) {
      this.updatedAt = updatedAt;
      return this;
    }

    public Builder updatedAt(OffsetDateTime updatedAt) {
      this.updatedAt = Optional.ofNullable(updatedAt);
      return this;
    }

    public PartnerProfile build() {
      return new PartnerProfile(id, name, email, phone, company, balance, currency, gstin, gstStatus, tdsApplicable, tdsPercentage, accountType, status, createdAt, updatedAt, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
