/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PartnerAnalyticsByDirection.Builder.class
)
public final class PartnerAnalyticsByDirection {
  private final Optional<PartnerAnalyticsByDirectionInbound> inbound;

  private final Optional<PartnerAnalyticsByDirectionOutbound> outbound;

  private final Map<String, Object> additionalProperties;

  private PartnerAnalyticsByDirection(Optional<PartnerAnalyticsByDirectionInbound> inbound,
      Optional<PartnerAnalyticsByDirectionOutbound> outbound,
      Map<String, Object> additionalProperties) {
    this.inbound = inbound;
    this.outbound = outbound;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("inbound")
  public Optional<PartnerAnalyticsByDirectionInbound> getInbound() {
    return inbound;
  }

  @JsonProperty("outbound")
  public Optional<PartnerAnalyticsByDirectionOutbound> getOutbound() {
    return outbound;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PartnerAnalyticsByDirection && equalTo((PartnerAnalyticsByDirection) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PartnerAnalyticsByDirection other) {
    return inbound.equals(other.inbound) && outbound.equals(other.outbound);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.inbound, this.outbound);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<PartnerAnalyticsByDirectionInbound> inbound = Optional.empty();

    private Optional<PartnerAnalyticsByDirectionOutbound> outbound = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(PartnerAnalyticsByDirection other) {
      inbound(other.getInbound());
      outbound(other.getOutbound());
      return this;
    }

    @JsonSetter(
        value = "inbound",
        nulls = Nulls.SKIP
    )
    public Builder inbound(Optional<PartnerAnalyticsByDirectionInbound> inbound) {
      this.inbound = inbound;
      return this;
    }

    public Builder inbound(PartnerAnalyticsByDirectionInbound inbound) {
      this.inbound = Optional.ofNullable(inbound);
      return this;
    }

    @JsonSetter(
        value = "outbound",
        nulls = Nulls.SKIP
    )
    public Builder outbound(Optional<PartnerAnalyticsByDirectionOutbound> outbound) {
      this.outbound = outbound;
      return this;
    }

    public Builder outbound(PartnerAnalyticsByDirectionOutbound outbound) {
      this.outbound = Optional.ofNullable(outbound);
      return this;
    }

    public PartnerAnalyticsByDirection build() {
      return new PartnerAnalyticsByDirection(inbound, outbound, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
