/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Float;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PartnerAnalyticsTopCustomersItem.Builder.class
)
public final class PartnerAnalyticsTopCustomersItem {
  private final Optional<String> authId;

  private final Optional<String> name;

  private final Optional<Integer> calls;

  private final Optional<Float> cost;

  private final Map<String, Object> additionalProperties;

  private PartnerAnalyticsTopCustomersItem(Optional<String> authId, Optional<String> name,
      Optional<Integer> calls, Optional<Float> cost, Map<String, Object> additionalProperties) {
    this.authId = authId;
    this.name = name;
    this.calls = calls;
    this.cost = cost;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("auth_id")
  public Optional<String> getAuthId() {
    return authId;
  }

  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  @JsonProperty("calls")
  public Optional<Integer> getCalls() {
    return calls;
  }

  @JsonProperty("cost")
  public Optional<Float> getCost() {
    return cost;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PartnerAnalyticsTopCustomersItem && equalTo((PartnerAnalyticsTopCustomersItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PartnerAnalyticsTopCustomersItem other) {
    return authId.equals(other.authId) && name.equals(other.name) && calls.equals(other.calls) && cost.equals(other.cost);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.authId, this.name, this.calls, this.cost);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> authId = Optional.empty();

    private Optional<String> name = Optional.empty();

    private Optional<Integer> calls = Optional.empty();

    private Optional<Float> cost = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(PartnerAnalyticsTopCustomersItem other) {
      authId(other.getAuthId());
      name(other.getName());
      calls(other.getCalls());
      cost(other.getCost());
      return this;
    }

    @JsonSetter(
        value = "auth_id",
        nulls = Nulls.SKIP
    )
    public Builder authId(Optional<String> authId) {
      this.authId = authId;
      return this;
    }

    public Builder authId(String authId) {
      this.authId = Optional.ofNullable(authId);
      return this;
    }

    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @JsonSetter(
        value = "calls",
        nulls = Nulls.SKIP
    )
    public Builder calls(Optional<Integer> calls) {
      this.calls = calls;
      return this;
    }

    public Builder calls(Integer calls) {
      this.calls = Optional.ofNullable(calls);
      return this;
    }

    @JsonSetter(
        value = "cost",
        nulls = Nulls.SKIP
    )
    public Builder cost(Optional<Float> cost) {
      this.cost = cost;
      return this;
    }

    public Builder cost(Float cost) {
      this.cost = Optional.ofNullable(cost);
      return this;
    }

    public PartnerAnalyticsTopCustomersItem build() {
      return new PartnerAnalyticsTopCustomersItem(authId, name, calls, cost, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
