/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Float;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PurchasedNumber.Builder.class
)
public final class PurchasedNumber {
  private final Optional<String> id;

  private final Optional<String> authId;

  private final Optional<String> e164;

  private final Optional<String> country;

  private final Optional<String> region;

  private final Optional<String> status;

  private final Optional<String> provider;

  private final Optional<Float> setupFee;

  private final Optional<Float> monthlyFee;

  private final Optional<String> currency;

  private final Optional<OffsetDateTime> purchasedAt;

  private final Optional<OffsetDateTime> createdAt;

  private final Optional<OffsetDateTime> updatedAt;

  private final Map<String, Object> additionalProperties;

  private PurchasedNumber(Optional<String> id, Optional<String> authId, Optional<String> e164,
      Optional<String> country, Optional<String> region, Optional<String> status,
      Optional<String> provider, Optional<Float> setupFee, Optional<Float> monthlyFee,
      Optional<String> currency, Optional<OffsetDateTime> purchasedAt,
      Optional<OffsetDateTime> createdAt, Optional<OffsetDateTime> updatedAt,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.authId = authId;
    this.e164 = e164;
    this.country = country;
    this.region = region;
    this.status = status;
    this.provider = provider;
    this.setupFee = setupFee;
    this.monthlyFee = monthlyFee;
    this.currency = currency;
    this.purchasedAt = purchasedAt;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public Optional<String> getId() {
    return id;
  }

  @JsonProperty("auth_id")
  public Optional<String> getAuthId() {
    return authId;
  }

  @JsonProperty("e164")
  public Optional<String> getE164() {
    return e164;
  }

  @JsonProperty("country")
  public Optional<String> getCountry() {
    return country;
  }

  @JsonProperty("region")
  public Optional<String> getRegion() {
    return region;
  }

  @JsonProperty("status")
  public Optional<String> getStatus() {
    return status;
  }

  @JsonProperty("provider")
  public Optional<String> getProvider() {
    return provider;
  }

  @JsonProperty("setup_fee")
  public Optional<Float> getSetupFee() {
    return setupFee;
  }

  @JsonProperty("monthly_fee")
  public Optional<Float> getMonthlyFee() {
    return monthlyFee;
  }

  @JsonProperty("currency")
  public Optional<String> getCurrency() {
    return currency;
  }

  @JsonProperty("purchased_at")
  public Optional<OffsetDateTime> getPurchasedAt() {
    return purchasedAt;
  }

  @JsonProperty("created_at")
  public Optional<OffsetDateTime> getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("updated_at")
  public Optional<OffsetDateTime> getUpdatedAt() {
    return updatedAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PurchasedNumber && equalTo((PurchasedNumber) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PurchasedNumber other) {
    return id.equals(other.id) && authId.equals(other.authId) && e164.equals(other.e164) && country.equals(other.country) && region.equals(other.region) && status.equals(other.status) && provider.equals(other.provider) && setupFee.equals(other.setupFee) && monthlyFee.equals(other.monthlyFee) && currency.equals(other.currency) && purchasedAt.equals(other.purchasedAt) && createdAt.equals(other.createdAt) && updatedAt.equals(other.updatedAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.authId, this.e164, this.country, this.region, this.status, this.provider, this.setupFee, this.monthlyFee, this.currency, this.purchasedAt, this.createdAt, this.updatedAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> id = Optional.empty();

    private Optional<String> authId = Optional.empty();

    private Optional<String> e164 = Optional.empty();

    private Optional<String> country = Optional.empty();

    private Optional<String> region = Optional.empty();

    private Optional<String> status = Optional.empty();

    private Optional<String> provider = Optional.empty();

    private Optional<Float> setupFee = Optional.empty();

    private Optional<Float> monthlyFee = Optional.empty();

    private Optional<String> currency = Optional.empty();

    private Optional<OffsetDateTime> purchasedAt = Optional.empty();

    private Optional<OffsetDateTime> createdAt = Optional.empty();

    private Optional<OffsetDateTime> updatedAt = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(PurchasedNumber other) {
      id(other.getId());
      authId(other.getAuthId());
      e164(other.getE164());
      country(other.getCountry());
      region(other.getRegion());
      status(other.getStatus());
      provider(other.getProvider());
      setupFee(other.getSetupFee());
      monthlyFee(other.getMonthlyFee());
      currency(other.getCurrency());
      purchasedAt(other.getPurchasedAt());
      createdAt(other.getCreatedAt());
      updatedAt(other.getUpdatedAt());
      return this;
    }

    @JsonSetter(
        value = "id",
        nulls = Nulls.SKIP
    )
    public Builder id(Optional<String> id) {
      this.id = id;
      return this;
    }

    public Builder id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    @JsonSetter(
        value = "auth_id",
        nulls = Nulls.SKIP
    )
    public Builder authId(Optional<String> authId) {
      this.authId = authId;
      return this;
    }

    public Builder authId(String authId) {
      this.authId = Optional.ofNullable(authId);
      return this;
    }

    @JsonSetter(
        value = "e164",
        nulls = Nulls.SKIP
    )
    public Builder e164(Optional<String> e164) {
      this.e164 = e164;
      return this;
    }

    public Builder e164(String e164) {
      this.e164 = Optional.ofNullable(e164);
      return this;
    }

    @JsonSetter(
        value = "country",
        nulls = Nulls.SKIP
    )
    public Builder country(Optional<String> country) {
      this.country = country;
      return this;
    }

    public Builder country(String country) {
      this.country = Optional.ofNullable(country);
      return this;
    }

    @JsonSetter(
        value = "region",
        nulls = Nulls.SKIP
    )
    public Builder region(Optional<String> region) {
      this.region = region;
      return this;
    }

    public Builder region(String region) {
      this.region = Optional.ofNullable(region);
      return this;
    }

    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<String> status) {
      this.status = status;
      return this;
    }

    public Builder status(String status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    @JsonSetter(
        value = "provider",
        nulls = Nulls.SKIP
    )
    public Builder provider(Optional<String> provider) {
      this.provider = provider;
      return this;
    }

    public Builder provider(String provider) {
      this.provider = Optional.ofNullable(provider);
      return this;
    }

    @JsonSetter(
        value = "setup_fee",
        nulls = Nulls.SKIP
    )
    public Builder setupFee(Optional<Float> setupFee) {
      this.setupFee = setupFee;
      return this;
    }

    public Builder setupFee(Float setupFee) {
      this.setupFee = Optional.ofNullable(setupFee);
      return this;
    }

    @JsonSetter(
        value = "monthly_fee",
        nulls = Nulls.SKIP
    )
    public Builder monthlyFee(Optional<Float> monthlyFee) {
      this.monthlyFee = monthlyFee;
      return this;
    }

    public Builder monthlyFee(Float monthlyFee) {
      this.monthlyFee = Optional.ofNullable(monthlyFee);
      return this;
    }

    @JsonSetter(
        value = "currency",
        nulls = Nulls.SKIP
    )
    public Builder currency(Optional<String> currency) {
      this.currency = currency;
      return this;
    }

    public Builder currency(String currency) {
      this.currency = Optional.ofNullable(currency);
      return this;
    }

    @JsonSetter(
        value = "purchased_at",
        nulls = Nulls.SKIP
    )
    public Builder purchasedAt(Optional<OffsetDateTime> purchasedAt) {
      this.purchasedAt = purchasedAt;
      return this;
    }

    public Builder purchasedAt(OffsetDateTime purchasedAt) {
      this.purchasedAt = Optional.ofNullable(purchasedAt);
      return this;
    }

    @JsonSetter(
        value = "created_at",
        nulls = Nulls.SKIP
    )
    public Builder createdAt(Optional<OffsetDateTime> createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    public Builder createdAt(OffsetDateTime createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }

    @JsonSetter(
        value = "updated_at",
        nulls = Nulls.SKIP
    )
    public Builder updatedAt(Optional<OffsetDateTime> updatedAt) {
      this.updatedAt = updatedAt;
      return this;
    }

    public Builder updatedAt(OffsetDateTime updatedAt) {
      this.updatedAt = Optional.ofNullable(updatedAt);
      return this;
    }

    public PurchasedNumber build() {
      return new PurchasedNumber(id, authId, e164, country, region, status, provider, setupFee, monthlyFee, currency, purchasedAt, createdAt, updatedAt, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
