/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SubAccount.Builder.class
)
public final class SubAccount {
  private final Optional<String> authId;

  private final Optional<String> authToken;

  private final Optional<String> name;

  private final Optional<Boolean> enabled;

  private final Optional<SubAccountKycMode> kycMode;

  private final Optional<String> businessType;

  private final Optional<Boolean> kycCallsBlocked;

  private final Optional<OffsetDateTime> createdAt;

  private final Map<String, Object> additionalProperties;

  private SubAccount(Optional<String> authId, Optional<String> authToken, Optional<String> name,
      Optional<Boolean> enabled, Optional<SubAccountKycMode> kycMode, Optional<String> businessType,
      Optional<Boolean> kycCallsBlocked, Optional<OffsetDateTime> createdAt,
      Map<String, Object> additionalProperties) {
    this.authId = authId;
    this.authToken = authToken;
    this.name = name;
    this.enabled = enabled;
    this.kycMode = kycMode;
    this.businessType = businessType;
    this.kycCallsBlocked = kycCallsBlocked;
    this.createdAt = createdAt;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("auth_id")
  public Optional<String> getAuthId() {
    return authId;
  }

  @JsonProperty("auth_token")
  public Optional<String> getAuthToken() {
    return authToken;
  }

  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  @JsonProperty("enabled")
  public Optional<Boolean> getEnabled() {
    return enabled;
  }

  /**
   * @return Verification mode. <code>customer_use</code> sub-accounts must complete their own KYC before placing calls.
   */
  @JsonProperty("kyc_mode")
  public Optional<SubAccountKycMode> getKycMode() {
    return kycMode;
  }

  /**
   * @return Legal constitution of the customer (e.g. <code>private_limited</code>).
   */
  @JsonProperty("business_type")
  public Optional<String> getBusinessType() {
    return businessType;
  }

  /**
   * @return True while a <code>customer_use</code> sub-account has not yet completed the KYC required to place calls.
   */
  @JsonProperty("kyc_calls_blocked")
  public Optional<Boolean> getKycCallsBlocked() {
    return kycCallsBlocked;
  }

  @JsonProperty("created_at")
  public Optional<OffsetDateTime> getCreatedAt() {
    return createdAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SubAccount && equalTo((SubAccount) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SubAccount other) {
    return authId.equals(other.authId) && authToken.equals(other.authToken) && name.equals(other.name) && enabled.equals(other.enabled) && kycMode.equals(other.kycMode) && businessType.equals(other.businessType) && kycCallsBlocked.equals(other.kycCallsBlocked) && createdAt.equals(other.createdAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.authId, this.authToken, this.name, this.enabled, this.kycMode, this.businessType, this.kycCallsBlocked, this.createdAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> authId = Optional.empty();

    private Optional<String> authToken = Optional.empty();

    private Optional<String> name = Optional.empty();

    private Optional<Boolean> enabled = Optional.empty();

    private Optional<SubAccountKycMode> kycMode = Optional.empty();

    private Optional<String> businessType = Optional.empty();

    private Optional<Boolean> kycCallsBlocked = Optional.empty();

    private Optional<OffsetDateTime> createdAt = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(SubAccount other) {
      authId(other.getAuthId());
      authToken(other.getAuthToken());
      name(other.getName());
      enabled(other.getEnabled());
      kycMode(other.getKycMode());
      businessType(other.getBusinessType());
      kycCallsBlocked(other.getKycCallsBlocked());
      createdAt(other.getCreatedAt());
      return this;
    }

    @JsonSetter(
        value = "auth_id",
        nulls = Nulls.SKIP
    )
    public Builder authId(Optional<String> authId) {
      this.authId = authId;
      return this;
    }

    public Builder authId(String authId) {
      this.authId = Optional.ofNullable(authId);
      return this;
    }

    @JsonSetter(
        value = "auth_token",
        nulls = Nulls.SKIP
    )
    public Builder authToken(Optional<String> authToken) {
      this.authToken = authToken;
      return this;
    }

    public Builder authToken(String authToken) {
      this.authToken = Optional.ofNullable(authToken);
      return this;
    }

    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @JsonSetter(
        value = "enabled",
        nulls = Nulls.SKIP
    )
    public Builder enabled(Optional<Boolean> enabled) {
      this.enabled = enabled;
      return this;
    }

    public Builder enabled(Boolean enabled) {
      this.enabled = Optional.ofNullable(enabled);
      return this;
    }

    /**
     * <p>Verification mode. <code>customer_use</code> sub-accounts must complete their own KYC before placing calls.</p>
     */
    @JsonSetter(
        value = "kyc_mode",
        nulls = Nulls.SKIP
    )
    public Builder kycMode(Optional<SubAccountKycMode> kycMode) {
      this.kycMode = kycMode;
      return this;
    }

    public Builder kycMode(SubAccountKycMode kycMode) {
      this.kycMode = Optional.ofNullable(kycMode);
      return this;
    }

    /**
     * <p>Legal constitution of the customer (e.g. <code>private_limited</code>).</p>
     */
    @JsonSetter(
        value = "business_type",
        nulls = Nulls.SKIP
    )
    public Builder businessType(Optional<String> businessType) {
      this.businessType = businessType;
      return this;
    }

    public Builder businessType(String businessType) {
      this.businessType = Optional.ofNullable(businessType);
      return this;
    }

    /**
     * <p>True while a <code>customer_use</code> sub-account has not yet completed the KYC required to place calls.</p>
     */
    @JsonSetter(
        value = "kyc_calls_blocked",
        nulls = Nulls.SKIP
    )
    public Builder kycCallsBlocked(Optional<Boolean> kycCallsBlocked) {
      this.kycCallsBlocked = kycCallsBlocked;
      return this;
    }

    public Builder kycCallsBlocked(Boolean kycCallsBlocked) {
      this.kycCallsBlocked = Optional.ofNullable(kycCallsBlocked);
      return this;
    }

    @JsonSetter(
        value = "created_at",
        nulls = Nulls.SKIP
    )
    public Builder createdAt(Optional<OffsetDateTime> createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    public Builder createdAt(OffsetDateTime createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }

    public SubAccount build() {
      return new SubAccount(authId, authToken, name, enabled, kycMode, businessType, kycCallsBlocked, createdAt, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
