/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class SubAccountKycStatusVerificationsValue {
  public static final SubAccountKycStatusVerificationsValue FAILED = new SubAccountKycStatusVerificationsValue(Value.FAILED, "failed");

  public static final SubAccountKycStatusVerificationsValue PENDING = new SubAccountKycStatusVerificationsValue(Value.PENDING, "pending");

  public static final SubAccountKycStatusVerificationsValue NOT_STARTED = new SubAccountKycStatusVerificationsValue(Value.NOT_STARTED, "not_started");

  public static final SubAccountKycStatusVerificationsValue VERIFIED = new SubAccountKycStatusVerificationsValue(Value.VERIFIED, "verified");

  private final Value value;

  private final String string;

  SubAccountKycStatusVerificationsValue(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof SubAccountKycStatusVerificationsValue && this.string.equals(((SubAccountKycStatusVerificationsValue) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case FAILED:
        return visitor.visitFailed();
      case PENDING:
        return visitor.visitPending();
      case NOT_STARTED:
        return visitor.visitNotStarted();
      case VERIFIED:
        return visitor.visitVerified();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static SubAccountKycStatusVerificationsValue valueOf(String value) {
    switch (value) {
      case "failed":
        return FAILED;
      case "pending":
        return PENDING;
      case "not_started":
        return NOT_STARTED;
      case "verified":
        return VERIFIED;
      default:
        return new SubAccountKycStatusVerificationsValue(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    NOT_STARTED,

    PENDING,

    VERIFIED,

    FAILED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitNotStarted();

    T visitPending();

    T visitVerified();

    T visitFailed();

    T visitUnknown(String unknownType);
  }
}
