/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.partnerapi.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateKycSessionRequestReminderScheduleItem.Builder.class
)
public final class CreateKycSessionRequestReminderScheduleItem {
  private final Optional<CreateKycSessionRequestReminderScheduleItemTrigger> trigger;

  private final Optional<Integer> value;

  private final Map<String, Object> additionalProperties;

  private CreateKycSessionRequestReminderScheduleItem(
      Optional<CreateKycSessionRequestReminderScheduleItemTrigger> trigger, Optional<Integer> value,
      Map<String, Object> additionalProperties) {
    this.trigger = trigger;
    this.value = value;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("trigger")
  public Optional<CreateKycSessionRequestReminderScheduleItemTrigger> getTrigger() {
    return trigger;
  }

  @JsonProperty("value")
  public Optional<Integer> getValue() {
    return value;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateKycSessionRequestReminderScheduleItem && equalTo((CreateKycSessionRequestReminderScheduleItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateKycSessionRequestReminderScheduleItem other) {
    return trigger.equals(other.trigger) && value.equals(other.value);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.trigger, this.value);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<CreateKycSessionRequestReminderScheduleItemTrigger> trigger = Optional.empty();

    private Optional<Integer> value = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CreateKycSessionRequestReminderScheduleItem other) {
      trigger(other.getTrigger());
      value(other.getValue());
      return this;
    }

    @JsonSetter(
        value = "trigger",
        nulls = Nulls.SKIP
    )
    public Builder trigger(Optional<CreateKycSessionRequestReminderScheduleItemTrigger> trigger) {
      this.trigger = trigger;
      return this;
    }

    public Builder trigger(CreateKycSessionRequestReminderScheduleItemTrigger trigger) {
      this.trigger = Optional.ofNullable(trigger);
      return this;
    }

    @JsonSetter(
        value = "value",
        nulls = Nulls.SKIP
    )
    public Builder value(Optional<Integer> value) {
      this.value = value;
      return this;
    }

    public Builder value(Integer value) {
      this.value = Optional.ofNullable(value);
      return this;
    }

    public CreateKycSessionRequestReminderScheduleItem build() {
      return new CreateKycSessionRequestReminderScheduleItem(trigger, value, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
