/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.partnerapi.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class CreateKycSessionRequestReminderScheduleItemTrigger {
  public static final CreateKycSessionRequestReminderScheduleItemTrigger DAYS_BEFORE_EXPIRY = new CreateKycSessionRequestReminderScheduleItemTrigger(Value.DAYS_BEFORE_EXPIRY, "days_before_expiry");

  private final Value value;

  private final String string;

  CreateKycSessionRequestReminderScheduleItemTrigger(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof CreateKycSessionRequestReminderScheduleItemTrigger && this.string.equals(((CreateKycSessionRequestReminderScheduleItemTrigger) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case DAYS_BEFORE_EXPIRY:
        return visitor.visitDaysBeforeExpiry();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static CreateKycSessionRequestReminderScheduleItemTrigger valueOf(String value) {
    switch (value) {
      case "days_before_expiry":
        return DAYS_BEFORE_EXPIRY;
      default:
        return new CreateKycSessionRequestReminderScheduleItemTrigger(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    DAYS_BEFORE_EXPIRY,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitDaysBeforeExpiry();

    T visitUnknown(String unknownType);
  }
}
