/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.partnerapi.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListKycSessionsResponseSessionsItemMetadataCustomerRef.Builder.class
)
public final class ListKycSessionsResponseSessionsItemMetadataCustomerRef {
  private final String plan;

  private final String customerRef;

  private final Map<String, Object> additionalProperties;

  private ListKycSessionsResponseSessionsItemMetadataCustomerRef(String plan, String customerRef,
      Map<String, Object> additionalProperties) {
    this.plan = plan;
    this.customerRef = customerRef;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("plan")
  public String getPlan() {
    return plan;
  }

  @JsonProperty("customer_ref")
  public String getCustomerRef() {
    return customerRef;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListKycSessionsResponseSessionsItemMetadataCustomerRef && equalTo((ListKycSessionsResponseSessionsItemMetadataCustomerRef) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListKycSessionsResponseSessionsItemMetadataCustomerRef other) {
    return plan.equals(other.plan) && customerRef.equals(other.customerRef);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.plan, this.customerRef);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static PlanStage builder() {
    return new Builder();
  }

  public interface PlanStage {
    CustomerRefStage plan(@NotNull String plan);

    Builder from(ListKycSessionsResponseSessionsItemMetadataCustomerRef other);
  }

  public interface CustomerRefStage {
    _FinalStage customerRef(@NotNull String customerRef);
  }

  public interface _FinalStage {
    ListKycSessionsResponseSessionsItemMetadataCustomerRef build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements PlanStage, CustomerRefStage, _FinalStage {
    private String plan;

    private String customerRef;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ListKycSessionsResponseSessionsItemMetadataCustomerRef other) {
      plan(other.getPlan());
      customerRef(other.getCustomerRef());
      return this;
    }

    @java.lang.Override
    @JsonSetter("plan")
    public CustomerRefStage plan(@NotNull String plan) {
      this.plan = Objects.requireNonNull(plan, "plan must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("customer_ref")
    public _FinalStage customerRef(@NotNull String customerRef) {
      this.customerRef = Objects.requireNonNull(customerRef, "customerRef must not be null");
      return this;
    }

    @java.lang.Override
    public ListKycSessionsResponseSessionsItemMetadataCustomerRef build() {
      return new ListKycSessionsResponseSessionsItemMetadataCustomerRef(plan, customerRef, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
