/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.partnerapi.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.Nullable;
import core.NullableNonemptyFilter;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListCustomerAccountsResponseAccountsItem.Builder.class
)
public final class ListCustomerAccountsResponseAccountsItem {
  private final String name;

  private final String email;

  private final String phone;

  private final Optional<String> description;

  private final Optional<String> gstin;

  private final Optional<String> gstStatus;

  private final boolean tdsEnabled;

  private final int tdsPercentage;

  private final String businessType;

  private final String id;

  private final String authId;

  private final String apiId;

  private final String accountType;

  private final String role;

  private final boolean postpaid;

  private final Optional<String> address;

  private final Optional<String> city;

  private final Optional<String> state;

  private final Optional<String> timezone;

  private final String country;

  private final Optional<String> zipCode;

  private final String company;

  private final String billingMode;

  private final boolean autoRecharge;

  private final String cashCredits;

  private final int cpsLimit;

  private final int concurrentCallsLimit;

  private final Optional<Object> baseCpsLimit;

  private final Optional<Object> baseConcurrentCallsLimit;

  private final Optional<Object> purchasedCps;

  private final Optional<Object> purchasedConcurrentCalls;

  private final boolean isActive;

  private final boolean isVerified;

  private final boolean isTrialAccount;

  private final boolean enabled;

  private final String kycStatus;

  private final Optional<Object> googleId;

  private final Optional<String> referralCode;

  private final boolean referralDisabled;

  private final Optional<Object> customReferrerRewardAmount;

  private final Optional<Object> customRefereeRewardAmount;

  private final String createdAt;

  private final String updatedAt;

  private final Optional<String> lastLogin;

  private final String pricingTierId;

  private final ListCustomerAccountsResponseAccountsItemPricingTier pricingTier;

  private final String partnerId;

  private final Optional<Object> autoRechargeConfig;

  private final String resourceUri;

  private final String authToken;

  private final Map<String, Object> additionalProperties;

  private ListCustomerAccountsResponseAccountsItem(String name, String email, String phone,
      Optional<String> description, Optional<String> gstin, Optional<String> gstStatus,
      boolean tdsEnabled, int tdsPercentage, String businessType, String id, String authId,
      String apiId, String accountType, String role, boolean postpaid, Optional<String> address,
      Optional<String> city, Optional<String> state, Optional<String> timezone, String country,
      Optional<String> zipCode, String company, String billingMode, boolean autoRecharge,
      String cashCredits, int cpsLimit, int concurrentCallsLimit, Optional<Object> baseCpsLimit,
      Optional<Object> baseConcurrentCallsLimit, Optional<Object> purchasedCps,
      Optional<Object> purchasedConcurrentCalls, boolean isActive, boolean isVerified,
      boolean isTrialAccount, boolean enabled, String kycStatus, Optional<Object> googleId,
      Optional<String> referralCode, boolean referralDisabled,
      Optional<Object> customReferrerRewardAmount, Optional<Object> customRefereeRewardAmount,
      String createdAt, String updatedAt, Optional<String> lastLogin, String pricingTierId,
      ListCustomerAccountsResponseAccountsItemPricingTier pricingTier, String partnerId,
      Optional<Object> autoRechargeConfig, String resourceUri, String authToken,
      Map<String, Object> additionalProperties) {
    this.name = name;
    this.email = email;
    this.phone = phone;
    this.description = description;
    this.gstin = gstin;
    this.gstStatus = gstStatus;
    this.tdsEnabled = tdsEnabled;
    this.tdsPercentage = tdsPercentage;
    this.businessType = businessType;
    this.id = id;
    this.authId = authId;
    this.apiId = apiId;
    this.accountType = accountType;
    this.role = role;
    this.postpaid = postpaid;
    this.address = address;
    this.city = city;
    this.state = state;
    this.timezone = timezone;
    this.country = country;
    this.zipCode = zipCode;
    this.company = company;
    this.billingMode = billingMode;
    this.autoRecharge = autoRecharge;
    this.cashCredits = cashCredits;
    this.cpsLimit = cpsLimit;
    this.concurrentCallsLimit = concurrentCallsLimit;
    this.baseCpsLimit = baseCpsLimit;
    this.baseConcurrentCallsLimit = baseConcurrentCallsLimit;
    this.purchasedCps = purchasedCps;
    this.purchasedConcurrentCalls = purchasedConcurrentCalls;
    this.isActive = isActive;
    this.isVerified = isVerified;
    this.isTrialAccount = isTrialAccount;
    this.enabled = enabled;
    this.kycStatus = kycStatus;
    this.googleId = googleId;
    this.referralCode = referralCode;
    this.referralDisabled = referralDisabled;
    this.customReferrerRewardAmount = customReferrerRewardAmount;
    this.customRefereeRewardAmount = customRefereeRewardAmount;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.lastLogin = lastLogin;
    this.pricingTierId = pricingTierId;
    this.pricingTier = pricingTier;
    this.partnerId = partnerId;
    this.autoRechargeConfig = autoRechargeConfig;
    this.resourceUri = resourceUri;
    this.authToken = authToken;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("email")
  public String getEmail() {
    return email;
  }

  @JsonProperty("phone")
  public String getPhone() {
    return phone;
  }

  @JsonIgnore
  public Optional<String> getDescription() {
    if (description == null) {
      return Optional.empty();
    }
    return description;
  }

  @JsonIgnore
  public Optional<String> getGstin() {
    if (gstin == null) {
      return Optional.empty();
    }
    return gstin;
  }

  @JsonIgnore
  public Optional<String> getGstStatus() {
    if (gstStatus == null) {
      return Optional.empty();
    }
    return gstStatus;
  }

  @JsonProperty("tds_enabled")
  public boolean getTdsEnabled() {
    return tdsEnabled;
  }

  @JsonProperty("tds_percentage")
  public int getTdsPercentage() {
    return tdsPercentage;
  }

  @JsonProperty("business_type")
  public String getBusinessType() {
    return businessType;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("auth_id")
  public String getAuthId() {
    return authId;
  }

  @JsonProperty("api_id")
  public String getApiId() {
    return apiId;
  }

  @JsonProperty("account_type")
  public String getAccountType() {
    return accountType;
  }

  @JsonProperty("role")
  public String getRole() {
    return role;
  }

  @JsonProperty("postpaid")
  public boolean getPostpaid() {
    return postpaid;
  }

  @JsonIgnore
  public Optional<String> getAddress() {
    if (address == null) {
      return Optional.empty();
    }
    return address;
  }

  @JsonIgnore
  public Optional<String> getCity() {
    if (city == null) {
      return Optional.empty();
    }
    return city;
  }

  @JsonIgnore
  public Optional<String> getState() {
    if (state == null) {
      return Optional.empty();
    }
    return state;
  }

  @JsonIgnore
  public Optional<String> getTimezone() {
    if (timezone == null) {
      return Optional.empty();
    }
    return timezone;
  }

  @JsonProperty("country")
  public String getCountry() {
    return country;
  }

  @JsonIgnore
  public Optional<String> getZipCode() {
    if (zipCode == null) {
      return Optional.empty();
    }
    return zipCode;
  }

  @JsonProperty("company")
  public String getCompany() {
    return company;
  }

  @JsonProperty("billing_mode")
  public String getBillingMode() {
    return billingMode;
  }

  @JsonProperty("auto_recharge")
  public boolean getAutoRecharge() {
    return autoRecharge;
  }

  @JsonProperty("cash_credits")
  public String getCashCredits() {
    return cashCredits;
  }

  @JsonProperty("cps_limit")
  public int getCpsLimit() {
    return cpsLimit;
  }

  @JsonProperty("concurrent_calls_limit")
  public int getConcurrentCallsLimit() {
    return concurrentCallsLimit;
  }

  @JsonIgnore
  public Optional<Object> getBaseCpsLimit() {
    if (baseCpsLimit == null) {
      return Optional.empty();
    }
    return baseCpsLimit;
  }

  @JsonIgnore
  public Optional<Object> getBaseConcurrentCallsLimit() {
    if (baseConcurrentCallsLimit == null) {
      return Optional.empty();
    }
    return baseConcurrentCallsLimit;
  }

  @JsonIgnore
  public Optional<Object> getPurchasedCps() {
    if (purchasedCps == null) {
      return Optional.empty();
    }
    return purchasedCps;
  }

  @JsonIgnore
  public Optional<Object> getPurchasedConcurrentCalls() {
    if (purchasedConcurrentCalls == null) {
      return Optional.empty();
    }
    return purchasedConcurrentCalls;
  }

  @JsonProperty("is_active")
  public boolean getIsActive() {
    return isActive;
  }

  @JsonProperty("is_verified")
  public boolean getIsVerified() {
    return isVerified;
  }

  @JsonProperty("is_trial_account")
  public boolean getIsTrialAccount() {
    return isTrialAccount;
  }

  @JsonProperty("enabled")
  public boolean getEnabled() {
    return enabled;
  }

  @JsonProperty("kyc_status")
  public String getKycStatus() {
    return kycStatus;
  }

  @JsonIgnore
  public Optional<Object> getGoogleId() {
    if (googleId == null) {
      return Optional.empty();
    }
    return googleId;
  }

  @JsonIgnore
  public Optional<String> getReferralCode() {
    if (referralCode == null) {
      return Optional.empty();
    }
    return referralCode;
  }

  @JsonProperty("referral_disabled")
  public boolean getReferralDisabled() {
    return referralDisabled;
  }

  @JsonIgnore
  public Optional<Object> getCustomReferrerRewardAmount() {
    if (customReferrerRewardAmount == null) {
      return Optional.empty();
    }
    return customReferrerRewardAmount;
  }

  @JsonIgnore
  public Optional<Object> getCustomRefereeRewardAmount() {
    if (customRefereeRewardAmount == null) {
      return Optional.empty();
    }
    return customRefereeRewardAmount;
  }

  @JsonProperty("created_at")
  public String getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("updated_at")
  public String getUpdatedAt() {
    return updatedAt;
  }

  @JsonIgnore
  public Optional<String> getLastLogin() {
    if (lastLogin == null) {
      return Optional.empty();
    }
    return lastLogin;
  }

  @JsonProperty("pricing_tier_id")
  public String getPricingTierId() {
    return pricingTierId;
  }

  @JsonProperty("pricing_tier")
  public ListCustomerAccountsResponseAccountsItemPricingTier getPricingTier() {
    return pricingTier;
  }

  @JsonProperty("partner_id")
  public String getPartnerId() {
    return partnerId;
  }

  @JsonIgnore
  public Optional<Object> getAutoRechargeConfig() {
    if (autoRechargeConfig == null) {
      return Optional.empty();
    }
    return autoRechargeConfig;
  }

  @JsonProperty("resource_uri")
  public String getResourceUri() {
    return resourceUri;
  }

  @JsonProperty("auth_token")
  public String getAuthToken() {
    return authToken;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("description")
  private Optional<String> _getDescription() {
    return description;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("gstin")
  private Optional<String> _getGstin() {
    return gstin;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("gst_status")
  private Optional<String> _getGstStatus() {
    return gstStatus;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("address")
  private Optional<String> _getAddress() {
    return address;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("city")
  private Optional<String> _getCity() {
    return city;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("state")
  private Optional<String> _getState() {
    return state;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("timezone")
  private Optional<String> _getTimezone() {
    return timezone;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("zip_code")
  private Optional<String> _getZipCode() {
    return zipCode;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("base_cps_limit")
  private Optional<Object> _getBaseCpsLimit() {
    return baseCpsLimit;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("base_concurrent_calls_limit")
  private Optional<Object> _getBaseConcurrentCallsLimit() {
    return baseConcurrentCallsLimit;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("purchased_cps")
  private Optional<Object> _getPurchasedCps() {
    return purchasedCps;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("purchased_concurrent_calls")
  private Optional<Object> _getPurchasedConcurrentCalls() {
    return purchasedConcurrentCalls;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("google_id")
  private Optional<Object> _getGoogleId() {
    return googleId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("referral_code")
  private Optional<String> _getReferralCode() {
    return referralCode;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("custom_referrer_reward_amount")
  private Optional<Object> _getCustomReferrerRewardAmount() {
    return customReferrerRewardAmount;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("custom_referee_reward_amount")
  private Optional<Object> _getCustomRefereeRewardAmount() {
    return customRefereeRewardAmount;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("last_login")
  private Optional<String> _getLastLogin() {
    return lastLogin;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("auto_recharge_config")
  private Optional<Object> _getAutoRechargeConfig() {
    return autoRechargeConfig;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListCustomerAccountsResponseAccountsItem && equalTo((ListCustomerAccountsResponseAccountsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListCustomerAccountsResponseAccountsItem other) {
    return name.equals(other.name) && email.equals(other.email) && phone.equals(other.phone) && description.equals(other.description) && gstin.equals(other.gstin) && gstStatus.equals(other.gstStatus) && tdsEnabled == other.tdsEnabled && tdsPercentage == other.tdsPercentage && businessType.equals(other.businessType) && id.equals(other.id) && authId.equals(other.authId) && apiId.equals(other.apiId) && accountType.equals(other.accountType) && role.equals(other.role) && postpaid == other.postpaid && address.equals(other.address) && city.equals(other.city) && state.equals(other.state) && timezone.equals(other.timezone) && country.equals(other.country) && zipCode.equals(other.zipCode) && company.equals(other.company) && billingMode.equals(other.billingMode) && autoRecharge == other.autoRecharge && cashCredits.equals(other.cashCredits) && cpsLimit == other.cpsLimit && concurrentCallsLimit == other.concurrentCallsLimit && baseCpsLimit.equals(other.baseCpsLimit) && baseConcurrentCallsLimit.equals(other.baseConcurrentCallsLimit) && purchasedCps.equals(other.purchasedCps) && purchasedConcurrentCalls.equals(other.purchasedConcurrentCalls) && isActive == other.isActive && isVerified == other.isVerified && isTrialAccount == other.isTrialAccount && enabled == other.enabled && kycStatus.equals(other.kycStatus) && googleId.equals(other.googleId) && referralCode.equals(other.referralCode) && referralDisabled == other.referralDisabled && customReferrerRewardAmount.equals(other.customReferrerRewardAmount) && customRefereeRewardAmount.equals(other.customRefereeRewardAmount) && createdAt.equals(other.createdAt) && updatedAt.equals(other.updatedAt) && lastLogin.equals(other.lastLogin) && pricingTierId.equals(other.pricingTierId) && pricingTier.equals(other.pricingTier) && partnerId.equals(other.partnerId) && autoRechargeConfig.equals(other.autoRechargeConfig) && resourceUri.equals(other.resourceUri) && authToken.equals(other.authToken);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.email, this.phone, this.description, this.gstin, this.gstStatus, this.tdsEnabled, this.tdsPercentage, this.businessType, this.id, this.authId, this.apiId, this.accountType, this.role, this.postpaid, this.address, this.city, this.state, this.timezone, this.country, this.zipCode, this.company, this.billingMode, this.autoRecharge, this.cashCredits, this.cpsLimit, this.concurrentCallsLimit, this.baseCpsLimit, this.baseConcurrentCallsLimit, this.purchasedCps, this.purchasedConcurrentCalls, this.isActive, this.isVerified, this.isTrialAccount, this.enabled, this.kycStatus, this.googleId, this.referralCode, this.referralDisabled, this.customReferrerRewardAmount, this.customRefereeRewardAmount, this.createdAt, this.updatedAt, this.lastLogin, this.pricingTierId, this.pricingTier, this.partnerId, this.autoRechargeConfig, this.resourceUri, this.authToken);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    EmailStage name(@NotNull String name);

    Builder from(ListCustomerAccountsResponseAccountsItem other);
  }

  public interface EmailStage {
    PhoneStage email(@NotNull String email);
  }

  public interface PhoneStage {
    TdsEnabledStage phone(@NotNull String phone);
  }

  public interface TdsEnabledStage {
    TdsPercentageStage tdsEnabled(boolean tdsEnabled);
  }

  public interface TdsPercentageStage {
    BusinessTypeStage tdsPercentage(int tdsPercentage);
  }

  public interface BusinessTypeStage {
    IdStage businessType(@NotNull String businessType);
  }

  public interface IdStage {
    AuthIdStage id(@NotNull String id);
  }

  public interface AuthIdStage {
    ApiIdStage authId(@NotNull String authId);
  }

  public interface ApiIdStage {
    AccountTypeStage apiId(@NotNull String apiId);
  }

  public interface AccountTypeStage {
    RoleStage accountType(@NotNull String accountType);
  }

  public interface RoleStage {
    PostpaidStage role(@NotNull String role);
  }

  public interface PostpaidStage {
    CountryStage postpaid(boolean postpaid);
  }

  public interface CountryStage {
    CompanyStage country(@NotNull String country);
  }

  public interface CompanyStage {
    BillingModeStage company(@NotNull String company);
  }

  public interface BillingModeStage {
    AutoRechargeStage billingMode(@NotNull String billingMode);
  }

  public interface AutoRechargeStage {
    CashCreditsStage autoRecharge(boolean autoRecharge);
  }

  public interface CashCreditsStage {
    CpsLimitStage cashCredits(@NotNull String cashCredits);
  }

  public interface CpsLimitStage {
    ConcurrentCallsLimitStage cpsLimit(int cpsLimit);
  }

  public interface ConcurrentCallsLimitStage {
    IsActiveStage concurrentCallsLimit(int concurrentCallsLimit);
  }

  public interface IsActiveStage {
    IsVerifiedStage isActive(boolean isActive);
  }

  public interface IsVerifiedStage {
    IsTrialAccountStage isVerified(boolean isVerified);
  }

  public interface IsTrialAccountStage {
    EnabledStage isTrialAccount(boolean isTrialAccount);
  }

  public interface EnabledStage {
    KycStatusStage enabled(boolean enabled);
  }

  public interface KycStatusStage {
    ReferralDisabledStage kycStatus(@NotNull String kycStatus);
  }

  public interface ReferralDisabledStage {
    CreatedAtStage referralDisabled(boolean referralDisabled);
  }

  public interface CreatedAtStage {
    UpdatedAtStage createdAt(@NotNull String createdAt);
  }

  public interface UpdatedAtStage {
    PricingTierIdStage updatedAt(@NotNull String updatedAt);
  }

  public interface PricingTierIdStage {
    PricingTierStage pricingTierId(@NotNull String pricingTierId);
  }

  public interface PricingTierStage {
    PartnerIdStage pricingTier(
        @NotNull ListCustomerAccountsResponseAccountsItemPricingTier pricingTier);
  }

  public interface PartnerIdStage {
    ResourceUriStage partnerId(@NotNull String partnerId);
  }

  public interface ResourceUriStage {
    AuthTokenStage resourceUri(@NotNull String resourceUri);
  }

  public interface AuthTokenStage {
    _FinalStage authToken(@NotNull String authToken);
  }

  public interface _FinalStage {
    ListCustomerAccountsResponseAccountsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    _FinalStage description(Nullable<String> description);

    _FinalStage gstin(Optional<String> gstin);

    _FinalStage gstin(String gstin);

    _FinalStage gstin(Nullable<String> gstin);

    _FinalStage gstStatus(Optional<String> gstStatus);

    _FinalStage gstStatus(String gstStatus);

    _FinalStage gstStatus(Nullable<String> gstStatus);

    _FinalStage address(Optional<String> address);

    _FinalStage address(String address);

    _FinalStage address(Nullable<String> address);

    _FinalStage city(Optional<String> city);

    _FinalStage city(String city);

    _FinalStage city(Nullable<String> city);

    _FinalStage state(Optional<String> state);

    _FinalStage state(String state);

    _FinalStage state(Nullable<String> state);

    _FinalStage timezone(Optional<String> timezone);

    _FinalStage timezone(String timezone);

    _FinalStage timezone(Nullable<String> timezone);

    _FinalStage zipCode(Optional<String> zipCode);

    _FinalStage zipCode(String zipCode);

    _FinalStage zipCode(Nullable<String> zipCode);

    _FinalStage baseCpsLimit(Optional<Object> baseCpsLimit);

    _FinalStage baseCpsLimit(Object baseCpsLimit);

    _FinalStage baseCpsLimit(Nullable<Object> baseCpsLimit);

    _FinalStage baseConcurrentCallsLimit(Optional<Object> baseConcurrentCallsLimit);

    _FinalStage baseConcurrentCallsLimit(Object baseConcurrentCallsLimit);

    _FinalStage baseConcurrentCallsLimit(Nullable<Object> baseConcurrentCallsLimit);

    _FinalStage purchasedCps(Optional<Object> purchasedCps);

    _FinalStage purchasedCps(Object purchasedCps);

    _FinalStage purchasedCps(Nullable<Object> purchasedCps);

    _FinalStage purchasedConcurrentCalls(Optional<Object> purchasedConcurrentCalls);

    _FinalStage purchasedConcurrentCalls(Object purchasedConcurrentCalls);

    _FinalStage purchasedConcurrentCalls(Nullable<Object> purchasedConcurrentCalls);

    _FinalStage googleId(Optional<Object> googleId);

    _FinalStage googleId(Object googleId);

    _FinalStage googleId(Nullable<Object> googleId);

    _FinalStage referralCode(Optional<String> referralCode);

    _FinalStage referralCode(String referralCode);

    _FinalStage referralCode(Nullable<String> referralCode);

    _FinalStage customReferrerRewardAmount(Optional<Object> customReferrerRewardAmount);

    _FinalStage customReferrerRewardAmount(Object customReferrerRewardAmount);

    _FinalStage customReferrerRewardAmount(Nullable<Object> customReferrerRewardAmount);

    _FinalStage customRefereeRewardAmount(Optional<Object> customRefereeRewardAmount);

    _FinalStage customRefereeRewardAmount(Object customRefereeRewardAmount);

    _FinalStage customRefereeRewardAmount(Nullable<Object> customRefereeRewardAmount);

    _FinalStage lastLogin(Optional<String> lastLogin);

    _FinalStage lastLogin(String lastLogin);

    _FinalStage lastLogin(Nullable<String> lastLogin);

    _FinalStage autoRechargeConfig(Optional<Object> autoRechargeConfig);

    _FinalStage autoRechargeConfig(Object autoRechargeConfig);

    _FinalStage autoRechargeConfig(Nullable<Object> autoRechargeConfig);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, EmailStage, PhoneStage, TdsEnabledStage, TdsPercentageStage, BusinessTypeStage, IdStage, AuthIdStage, ApiIdStage, AccountTypeStage, RoleStage, PostpaidStage, CountryStage, CompanyStage, BillingModeStage, AutoRechargeStage, CashCreditsStage, CpsLimitStage, ConcurrentCallsLimitStage, IsActiveStage, IsVerifiedStage, IsTrialAccountStage, EnabledStage, KycStatusStage, ReferralDisabledStage, CreatedAtStage, UpdatedAtStage, PricingTierIdStage, PricingTierStage, PartnerIdStage, ResourceUriStage, AuthTokenStage, _FinalStage {
    private String name;

    private String email;

    private String phone;

    private boolean tdsEnabled;

    private int tdsPercentage;

    private String businessType;

    private String id;

    private String authId;

    private String apiId;

    private String accountType;

    private String role;

    private boolean postpaid;

    private String country;

    private String company;

    private String billingMode;

    private boolean autoRecharge;

    private String cashCredits;

    private int cpsLimit;

    private int concurrentCallsLimit;

    private boolean isActive;

    private boolean isVerified;

    private boolean isTrialAccount;

    private boolean enabled;

    private String kycStatus;

    private boolean referralDisabled;

    private String createdAt;

    private String updatedAt;

    private String pricingTierId;

    private ListCustomerAccountsResponseAccountsItemPricingTier pricingTier;

    private String partnerId;

    private String resourceUri;

    private String authToken;

    private Optional<Object> autoRechargeConfig = Optional.empty();

    private Optional<String> lastLogin = Optional.empty();

    private Optional<Object> customRefereeRewardAmount = Optional.empty();

    private Optional<Object> customReferrerRewardAmount = Optional.empty();

    private Optional<String> referralCode = Optional.empty();

    private Optional<Object> googleId = Optional.empty();

    private Optional<Object> purchasedConcurrentCalls = Optional.empty();

    private Optional<Object> purchasedCps = Optional.empty();

    private Optional<Object> baseConcurrentCallsLimit = Optional.empty();

    private Optional<Object> baseCpsLimit = Optional.empty();

    private Optional<String> zipCode = Optional.empty();

    private Optional<String> timezone = Optional.empty();

    private Optional<String> state = Optional.empty();

    private Optional<String> city = Optional.empty();

    private Optional<String> address = Optional.empty();

    private Optional<String> gstStatus = Optional.empty();

    private Optional<String> gstin = Optional.empty();

    private Optional<String> description = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ListCustomerAccountsResponseAccountsItem other) {
      name(other.getName());
      email(other.getEmail());
      phone(other.getPhone());
      description(other.getDescription());
      gstin(other.getGstin());
      gstStatus(other.getGstStatus());
      tdsEnabled(other.getTdsEnabled());
      tdsPercentage(other.getTdsPercentage());
      businessType(other.getBusinessType());
      id(other.getId());
      authId(other.getAuthId());
      apiId(other.getApiId());
      accountType(other.getAccountType());
      role(other.getRole());
      postpaid(other.getPostpaid());
      address(other.getAddress());
      city(other.getCity());
      state(other.getState());
      timezone(other.getTimezone());
      country(other.getCountry());
      zipCode(other.getZipCode());
      company(other.getCompany());
      billingMode(other.getBillingMode());
      autoRecharge(other.getAutoRecharge());
      cashCredits(other.getCashCredits());
      cpsLimit(other.getCpsLimit());
      concurrentCallsLimit(other.getConcurrentCallsLimit());
      baseCpsLimit(other.getBaseCpsLimit());
      baseConcurrentCallsLimit(other.getBaseConcurrentCallsLimit());
      purchasedCps(other.getPurchasedCps());
      purchasedConcurrentCalls(other.getPurchasedConcurrentCalls());
      isActive(other.getIsActive());
      isVerified(other.getIsVerified());
      isTrialAccount(other.getIsTrialAccount());
      enabled(other.getEnabled());
      kycStatus(other.getKycStatus());
      googleId(other.getGoogleId());
      referralCode(other.getReferralCode());
      referralDisabled(other.getReferralDisabled());
      customReferrerRewardAmount(other.getCustomReferrerRewardAmount());
      customRefereeRewardAmount(other.getCustomRefereeRewardAmount());
      createdAt(other.getCreatedAt());
      updatedAt(other.getUpdatedAt());
      lastLogin(other.getLastLogin());
      pricingTierId(other.getPricingTierId());
      pricingTier(other.getPricingTier());
      partnerId(other.getPartnerId());
      autoRechargeConfig(other.getAutoRechargeConfig());
      resourceUri(other.getResourceUri());
      authToken(other.getAuthToken());
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public EmailStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("email")
    public PhoneStage email(@NotNull String email) {
      this.email = Objects.requireNonNull(email, "email must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("phone")
    public TdsEnabledStage phone(@NotNull String phone) {
      this.phone = Objects.requireNonNull(phone, "phone must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("tds_enabled")
    public TdsPercentageStage tdsEnabled(boolean tdsEnabled) {
      this.tdsEnabled = tdsEnabled;
      return this;
    }

    @java.lang.Override
    @JsonSetter("tds_percentage")
    public BusinessTypeStage tdsPercentage(int tdsPercentage) {
      this.tdsPercentage = tdsPercentage;
      return this;
    }

    @java.lang.Override
    @JsonSetter("business_type")
    public IdStage businessType(@NotNull String businessType) {
      this.businessType = Objects.requireNonNull(businessType, "businessType must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public AuthIdStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("auth_id")
    public ApiIdStage authId(@NotNull String authId) {
      this.authId = Objects.requireNonNull(authId, "authId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("api_id")
    public AccountTypeStage apiId(@NotNull String apiId) {
      this.apiId = Objects.requireNonNull(apiId, "apiId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("account_type")
    public RoleStage accountType(@NotNull String accountType) {
      this.accountType = Objects.requireNonNull(accountType, "accountType must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("role")
    public PostpaidStage role(@NotNull String role) {
      this.role = Objects.requireNonNull(role, "role must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("postpaid")
    public CountryStage postpaid(boolean postpaid) {
      this.postpaid = postpaid;
      return this;
    }

    @java.lang.Override
    @JsonSetter("country")
    public CompanyStage country(@NotNull String country) {
      this.country = Objects.requireNonNull(country, "country must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("company")
    public BillingModeStage company(@NotNull String company) {
      this.company = Objects.requireNonNull(company, "company must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("billing_mode")
    public AutoRechargeStage billingMode(@NotNull String billingMode) {
      this.billingMode = Objects.requireNonNull(billingMode, "billingMode must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("auto_recharge")
    public CashCreditsStage autoRecharge(boolean autoRecharge) {
      this.autoRecharge = autoRecharge;
      return this;
    }

    @java.lang.Override
    @JsonSetter("cash_credits")
    public CpsLimitStage cashCredits(@NotNull String cashCredits) {
      this.cashCredits = Objects.requireNonNull(cashCredits, "cashCredits must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("cps_limit")
    public ConcurrentCallsLimitStage cpsLimit(int cpsLimit) {
      this.cpsLimit = cpsLimit;
      return this;
    }

    @java.lang.Override
    @JsonSetter("concurrent_calls_limit")
    public IsActiveStage concurrentCallsLimit(int concurrentCallsLimit) {
      this.concurrentCallsLimit = concurrentCallsLimit;
      return this;
    }

    @java.lang.Override
    @JsonSetter("is_active")
    public IsVerifiedStage isActive(boolean isActive) {
      this.isActive = isActive;
      return this;
    }

    @java.lang.Override
    @JsonSetter("is_verified")
    public IsTrialAccountStage isVerified(boolean isVerified) {
      this.isVerified = isVerified;
      return this;
    }

    @java.lang.Override
    @JsonSetter("is_trial_account")
    public EnabledStage isTrialAccount(boolean isTrialAccount) {
      this.isTrialAccount = isTrialAccount;
      return this;
    }

    @java.lang.Override
    @JsonSetter("enabled")
    public KycStatusStage enabled(boolean enabled) {
      this.enabled = enabled;
      return this;
    }

    @java.lang.Override
    @JsonSetter("kyc_status")
    public ReferralDisabledStage kycStatus(@NotNull String kycStatus) {
      this.kycStatus = Objects.requireNonNull(kycStatus, "kycStatus must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("referral_disabled")
    public CreatedAtStage referralDisabled(boolean referralDisabled) {
      this.referralDisabled = referralDisabled;
      return this;
    }

    @java.lang.Override
    @JsonSetter("created_at")
    public UpdatedAtStage createdAt(@NotNull String createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("updated_at")
    public PricingTierIdStage updatedAt(@NotNull String updatedAt) {
      this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("pricing_tier_id")
    public PricingTierStage pricingTierId(@NotNull String pricingTierId) {
      this.pricingTierId = Objects.requireNonNull(pricingTierId, "pricingTierId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("pricing_tier")
    public PartnerIdStage pricingTier(
        @NotNull ListCustomerAccountsResponseAccountsItemPricingTier pricingTier) {
      this.pricingTier = Objects.requireNonNull(pricingTier, "pricingTier must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("partner_id")
    public ResourceUriStage partnerId(@NotNull String partnerId) {
      this.partnerId = Objects.requireNonNull(partnerId, "partnerId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("resource_uri")
    public AuthTokenStage resourceUri(@NotNull String resourceUri) {
      this.resourceUri = Objects.requireNonNull(resourceUri, "resourceUri must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("auth_token")
    public _FinalStage authToken(@NotNull String authToken) {
      this.authToken = Objects.requireNonNull(authToken, "authToken must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage autoRechargeConfig(Nullable<Object> autoRechargeConfig) {
      if (autoRechargeConfig.isNull()) {
        this.autoRechargeConfig = null;
      }
      else if (autoRechargeConfig.isEmpty()) {
        this.autoRechargeConfig = Optional.empty();
      }
      else {
        this.autoRechargeConfig = Optional.of(autoRechargeConfig.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage autoRechargeConfig(Object autoRechargeConfig) {
      this.autoRechargeConfig = Optional.ofNullable(autoRechargeConfig);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "auto_recharge_config",
        nulls = Nulls.SKIP
    )
    public _FinalStage autoRechargeConfig(Optional<Object> autoRechargeConfig) {
      this.autoRechargeConfig = autoRechargeConfig;
      return this;
    }

    @java.lang.Override
    public _FinalStage lastLogin(Nullable<String> lastLogin) {
      if (lastLogin.isNull()) {
        this.lastLogin = null;
      }
      else if (lastLogin.isEmpty()) {
        this.lastLogin = Optional.empty();
      }
      else {
        this.lastLogin = Optional.of(lastLogin.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage lastLogin(String lastLogin) {
      this.lastLogin = Optional.ofNullable(lastLogin);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "last_login",
        nulls = Nulls.SKIP
    )
    public _FinalStage lastLogin(Optional<String> lastLogin) {
      this.lastLogin = lastLogin;
      return this;
    }

    @java.lang.Override
    public _FinalStage customRefereeRewardAmount(Nullable<Object> customRefereeRewardAmount) {
      if (customRefereeRewardAmount.isNull()) {
        this.customRefereeRewardAmount = null;
      }
      else if (customRefereeRewardAmount.isEmpty()) {
        this.customRefereeRewardAmount = Optional.empty();
      }
      else {
        this.customRefereeRewardAmount = Optional.of(customRefereeRewardAmount.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage customRefereeRewardAmount(Object customRefereeRewardAmount) {
      this.customRefereeRewardAmount = Optional.ofNullable(customRefereeRewardAmount);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "custom_referee_reward_amount",
        nulls = Nulls.SKIP
    )
    public _FinalStage customRefereeRewardAmount(Optional<Object> customRefereeRewardAmount) {
      this.customRefereeRewardAmount = customRefereeRewardAmount;
      return this;
    }

    @java.lang.Override
    public _FinalStage customReferrerRewardAmount(Nullable<Object> customReferrerRewardAmount) {
      if (customReferrerRewardAmount.isNull()) {
        this.customReferrerRewardAmount = null;
      }
      else if (customReferrerRewardAmount.isEmpty()) {
        this.customReferrerRewardAmount = Optional.empty();
      }
      else {
        this.customReferrerRewardAmount = Optional.of(customReferrerRewardAmount.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage customReferrerRewardAmount(Object customReferrerRewardAmount) {
      this.customReferrerRewardAmount = Optional.ofNullable(customReferrerRewardAmount);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "custom_referrer_reward_amount",
        nulls = Nulls.SKIP
    )
    public _FinalStage customReferrerRewardAmount(Optional<Object> customReferrerRewardAmount) {
      this.customReferrerRewardAmount = customReferrerRewardAmount;
      return this;
    }

    @java.lang.Override
    public _FinalStage referralCode(Nullable<String> referralCode) {
      if (referralCode.isNull()) {
        this.referralCode = null;
      }
      else if (referralCode.isEmpty()) {
        this.referralCode = Optional.empty();
      }
      else {
        this.referralCode = Optional.of(referralCode.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage referralCode(String referralCode) {
      this.referralCode = Optional.ofNullable(referralCode);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "referral_code",
        nulls = Nulls.SKIP
    )
    public _FinalStage referralCode(Optional<String> referralCode) {
      this.referralCode = referralCode;
      return this;
    }

    @java.lang.Override
    public _FinalStage googleId(Nullable<Object> googleId) {
      if (googleId.isNull()) {
        this.googleId = null;
      }
      else if (googleId.isEmpty()) {
        this.googleId = Optional.empty();
      }
      else {
        this.googleId = Optional.of(googleId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage googleId(Object googleId) {
      this.googleId = Optional.ofNullable(googleId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "google_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage googleId(Optional<Object> googleId) {
      this.googleId = googleId;
      return this;
    }

    @java.lang.Override
    public _FinalStage purchasedConcurrentCalls(Nullable<Object> purchasedConcurrentCalls) {
      if (purchasedConcurrentCalls.isNull()) {
        this.purchasedConcurrentCalls = null;
      }
      else if (purchasedConcurrentCalls.isEmpty()) {
        this.purchasedConcurrentCalls = Optional.empty();
      }
      else {
        this.purchasedConcurrentCalls = Optional.of(purchasedConcurrentCalls.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage purchasedConcurrentCalls(Object purchasedConcurrentCalls) {
      this.purchasedConcurrentCalls = Optional.ofNullable(purchasedConcurrentCalls);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "purchased_concurrent_calls",
        nulls = Nulls.SKIP
    )
    public _FinalStage purchasedConcurrentCalls(Optional<Object> purchasedConcurrentCalls) {
      this.purchasedConcurrentCalls = purchasedConcurrentCalls;
      return this;
    }

    @java.lang.Override
    public _FinalStage purchasedCps(Nullable<Object> purchasedCps) {
      if (purchasedCps.isNull()) {
        this.purchasedCps = null;
      }
      else if (purchasedCps.isEmpty()) {
        this.purchasedCps = Optional.empty();
      }
      else {
        this.purchasedCps = Optional.of(purchasedCps.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage purchasedCps(Object purchasedCps) {
      this.purchasedCps = Optional.ofNullable(purchasedCps);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "purchased_cps",
        nulls = Nulls.SKIP
    )
    public _FinalStage purchasedCps(Optional<Object> purchasedCps) {
      this.purchasedCps = purchasedCps;
      return this;
    }

    @java.lang.Override
    public _FinalStage baseConcurrentCallsLimit(Nullable<Object> baseConcurrentCallsLimit) {
      if (baseConcurrentCallsLimit.isNull()) {
        this.baseConcurrentCallsLimit = null;
      }
      else if (baseConcurrentCallsLimit.isEmpty()) {
        this.baseConcurrentCallsLimit = Optional.empty();
      }
      else {
        this.baseConcurrentCallsLimit = Optional.of(baseConcurrentCallsLimit.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage baseConcurrentCallsLimit(Object baseConcurrentCallsLimit) {
      this.baseConcurrentCallsLimit = Optional.ofNullable(baseConcurrentCallsLimit);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "base_concurrent_calls_limit",
        nulls = Nulls.SKIP
    )
    public _FinalStage baseConcurrentCallsLimit(Optional<Object> baseConcurrentCallsLimit) {
      this.baseConcurrentCallsLimit = baseConcurrentCallsLimit;
      return this;
    }

    @java.lang.Override
    public _FinalStage baseCpsLimit(Nullable<Object> baseCpsLimit) {
      if (baseCpsLimit.isNull()) {
        this.baseCpsLimit = null;
      }
      else if (baseCpsLimit.isEmpty()) {
        this.baseCpsLimit = Optional.empty();
      }
      else {
        this.baseCpsLimit = Optional.of(baseCpsLimit.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage baseCpsLimit(Object baseCpsLimit) {
      this.baseCpsLimit = Optional.ofNullable(baseCpsLimit);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "base_cps_limit",
        nulls = Nulls.SKIP
    )
    public _FinalStage baseCpsLimit(Optional<Object> baseCpsLimit) {
      this.baseCpsLimit = baseCpsLimit;
      return this;
    }

    @java.lang.Override
    public _FinalStage zipCode(Nullable<String> zipCode) {
      if (zipCode.isNull()) {
        this.zipCode = null;
      }
      else if (zipCode.isEmpty()) {
        this.zipCode = Optional.empty();
      }
      else {
        this.zipCode = Optional.of(zipCode.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage zipCode(String zipCode) {
      this.zipCode = Optional.ofNullable(zipCode);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "zip_code",
        nulls = Nulls.SKIP
    )
    public _FinalStage zipCode(Optional<String> zipCode) {
      this.zipCode = zipCode;
      return this;
    }

    @java.lang.Override
    public _FinalStage timezone(Nullable<String> timezone) {
      if (timezone.isNull()) {
        this.timezone = null;
      }
      else if (timezone.isEmpty()) {
        this.timezone = Optional.empty();
      }
      else {
        this.timezone = Optional.of(timezone.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage timezone(String timezone) {
      this.timezone = Optional.ofNullable(timezone);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "timezone",
        nulls = Nulls.SKIP
    )
    public _FinalStage timezone(Optional<String> timezone) {
      this.timezone = timezone;
      return this;
    }

    @java.lang.Override
    public _FinalStage state(Nullable<String> state) {
      if (state.isNull()) {
        this.state = null;
      }
      else if (state.isEmpty()) {
        this.state = Optional.empty();
      }
      else {
        this.state = Optional.of(state.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage state(String state) {
      this.state = Optional.ofNullable(state);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "state",
        nulls = Nulls.SKIP
    )
    public _FinalStage state(Optional<String> state) {
      this.state = state;
      return this;
    }

    @java.lang.Override
    public _FinalStage city(Nullable<String> city) {
      if (city.isNull()) {
        this.city = null;
      }
      else if (city.isEmpty()) {
        this.city = Optional.empty();
      }
      else {
        this.city = Optional.of(city.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage city(String city) {
      this.city = Optional.ofNullable(city);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "city",
        nulls = Nulls.SKIP
    )
    public _FinalStage city(Optional<String> city) {
      this.city = city;
      return this;
    }

    @java.lang.Override
    public _FinalStage address(Nullable<String> address) {
      if (address.isNull()) {
        this.address = null;
      }
      else if (address.isEmpty()) {
        this.address = Optional.empty();
      }
      else {
        this.address = Optional.of(address.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage address(String address) {
      this.address = Optional.ofNullable(address);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "address",
        nulls = Nulls.SKIP
    )
    public _FinalStage address(Optional<String> address) {
      this.address = address;
      return this;
    }

    @java.lang.Override
    public _FinalStage gstStatus(Nullable<String> gstStatus) {
      if (gstStatus.isNull()) {
        this.gstStatus = null;
      }
      else if (gstStatus.isEmpty()) {
        this.gstStatus = Optional.empty();
      }
      else {
        this.gstStatus = Optional.of(gstStatus.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage gstStatus(String gstStatus) {
      this.gstStatus = Optional.ofNullable(gstStatus);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "gst_status",
        nulls = Nulls.SKIP
    )
    public _FinalStage gstStatus(Optional<String> gstStatus) {
      this.gstStatus = gstStatus;
      return this;
    }

    @java.lang.Override
    public _FinalStage gstin(Nullable<String> gstin) {
      if (gstin.isNull()) {
        this.gstin = null;
      }
      else if (gstin.isEmpty()) {
        this.gstin = Optional.empty();
      }
      else {
        this.gstin = Optional.of(gstin.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage gstin(String gstin) {
      this.gstin = Optional.ofNullable(gstin);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "gstin",
        nulls = Nulls.SKIP
    )
    public _FinalStage gstin(Optional<String> gstin) {
      this.gstin = gstin;
      return this;
    }

    @java.lang.Override
    public _FinalStage description(Nullable<String> description) {
      if (description.isNull()) {
        this.description = null;
      }
      else if (description.isEmpty()) {
        this.description = Optional.empty();
      }
      else {
        this.description = Optional.of(description.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    @java.lang.Override
    public ListCustomerAccountsResponseAccountsItem build() {
      return new ListCustomerAccountsResponseAccountsItem(name, email, phone, description, gstin, gstStatus, tdsEnabled, tdsPercentage, businessType, id, authId, apiId, accountType, role, postpaid, address, city, state, timezone, country, zipCode, company, billingMode, autoRecharge, cashCredits, cpsLimit, concurrentCallsLimit, baseCpsLimit, baseConcurrentCallsLimit, purchasedCps, purchasedConcurrentCalls, isActive, isVerified, isTrialAccount, enabled, kycStatus, googleId, referralCode, referralDisabled, customReferrerRewardAmount, customRefereeRewardAmount, createdAt, updatedAt, lastLogin, pricingTierId, pricingTier, partnerId, autoRechargeConfig, resourceUri, authToken, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
