/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.partnerapi.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListKycSessionsResponseSessionsItemReminderScheduleItem.Builder.class
)
public final class ListKycSessionsResponseSessionsItemReminderScheduleItem {
  private final int value;

  private final String trigger;

  private final Map<String, Object> additionalProperties;

  private ListKycSessionsResponseSessionsItemReminderScheduleItem(int value, String trigger,
      Map<String, Object> additionalProperties) {
    this.value = value;
    this.trigger = trigger;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("value")
  public int getValue() {
    return value;
  }

  @JsonProperty("trigger")
  public String getTrigger() {
    return trigger;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListKycSessionsResponseSessionsItemReminderScheduleItem && equalTo((ListKycSessionsResponseSessionsItemReminderScheduleItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListKycSessionsResponseSessionsItemReminderScheduleItem other) {
    return value == other.value && trigger.equals(other.trigger);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.value, this.trigger);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ValueStage builder() {
    return new Builder();
  }

  public interface ValueStage {
    TriggerStage value(int value);

    Builder from(ListKycSessionsResponseSessionsItemReminderScheduleItem other);
  }

  public interface TriggerStage {
    _FinalStage trigger(@NotNull String trigger);
  }

  public interface _FinalStage {
    ListKycSessionsResponseSessionsItemReminderScheduleItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ValueStage, TriggerStage, _FinalStage {
    private int value;

    private String trigger;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ListKycSessionsResponseSessionsItemReminderScheduleItem other) {
      value(other.getValue());
      trigger(other.getTrigger());
      return this;
    }

    @java.lang.Override
    @JsonSetter("value")
    public TriggerStage value(int value) {
      this.value = value;
      return this;
    }

    @java.lang.Override
    @JsonSetter("trigger")
    public _FinalStage trigger(@NotNull String trigger) {
      this.trigger = Objects.requireNonNull(trigger, "trigger must not be null");
      return this;
    }

    @java.lang.Override
    public ListKycSessionsResponseSessionsItemReminderScheduleItem build() {
      return new ListKycSessionsResponseSessionsItemReminderScheduleItem(value, trigger, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
