/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.conferences;

import core.ClientOptions;
import core.RequestOptions;
import java.lang.Object;
import java.lang.String;
import java.lang.Void;
import java.util.concurrent.CompletableFuture;
import resources.conferences.requests.DeleteAllConferencesRequest;
import resources.conferences.requests.DeleteConferenceRequest;
import resources.conferences.requests.GetConferenceRequest;
import resources.conferences.requests.ListConferencesRequest;
import resources.conferences.types.ListConferencesResponse;

public class AsyncConferencesClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawConferencesClient rawClient;

  public AsyncConferencesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawConferencesClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawConferencesClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Retrieve all active conference rooms on the account.
   */
  public CompletableFuture<ListConferencesResponse> listConferences(String authId) {
    return this.rawClient.listConferences(authId).thenApply(response -> response.body());
  }

  /**
   * Retrieve all active conference rooms on the account.
   */
  public CompletableFuture<ListConferencesResponse> listConferences(String authId,
      RequestOptions requestOptions) {
    return this.rawClient.listConferences(authId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieve all active conference rooms on the account.
   */
  public CompletableFuture<ListConferencesResponse> listConferences(String authId,
      ListConferencesRequest request) {
    return this.rawClient.listConferences(authId, request).thenApply(response -> response.body());
  }

  /**
   * Retrieve all active conference rooms on the account.
   */
  public CompletableFuture<ListConferencesResponse> listConferences(String authId,
      ListConferencesRequest request, RequestOptions requestOptions) {
    return this.rawClient.listConferences(authId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Terminate all active conference rooms.
   */
  public CompletableFuture<Void> deleteAllConferences(String authId) {
    return this.rawClient.deleteAllConferences(authId).thenApply(response -> response.body());
  }

  /**
   * Terminate all active conference rooms.
   */
  public CompletableFuture<Void> deleteAllConferences(String authId,
      RequestOptions requestOptions) {
    return this.rawClient.deleteAllConferences(authId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Terminate all active conference rooms.
   */
  public CompletableFuture<Void> deleteAllConferences(String authId,
      DeleteAllConferencesRequest request) {
    return this.rawClient.deleteAllConferences(authId, request).thenApply(response -> response.body());
  }

  /**
   * Terminate all active conference rooms.
   */
  public CompletableFuture<Void> deleteAllConferences(String authId,
      DeleteAllConferencesRequest request, RequestOptions requestOptions) {
    return this.rawClient.deleteAllConferences(authId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get details and member list of a specific conference room.
   */
  public CompletableFuture<Object> getConference(String authId, String conferenceName) {
    return this.rawClient.getConference(authId, conferenceName).thenApply(response -> response.body());
  }

  /**
   * Get details and member list of a specific conference room.
   */
  public CompletableFuture<Object> getConference(String authId, String conferenceName,
      RequestOptions requestOptions) {
    return this.rawClient.getConference(authId, conferenceName, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get details and member list of a specific conference room.
   */
  public CompletableFuture<Object> getConference(String authId, String conferenceName,
      GetConferenceRequest request) {
    return this.rawClient.getConference(authId, conferenceName, request).thenApply(response -> response.body());
  }

  /**
   * Get details and member list of a specific conference room.
   */
  public CompletableFuture<Object> getConference(String authId, String conferenceName,
      GetConferenceRequest request, RequestOptions requestOptions) {
    return this.rawClient.getConference(authId, conferenceName, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Terminate a specific conference room and disconnect all members.
   */
  public CompletableFuture<Void> deleteConference(String authId, String conferenceName) {
    return this.rawClient.deleteConference(authId, conferenceName).thenApply(response -> response.body());
  }

  /**
   * Terminate a specific conference room and disconnect all members.
   */
  public CompletableFuture<Void> deleteConference(String authId, String conferenceName,
      RequestOptions requestOptions) {
    return this.rawClient.deleteConference(authId, conferenceName, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Terminate a specific conference room and disconnect all members.
   */
  public CompletableFuture<Void> deleteConference(String authId, String conferenceName,
      DeleteConferenceRequest request) {
    return this.rawClient.deleteConference(authId, conferenceName, request).thenApply(response -> response.body());
  }

  /**
   * Terminate a specific conference room and disconnect all members.
   */
  public CompletableFuture<Void> deleteConference(String authId, String conferenceName,
      DeleteConferenceRequest request, RequestOptions requestOptions) {
    return this.rawClient.deleteConference(authId, conferenceName, request, requestOptions).thenApply(response -> response.body());
  }
}
