/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.conferences;

import com.fasterxml.jackson.core.JsonProcessingException;
import core.ClientOptions;
import core.ObjectMappers;
import core.RequestOptions;
import core.VobizApiApiException;
import core.VobizApiException;
import core.VobizApiHttpResponse;
import errors.NotFoundError;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import java.lang.Void;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.conferences.requests.DeleteAllConferencesRequest;
import resources.conferences.requests.DeleteConferenceRequest;
import resources.conferences.requests.GetConferenceRequest;
import resources.conferences.requests.ListConferencesRequest;
import resources.conferences.types.GetConferenceResponse;
import resources.conferences.types.ListConferencesResponse;

public class RawConferencesClient {
  protected final ClientOptions clientOptions;

  public RawConferencesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Retrieve conference room names reported by the API. An empty array is inconclusive and can occur while conferences are active. Maintain your own room registry for authoritative discovery, billing, cleanup, and destructive workflows.
   */
  public VobizApiHttpResponse<ListConferencesResponse> listConferences(String authId) {
    return listConferences(authId,ListConferencesRequest.builder().build());
  }

  /**
   * Retrieve conference room names reported by the API. An empty array is inconclusive and can occur while conferences are active. Maintain your own room registry for authoritative discovery, billing, cleanup, and destructive workflows.
   */
  public VobizApiHttpResponse<ListConferencesResponse> listConferences(String authId,
      RequestOptions requestOptions) {
    return listConferences(authId,ListConferencesRequest.builder().build(),requestOptions);
  }

  /**
   * Retrieve conference room names reported by the API. An empty array is inconclusive and can occur while conferences are active. Maintain your own room registry for authoritative discovery, billing, cleanup, and destructive workflows.
   */
  public VobizApiHttpResponse<ListConferencesResponse> listConferences(String authId,
      ListConferencesRequest request) {
    return listConferences(authId,request,null);
  }

  /**
   * Retrieve conference room names reported by the API. An empty array is inconclusive and can occur while conferences are active. Maintain your own room registry for authoritative discovery, billing, cleanup, and destructive workflows.
   */
  public VobizApiHttpResponse<ListConferencesResponse> listConferences(String authId,
      ListConferencesRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api/v1/Account")
      .addPathSegment(authId)
      .addPathSegments("Conference");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new VobizApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListConferencesResponse.class), response);
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new VobizApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Terminate all active conference rooms.
     */
    public VobizApiHttpResponse<Void> deleteAllConferences(String authId) {
      return deleteAllConferences(authId,DeleteAllConferencesRequest.builder().build());
    }

    /**
     * Terminate all active conference rooms.
     */
    public VobizApiHttpResponse<Void> deleteAllConferences(String authId,
        RequestOptions requestOptions) {
      return deleteAllConferences(authId,DeleteAllConferencesRequest.builder().build(),requestOptions);
    }

    /**
     * Terminate all active conference rooms.
     */
    public VobizApiHttpResponse<Void> deleteAllConferences(String authId,
        DeleteAllConferencesRequest request) {
      return deleteAllConferences(authId,request,null);
    }

    /**
     * Terminate all active conference rooms.
     */
    public VobizApiHttpResponse<Void> deleteAllConferences(String authId,
        DeleteAllConferencesRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("api/v1/Account")
        .addPathSegment(authId)
        .addPathSegments("Conference");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("DELETE", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)));
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          if (response.isSuccessful()) {
            return new VobizApiHttpResponse<>(null, response);
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new VobizApiException("Network error executing HTTP request", e);
        }
      }

      /**
       * Retrieve a specific conference room. A live conference can currently return a 200 response with an error payload instead of conference details.
       */
      public VobizApiHttpResponse<GetConferenceResponse> getConference(String authId,
          String conferenceName) {
        return getConference(authId,conferenceName,GetConferenceRequest.builder().build());
      }

      /**
       * Retrieve a specific conference room. A live conference can currently return a 200 response with an error payload instead of conference details.
       */
      public VobizApiHttpResponse<GetConferenceResponse> getConference(String authId,
          String conferenceName, RequestOptions requestOptions) {
        return getConference(authId,conferenceName,GetConferenceRequest.builder().build(),requestOptions);
      }

      /**
       * Retrieve a specific conference room. A live conference can currently return a 200 response with an error payload instead of conference details.
       */
      public VobizApiHttpResponse<GetConferenceResponse> getConference(String authId,
          String conferenceName, GetConferenceRequest request) {
        return getConference(authId,conferenceName,request,null);
      }

      /**
       * Retrieve a specific conference room. A live conference can currently return a 200 response with an error payload instead of conference details.
       */
      public VobizApiHttpResponse<GetConferenceResponse> getConference(String authId,
          String conferenceName, GetConferenceRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("api/v1/Account")
          .addPathSegment(authId)
          .addPathSegments("Conference")
          .addPathSegment(conferenceName);if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              return new VobizApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetConferenceResponse.class), response);
            }
            try {
              if (response.code() == 404) {
                throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (IOException e) {
            throw new VobizApiException("Network error executing HTTP request", e);
          }
        }

        /**
         * Terminate a specific conference room and disconnect all members.
         */
        public VobizApiHttpResponse<Void> deleteConference(String authId, String conferenceName) {
          return deleteConference(authId,conferenceName,DeleteConferenceRequest.builder().build());
        }

        /**
         * Terminate a specific conference room and disconnect all members.
         */
        public VobizApiHttpResponse<Void> deleteConference(String authId, String conferenceName,
            RequestOptions requestOptions) {
          return deleteConference(authId,conferenceName,DeleteConferenceRequest.builder().build(),requestOptions);
        }

        /**
         * Terminate a specific conference room and disconnect all members.
         */
        public VobizApiHttpResponse<Void> deleteConference(String authId, String conferenceName,
            DeleteConferenceRequest request) {
          return deleteConference(authId,conferenceName,request,null);
        }

        /**
         * Terminate a specific conference room and disconnect all members.
         */
        public VobizApiHttpResponse<Void> deleteConference(String authId, String conferenceName,
            DeleteConferenceRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("api/v1/Account")
            .addPathSegment(authId)
            .addPathSegments("Conference")
            .addPathSegment(conferenceName);if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("DELETE", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)));
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              if (response.isSuccessful()) {
                return new VobizApiHttpResponse<>(null, response);
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (IOException e) {
              throw new VobizApiException("Network error executing HTTP request", e);
            }
          }
        }
