/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.phonenumbers.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class CancelNumberReleaseResponseStatus {
  public static final CancelNumberReleaseResponseStatus ACTIVE = new CancelNumberReleaseResponseStatus(Value.ACTIVE, "active");

  private final Value value;

  private final String string;

  CancelNumberReleaseResponseStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof CancelNumberReleaseResponseStatus && this.string.equals(((CancelNumberReleaseResponseStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case ACTIVE:
        return visitor.visitActive();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static CancelNumberReleaseResponseStatus valueOf(String value) {
    switch (value) {
      case "active":
        return ACTIVE;
      default:
        return new CancelNumberReleaseResponseStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    ACTIVE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitActive();

    T visitUnknown(String unknownType);
  }
}
