/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.phonenumbers.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListInventoryNumbersResponse.Builder.class
)
public final class ListInventoryNumbersResponse {
  private final List<ListInventoryNumbersResponseItemsItem> items;

  private final int page;

  private final int perPage;

  private final int total;

  private final Map<String, Object> additionalProperties;

  private ListInventoryNumbersResponse(List<ListInventoryNumbersResponseItemsItem> items, int page,
      int perPage, int total, Map<String, Object> additionalProperties) {
    this.items = items;
    this.page = page;
    this.perPage = perPage;
    this.total = total;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("items")
  public List<ListInventoryNumbersResponseItemsItem> getItems() {
    return items;
  }

  @JsonProperty("page")
  public int getPage() {
    return page;
  }

  @JsonProperty("per_page")
  public int getPerPage() {
    return perPage;
  }

  @JsonProperty("total")
  public int getTotal() {
    return total;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListInventoryNumbersResponse && equalTo((ListInventoryNumbersResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListInventoryNumbersResponse other) {
    return items.equals(other.items) && page == other.page && perPage == other.perPage && total == other.total;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.items, this.page, this.perPage, this.total);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static PageStage builder() {
    return new Builder();
  }

  public interface PageStage {
    PerPageStage page(int page);

    Builder from(ListInventoryNumbersResponse other);
  }

  public interface PerPageStage {
    TotalStage perPage(int perPage);
  }

  public interface TotalStage {
    _FinalStage total(int total);
  }

  public interface _FinalStage {
    ListInventoryNumbersResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage items(List<ListInventoryNumbersResponseItemsItem> items);

    _FinalStage addItems(ListInventoryNumbersResponseItemsItem items);

    _FinalStage addAllItems(List<ListInventoryNumbersResponseItemsItem> items);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements PageStage, PerPageStage, TotalStage, _FinalStage {
    private int page;

    private int perPage;

    private int total;

    private List<ListInventoryNumbersResponseItemsItem> items = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ListInventoryNumbersResponse other) {
      items(other.getItems());
      page(other.getPage());
      perPage(other.getPerPage());
      total(other.getTotal());
      return this;
    }

    @java.lang.Override
    @JsonSetter("page")
    public PerPageStage page(int page) {
      this.page = page;
      return this;
    }

    @java.lang.Override
    @JsonSetter("per_page")
    public TotalStage perPage(int perPage) {
      this.perPage = perPage;
      return this;
    }

    @java.lang.Override
    @JsonSetter("total")
    public _FinalStage total(int total) {
      this.total = total;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllItems(List<ListInventoryNumbersResponseItemsItem> items) {
      if (items != null) {
        this.items.addAll(items);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addItems(ListInventoryNumbersResponseItemsItem items) {
      this.items.add(items);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "items",
        nulls = Nulls.SKIP
    )
    public _FinalStage items(List<ListInventoryNumbersResponseItemsItem> items) {
      this.items.clear();
      if (items != null) {
        this.items.addAll(items);
      }
      return this;
    }

    @java.lang.Override
    public ListInventoryNumbersResponse build() {
      return new ListInventoryNumbersResponse(items, page, perPage, total, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
