/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.bulkoperations;

import core.ClientOptions;
import core.RequestOptions;
import java.lang.String;
import resources.bulkoperations.requests.BulkExportRecordingsRequest;
import resources.bulkoperations.types.BulkExportRecordingsResponse;

public class BulkOperationsClient {
  protected final ClientOptions clientOptions;

  private final RawBulkOperationsClient rawClient;

  public BulkOperationsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawBulkOperationsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawBulkOperationsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Queue a bulk export of the recordings matching your filter criteria. The request is
   * validated and accepted for background processing, and the resulting archive is emailed
   * as a download link to every address in <code>recipient.customer_account</code>. The archive is
   * typically available within 15-60 minutes depending on volume.
   * <p>Results are delivered by email only; the export runs to completion in the background
   * after the <code>202</code> response.</p>
   * <p>One export runs at a time per account. While an export is in progress, further requests
   * return <code>403</code>.</p>
   * <p>Filter rules:</p>
   * <ul>
   * <li>Use either <code>from</code>/<code>to</code> or the <code>recording_storage_duration*</code> filters, not both.</li>
   * <li>Use one of <code>__gt</code> or <code>__gte</code>, and one of <code>__lt</code> or <code>__lte</code>.</li>
   * <li>When using range filters (<code>__gte</code>/<code>__lte</code>), provide both.</li>
   * <li>Maximum date range is 1 year (366 days); maximum storage duration range is 30 days.</li>
   * <li>The additional filters (<code>from_number</code>, <code>to_number</code>, <code>call_uuid</code>, <code>conference_name</code>,
   * <code>recording_format</code>, <code>recording_id</code>) apply when the range is 30 days or less.</li>
   * </ul>
   */
  public BulkExportRecordingsResponse bulkExportRecordings(String authId,
      BulkExportRecordingsRequest request) {
    return this.rawClient.bulkExportRecordings(authId, request).body();
  }

  /**
   * Queue a bulk export of the recordings matching your filter criteria. The request is
   * validated and accepted for background processing, and the resulting archive is emailed
   * as a download link to every address in <code>recipient.customer_account</code>. The archive is
   * typically available within 15-60 minutes depending on volume.
   * <p>Results are delivered by email only; the export runs to completion in the background
   * after the <code>202</code> response.</p>
   * <p>One export runs at a time per account. While an export is in progress, further requests
   * return <code>403</code>.</p>
   * <p>Filter rules:</p>
   * <ul>
   * <li>Use either <code>from</code>/<code>to</code> or the <code>recording_storage_duration*</code> filters, not both.</li>
   * <li>Use one of <code>__gt</code> or <code>__gte</code>, and one of <code>__lt</code> or <code>__lte</code>.</li>
   * <li>When using range filters (<code>__gte</code>/<code>__lte</code>), provide both.</li>
   * <li>Maximum date range is 1 year (366 days); maximum storage duration range is 30 days.</li>
   * <li>The additional filters (<code>from_number</code>, <code>to_number</code>, <code>call_uuid</code>, <code>conference_name</code>,
   * <code>recording_format</code>, <code>recording_id</code>) apply when the range is 30 days or less.</li>
   * </ul>
   */
  public BulkExportRecordingsResponse bulkExportRecordings(String authId,
      BulkExportRecordingsRequest request, RequestOptions requestOptions) {
    return this.rawClient.bulkExportRecordings(authId, request, requestOptions).body();
  }
}
