/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.recordings;

import core.ClientOptions;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import core.VobizApiApiException;
import core.VobizApiException;
import core.VobizApiHttpResponse;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import java.lang.Void;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.recordings.requests.DeleteRecordingRequest;
import resources.recordings.requests.GetRecordingRequest;
import resources.recordings.requests.ListRecordingsRequest;
import resources.recordings.types.GetRecordingResponse;
import resources.recordings.types.ListRecordingsResponse;

public class RawRecordingsClient {
  protected final ClientOptions clientOptions;

  public RawRecordingsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Retrieve all call recordings on the account.
   */
  public VobizApiHttpResponse<ListRecordingsResponse> listRecordings(String authId) {
    return listRecordings(authId,ListRecordingsRequest.builder().build());
  }

  /**
   * Retrieve all call recordings on the account.
   */
  public VobizApiHttpResponse<ListRecordingsResponse> listRecordings(String authId,
      RequestOptions requestOptions) {
    return listRecordings(authId,ListRecordingsRequest.builder().build(),requestOptions);
  }

  /**
   * Retrieve all call recordings on the account.
   */
  public VobizApiHttpResponse<ListRecordingsResponse> listRecordings(String authId,
      ListRecordingsRequest request) {
    return listRecordings(authId,request,null);
  }

  /**
   * Retrieve all call recordings on the account.
   */
  public VobizApiHttpResponse<ListRecordingsResponse> listRecordings(String authId,
      ListRecordingsRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api/v1/Account")
      .addPathSegment(authId)
      .addPathSegments("Recording");if (request.getLimit().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
      }
      if (request.getOffset().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "offset", request.getOffset().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new VobizApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListRecordingsResponse.class), response);
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new VobizApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Get details and download URL for a specific recording.
     */
    public VobizApiHttpResponse<GetRecordingResponse> getRecording(String authId,
        String recordingId) {
      return getRecording(authId,recordingId,GetRecordingRequest.builder().build());
    }

    /**
     * Get details and download URL for a specific recording.
     */
    public VobizApiHttpResponse<GetRecordingResponse> getRecording(String authId,
        String recordingId, RequestOptions requestOptions) {
      return getRecording(authId,recordingId,GetRecordingRequest.builder().build(),requestOptions);
    }

    /**
     * Get details and download URL for a specific recording.
     */
    public VobizApiHttpResponse<GetRecordingResponse> getRecording(String authId,
        String recordingId, GetRecordingRequest request) {
      return getRecording(authId,recordingId,request,null);
    }

    /**
     * Get details and download URL for a specific recording.
     */
    public VobizApiHttpResponse<GetRecordingResponse> getRecording(String authId,
        String recordingId, GetRecordingRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("api/v1/Account")
        .addPathSegment(authId)
        .addPathSegments("Recording")
        .addPathSegment(recordingId);if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new VobizApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetRecordingResponse.class), response);
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new VobizApiException("Network error executing HTTP request", e);
        }
      }

      /**
       * Permanently delete a recording from the account.
       */
      public VobizApiHttpResponse<Void> deleteRecording(String authId, String recordingId) {
        return deleteRecording(authId,recordingId,DeleteRecordingRequest.builder().build());
      }

      /**
       * Permanently delete a recording from the account.
       */
      public VobizApiHttpResponse<Void> deleteRecording(String authId, String recordingId,
          RequestOptions requestOptions) {
        return deleteRecording(authId,recordingId,DeleteRecordingRequest.builder().build(),requestOptions);
      }

      /**
       * Permanently delete a recording from the account.
       */
      public VobizApiHttpResponse<Void> deleteRecording(String authId, String recordingId,
          DeleteRecordingRequest request) {
        return deleteRecording(authId,recordingId,request,null);
      }

      /**
       * Permanently delete a recording from the account.
       */
      public VobizApiHttpResponse<Void> deleteRecording(String authId, String recordingId,
          DeleteRecordingRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("api/v1/Account")
          .addPathSegment(authId)
          .addPathSegments("Recording")
          .addPathSegment(recordingId);if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("DELETE", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)));
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
              return new VobizApiHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (IOException e) {
            throw new VobizApiException("Network error executing HTTP request", e);
          }
        }
      }
