/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.conferencerecording;

import com.fasterxml.jackson.core.JsonProcessingException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.RequestOptions;
import core.VobizApiApiException;
import core.VobizApiException;
import core.VobizApiHttpResponse;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import java.lang.Void;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.conferencerecording.requests.StartConferenceRecordingRequest;
import resources.conferencerecording.requests.StopConferenceRecordingRequest;

public class RawConferenceRecordingClient {
  protected final ClientOptions clientOptions;

  public RawConferenceRecordingClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Queue recording for all audio in a conference room. The response does not include a recording ID or download URL.
   */
  public VobizApiHttpResponse<Object> startConferenceRecording(String authId,
      String conferenceName) {
    return startConferenceRecording(authId,conferenceName,StartConferenceRecordingRequest.builder().build());
  }

  /**
   * Queue recording for all audio in a conference room. The response does not include a recording ID or download URL.
   */
  public VobizApiHttpResponse<Object> startConferenceRecording(String authId, String conferenceName,
      RequestOptions requestOptions) {
    return startConferenceRecording(authId,conferenceName,StartConferenceRecordingRequest.builder().build(),requestOptions);
  }

  /**
   * Queue recording for all audio in a conference room. The response does not include a recording ID or download URL.
   */
  public VobizApiHttpResponse<Object> startConferenceRecording(String authId, String conferenceName,
      StartConferenceRecordingRequest request) {
    return startConferenceRecording(authId,conferenceName,request,null);
  }

  /**
   * Queue recording for all audio in a conference room. The response does not include a recording ID or download URL.
   */
  public VobizApiHttpResponse<Object> startConferenceRecording(String authId, String conferenceName,
      StartConferenceRecordingRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api/v1/Account")
      .addPathSegment(authId)
      .addPathSegments("Conference")
      .addPathSegment(conferenceName)
      .addPathSegments("Record");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
      }
      catch(JsonProcessingException e) {
        throw new VobizApiException("Failed to serialize request", e);
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new VobizApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new VobizApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Stop recording a conference room.
     */
    public VobizApiHttpResponse<Void> stopConferenceRecording(String authId,
        String conferenceName) {
      return stopConferenceRecording(authId,conferenceName,StopConferenceRecordingRequest.builder().build());
    }

    /**
     * Stop recording a conference room.
     */
    public VobizApiHttpResponse<Void> stopConferenceRecording(String authId, String conferenceName,
        RequestOptions requestOptions) {
      return stopConferenceRecording(authId,conferenceName,StopConferenceRecordingRequest.builder().build(),requestOptions);
    }

    /**
     * Stop recording a conference room.
     */
    public VobizApiHttpResponse<Void> stopConferenceRecording(String authId, String conferenceName,
        StopConferenceRecordingRequest request) {
      return stopConferenceRecording(authId,conferenceName,request,null);
    }

    /**
     * Stop recording a conference room.
     */
    public VobizApiHttpResponse<Void> stopConferenceRecording(String authId, String conferenceName,
        StopConferenceRecordingRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("api/v1/Account")
        .addPathSegment(authId)
        .addPathSegments("Conference")
        .addPathSegment(conferenceName)
        .addPathSegments("Record");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("DELETE", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)));
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          if (response.isSuccessful()) {
            return new VobizApiHttpResponse<>(null, response);
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new VobizApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new VobizApiException("Network error executing HTTP request", e);
        }
      }
    }
