/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.bulkoperations.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import resources.bulkoperations.types.BulkExportRecordingsRequestRecipient;
import resources.bulkoperations.types.BulkExportRecordingsRequestRecordingFormat;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BulkExportRecordingsRequest.Builder.class
)
public final class BulkExportRecordingsRequest {
  private final BulkExportRecordingsRequestRecipient recipient;

  private final Optional<String> from;

  private final Optional<String> to;

  private final Optional<String> recordingStorageDuration;

  private final Optional<String> recordingStorageDurationGte;

  private final Optional<String> recordingStorageDurationGt;

  private final Optional<String> recordingStorageDurationLte;

  private final Optional<String> recordingStorageDurationLt;

  private final Optional<String> fromNumber;

  private final Optional<String> toNumber;

  private final Optional<String> callUuid;

  private final Optional<String> conferenceName;

  private final Optional<BulkExportRecordingsRequestRecordingFormat> recordingFormat;

  private final Optional<String> recordingId;

  private final Map<String, Object> additionalProperties;

  private BulkExportRecordingsRequest(BulkExportRecordingsRequestRecipient recipient,
      Optional<String> from, Optional<String> to, Optional<String> recordingStorageDuration,
      Optional<String> recordingStorageDurationGte, Optional<String> recordingStorageDurationGt,
      Optional<String> recordingStorageDurationLte, Optional<String> recordingStorageDurationLt,
      Optional<String> fromNumber, Optional<String> toNumber, Optional<String> callUuid,
      Optional<String> conferenceName,
      Optional<BulkExportRecordingsRequestRecordingFormat> recordingFormat,
      Optional<String> recordingId, Map<String, Object> additionalProperties) {
    this.recipient = recipient;
    this.from = from;
    this.to = to;
    this.recordingStorageDuration = recordingStorageDuration;
    this.recordingStorageDurationGte = recordingStorageDurationGte;
    this.recordingStorageDurationGt = recordingStorageDurationGt;
    this.recordingStorageDurationLte = recordingStorageDurationLte;
    this.recordingStorageDurationLt = recordingStorageDurationLt;
    this.fromNumber = fromNumber;
    this.toNumber = toNumber;
    this.callUuid = callUuid;
    this.conferenceName = conferenceName;
    this.recordingFormat = recordingFormat;
    this.recordingId = recordingId;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Email delivery targets for the export archive.
   */
  @JsonProperty("recipient")
  public BulkExportRecordingsRequestRecipient getRecipient() {
    return recipient;
  }

  /**
   * @return Start date for the export. Format: YYYY-MM-DD HH:MM:SS. Defaults to 7 days ago.
   */
  @JsonProperty("from")
  public Optional<String> getFrom() {
    return from;
  }

  /**
   * @return End date for the export. Format: YYYY-MM-DD HH:MM:SS. Defaults to the current time.
   */
  @JsonProperty("to")
  public Optional<String> getTo() {
    return to;
  }

  /**
   * @return Export recordings exactly N days old. <code>&quot;7&quot;</code> exports recordings from exactly 7 days ago.
   */
  @JsonProperty("recording_storage_duration")
  public Optional<String> getRecordingStorageDuration() {
    return recordingStorageDuration;
  }

  /**
   * @return Export recordings N days old or older. <code>&quot;7&quot;</code> exports recordings 7 days old and older.
   */
  @JsonProperty("recording_storage_duration__gte")
  public Optional<String> getRecordingStorageDurationGte() {
    return recordingStorageDurationGte;
  }

  /**
   * @return Export recordings older than N days. <code>&quot;7&quot;</code> exports recordings 8 days old and older.
   */
  @JsonProperty("recording_storage_duration__gt")
  public Optional<String> getRecordingStorageDurationGt() {
    return recordingStorageDurationGt;
  }

  /**
   * @return Export recordings N days old or newer. <code>&quot;30&quot;</code> exports recordings 0-30 days old.
   */
  @JsonProperty("recording_storage_duration__lte")
  public Optional<String> getRecordingStorageDurationLte() {
    return recordingStorageDurationLte;
  }

  /**
   * @return Export recordings newer than N days. <code>&quot;30&quot;</code> exports recordings 0-29 days old.
   */
  @JsonProperty("recording_storage_duration__lt")
  public Optional<String> getRecordingStorageDurationLt() {
    return recordingStorageDurationLt;
  }

  /**
   * @return Filter by caller phone number. Applies when the range is 30 days or less.
   */
  @JsonProperty("from_number")
  public Optional<String> getFromNumber() {
    return fromNumber;
  }

  /**
   * @return Filter by destination phone number. Applies when the range is 30 days or less.
   */
  @JsonProperty("to_number")
  public Optional<String> getToNumber() {
    return toNumber;
  }

  /**
   * @return Filter by call UUID. Also use this field for a conference_uuid or mpc_uuid. Applies when the range is 30 days or less.
   */
  @JsonProperty("call_uuid")
  public Optional<String> getCallUuid() {
    return callUuid;
  }

  /**
   * @return Filter by conference name. Also use this field for an mpc_name. Applies when the range is 30 days or less.
   */
  @JsonProperty("conference_name")
  public Optional<String> getConferenceName() {
    return conferenceName;
  }

  /**
   * @return Filter by recording format. Applies when the range is 30 days or less.
   */
  @JsonProperty("recording_format")
  public Optional<BulkExportRecordingsRequestRecordingFormat> getRecordingFormat() {
    return recordingFormat;
  }

  /**
   * @return Filter by a specific recording ID. Applies when the range is 30 days or less.
   */
  @JsonProperty("recording_id")
  public Optional<String> getRecordingId() {
    return recordingId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BulkExportRecordingsRequest && equalTo((BulkExportRecordingsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BulkExportRecordingsRequest other) {
    return recipient.equals(other.recipient) && from.equals(other.from) && to.equals(other.to) && recordingStorageDuration.equals(other.recordingStorageDuration) && recordingStorageDurationGte.equals(other.recordingStorageDurationGte) && recordingStorageDurationGt.equals(other.recordingStorageDurationGt) && recordingStorageDurationLte.equals(other.recordingStorageDurationLte) && recordingStorageDurationLt.equals(other.recordingStorageDurationLt) && fromNumber.equals(other.fromNumber) && toNumber.equals(other.toNumber) && callUuid.equals(other.callUuid) && conferenceName.equals(other.conferenceName) && recordingFormat.equals(other.recordingFormat) && recordingId.equals(other.recordingId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.recipient, this.from, this.to, this.recordingStorageDuration, this.recordingStorageDurationGte, this.recordingStorageDurationGt, this.recordingStorageDurationLte, this.recordingStorageDurationLt, this.fromNumber, this.toNumber, this.callUuid, this.conferenceName, this.recordingFormat, this.recordingId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static RecipientStage builder() {
    return new Builder();
  }

  public interface RecipientStage {
    /**
     * <p>Email delivery targets for the export archive.</p>
     */
    _FinalStage recipient(@NotNull BulkExportRecordingsRequestRecipient recipient);

    Builder from(BulkExportRecordingsRequest other);
  }

  public interface _FinalStage {
    BulkExportRecordingsRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Start date for the export. Format: YYYY-MM-DD HH:MM:SS. Defaults to 7 days ago.</p>
     */
    _FinalStage from(Optional<String> from);

    _FinalStage from(String from);

    /**
     * <p>End date for the export. Format: YYYY-MM-DD HH:MM:SS. Defaults to the current time.</p>
     */
    _FinalStage to(Optional<String> to);

    _FinalStage to(String to);

    /**
     * <p>Export recordings exactly N days old. <code>&quot;7&quot;</code> exports recordings from exactly 7 days ago.</p>
     */
    _FinalStage recordingStorageDuration(Optional<String> recordingStorageDuration);

    _FinalStage recordingStorageDuration(String recordingStorageDuration);

    /**
     * <p>Export recordings N days old or older. <code>&quot;7&quot;</code> exports recordings 7 days old and older.</p>
     */
    _FinalStage recordingStorageDurationGte(Optional<String> recordingStorageDurationGte);

    _FinalStage recordingStorageDurationGte(String recordingStorageDurationGte);

    /**
     * <p>Export recordings older than N days. <code>&quot;7&quot;</code> exports recordings 8 days old and older.</p>
     */
    _FinalStage recordingStorageDurationGt(Optional<String> recordingStorageDurationGt);

    _FinalStage recordingStorageDurationGt(String recordingStorageDurationGt);

    /**
     * <p>Export recordings N days old or newer. <code>&quot;30&quot;</code> exports recordings 0-30 days old.</p>
     */
    _FinalStage recordingStorageDurationLte(Optional<String> recordingStorageDurationLte);

    _FinalStage recordingStorageDurationLte(String recordingStorageDurationLte);

    /**
     * <p>Export recordings newer than N days. <code>&quot;30&quot;</code> exports recordings 0-29 days old.</p>
     */
    _FinalStage recordingStorageDurationLt(Optional<String> recordingStorageDurationLt);

    _FinalStage recordingStorageDurationLt(String recordingStorageDurationLt);

    /**
     * <p>Filter by caller phone number. Applies when the range is 30 days or less.</p>
     */
    _FinalStage fromNumber(Optional<String> fromNumber);

    _FinalStage fromNumber(String fromNumber);

    /**
     * <p>Filter by destination phone number. Applies when the range is 30 days or less.</p>
     */
    _FinalStage toNumber(Optional<String> toNumber);

    _FinalStage toNumber(String toNumber);

    /**
     * <p>Filter by call UUID. Also use this field for a conference_uuid or mpc_uuid. Applies when the range is 30 days or less.</p>
     */
    _FinalStage callUuid(Optional<String> callUuid);

    _FinalStage callUuid(String callUuid);

    /**
     * <p>Filter by conference name. Also use this field for an mpc_name. Applies when the range is 30 days or less.</p>
     */
    _FinalStage conferenceName(Optional<String> conferenceName);

    _FinalStage conferenceName(String conferenceName);

    /**
     * <p>Filter by recording format. Applies when the range is 30 days or less.</p>
     */
    _FinalStage recordingFormat(
        Optional<BulkExportRecordingsRequestRecordingFormat> recordingFormat);

    _FinalStage recordingFormat(BulkExportRecordingsRequestRecordingFormat recordingFormat);

    /**
     * <p>Filter by a specific recording ID. Applies when the range is 30 days or less.</p>
     */
    _FinalStage recordingId(Optional<String> recordingId);

    _FinalStage recordingId(String recordingId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements RecipientStage, _FinalStage {
    private BulkExportRecordingsRequestRecipient recipient;

    private Optional<String> recordingId = Optional.empty();

    private Optional<BulkExportRecordingsRequestRecordingFormat> recordingFormat = Optional.empty();

    private Optional<String> conferenceName = Optional.empty();

    private Optional<String> callUuid = Optional.empty();

    private Optional<String> toNumber = Optional.empty();

    private Optional<String> fromNumber = Optional.empty();

    private Optional<String> recordingStorageDurationLt = Optional.empty();

    private Optional<String> recordingStorageDurationLte = Optional.empty();

    private Optional<String> recordingStorageDurationGt = Optional.empty();

    private Optional<String> recordingStorageDurationGte = Optional.empty();

    private Optional<String> recordingStorageDuration = Optional.empty();

    private Optional<String> to = Optional.empty();

    private Optional<String> from = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BulkExportRecordingsRequest other) {
      recipient(other.getRecipient());
      from(other.getFrom());
      to(other.getTo());
      recordingStorageDuration(other.getRecordingStorageDuration());
      recordingStorageDurationGte(other.getRecordingStorageDurationGte());
      recordingStorageDurationGt(other.getRecordingStorageDurationGt());
      recordingStorageDurationLte(other.getRecordingStorageDurationLte());
      recordingStorageDurationLt(other.getRecordingStorageDurationLt());
      fromNumber(other.getFromNumber());
      toNumber(other.getToNumber());
      callUuid(other.getCallUuid());
      conferenceName(other.getConferenceName());
      recordingFormat(other.getRecordingFormat());
      recordingId(other.getRecordingId());
      return this;
    }

    /**
     * <p>Email delivery targets for the export archive.</p>
     * <p>Email delivery targets for the export archive.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("recipient")
    public _FinalStage recipient(@NotNull BulkExportRecordingsRequestRecipient recipient) {
      this.recipient = Objects.requireNonNull(recipient, "recipient must not be null");
      return this;
    }

    /**
     * <p>Filter by a specific recording ID. Applies when the range is 30 days or less.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage recordingId(String recordingId) {
      this.recordingId = Optional.ofNullable(recordingId);
      return this;
    }

    /**
     * <p>Filter by a specific recording ID. Applies when the range is 30 days or less.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "recording_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage recordingId(Optional<String> recordingId) {
      this.recordingId = recordingId;
      return this;
    }

    /**
     * <p>Filter by recording format. Applies when the range is 30 days or less.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage recordingFormat(BulkExportRecordingsRequestRecordingFormat recordingFormat) {
      this.recordingFormat = Optional.ofNullable(recordingFormat);
      return this;
    }

    /**
     * <p>Filter by recording format. Applies when the range is 30 days or less.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "recording_format",
        nulls = Nulls.SKIP
    )
    public _FinalStage recordingFormat(
        Optional<BulkExportRecordingsRequestRecordingFormat> recordingFormat) {
      this.recordingFormat = recordingFormat;
      return this;
    }

    /**
     * <p>Filter by conference name. Also use this field for an mpc_name. Applies when the range is 30 days or less.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage conferenceName(String conferenceName) {
      this.conferenceName = Optional.ofNullable(conferenceName);
      return this;
    }

    /**
     * <p>Filter by conference name. Also use this field for an mpc_name. Applies when the range is 30 days or less.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "conference_name",
        nulls = Nulls.SKIP
    )
    public _FinalStage conferenceName(Optional<String> conferenceName) {
      this.conferenceName = conferenceName;
      return this;
    }

    /**
     * <p>Filter by call UUID. Also use this field for a conference_uuid or mpc_uuid. Applies when the range is 30 days or less.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage callUuid(String callUuid) {
      this.callUuid = Optional.ofNullable(callUuid);
      return this;
    }

    /**
     * <p>Filter by call UUID. Also use this field for a conference_uuid or mpc_uuid. Applies when the range is 30 days or less.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "call_uuid",
        nulls = Nulls.SKIP
    )
    public _FinalStage callUuid(Optional<String> callUuid) {
      this.callUuid = callUuid;
      return this;
    }

    /**
     * <p>Filter by destination phone number. Applies when the range is 30 days or less.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage toNumber(String toNumber) {
      this.toNumber = Optional.ofNullable(toNumber);
      return this;
    }

    /**
     * <p>Filter by destination phone number. Applies when the range is 30 days or less.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "to_number",
        nulls = Nulls.SKIP
    )
    public _FinalStage toNumber(Optional<String> toNumber) {
      this.toNumber = toNumber;
      return this;
    }

    /**
     * <p>Filter by caller phone number. Applies when the range is 30 days or less.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage fromNumber(String fromNumber) {
      this.fromNumber = Optional.ofNullable(fromNumber);
      return this;
    }

    /**
     * <p>Filter by caller phone number. Applies when the range is 30 days or less.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "from_number",
        nulls = Nulls.SKIP
    )
    public _FinalStage fromNumber(Optional<String> fromNumber) {
      this.fromNumber = fromNumber;
      return this;
    }

    /**
     * <p>Export recordings newer than N days. <code>&quot;30&quot;</code> exports recordings 0-29 days old.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage recordingStorageDurationLt(String recordingStorageDurationLt) {
      this.recordingStorageDurationLt = Optional.ofNullable(recordingStorageDurationLt);
      return this;
    }

    /**
     * <p>Export recordings newer than N days. <code>&quot;30&quot;</code> exports recordings 0-29 days old.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "recording_storage_duration__lt",
        nulls = Nulls.SKIP
    )
    public _FinalStage recordingStorageDurationLt(Optional<String> recordingStorageDurationLt) {
      this.recordingStorageDurationLt = recordingStorageDurationLt;
      return this;
    }

    /**
     * <p>Export recordings N days old or newer. <code>&quot;30&quot;</code> exports recordings 0-30 days old.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage recordingStorageDurationLte(String recordingStorageDurationLte) {
      this.recordingStorageDurationLte = Optional.ofNullable(recordingStorageDurationLte);
      return this;
    }

    /**
     * <p>Export recordings N days old or newer. <code>&quot;30&quot;</code> exports recordings 0-30 days old.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "recording_storage_duration__lte",
        nulls = Nulls.SKIP
    )
    public _FinalStage recordingStorageDurationLte(Optional<String> recordingStorageDurationLte) {
      this.recordingStorageDurationLte = recordingStorageDurationLte;
      return this;
    }

    /**
     * <p>Export recordings older than N days. <code>&quot;7&quot;</code> exports recordings 8 days old and older.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage recordingStorageDurationGt(String recordingStorageDurationGt) {
      this.recordingStorageDurationGt = Optional.ofNullable(recordingStorageDurationGt);
      return this;
    }

    /**
     * <p>Export recordings older than N days. <code>&quot;7&quot;</code> exports recordings 8 days old and older.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "recording_storage_duration__gt",
        nulls = Nulls.SKIP
    )
    public _FinalStage recordingStorageDurationGt(Optional<String> recordingStorageDurationGt) {
      this.recordingStorageDurationGt = recordingStorageDurationGt;
      return this;
    }

    /**
     * <p>Export recordings N days old or older. <code>&quot;7&quot;</code> exports recordings 7 days old and older.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage recordingStorageDurationGte(String recordingStorageDurationGte) {
      this.recordingStorageDurationGte = Optional.ofNullable(recordingStorageDurationGte);
      return this;
    }

    /**
     * <p>Export recordings N days old or older. <code>&quot;7&quot;</code> exports recordings 7 days old and older.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "recording_storage_duration__gte",
        nulls = Nulls.SKIP
    )
    public _FinalStage recordingStorageDurationGte(Optional<String> recordingStorageDurationGte) {
      this.recordingStorageDurationGte = recordingStorageDurationGte;
      return this;
    }

    /**
     * <p>Export recordings exactly N days old. <code>&quot;7&quot;</code> exports recordings from exactly 7 days ago.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage recordingStorageDuration(String recordingStorageDuration) {
      this.recordingStorageDuration = Optional.ofNullable(recordingStorageDuration);
      return this;
    }

    /**
     * <p>Export recordings exactly N days old. <code>&quot;7&quot;</code> exports recordings from exactly 7 days ago.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "recording_storage_duration",
        nulls = Nulls.SKIP
    )
    public _FinalStage recordingStorageDuration(Optional<String> recordingStorageDuration) {
      this.recordingStorageDuration = recordingStorageDuration;
      return this;
    }

    /**
     * <p>End date for the export. Format: YYYY-MM-DD HH:MM:SS. Defaults to the current time.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage to(String to) {
      this.to = Optional.ofNullable(to);
      return this;
    }

    /**
     * <p>End date for the export. Format: YYYY-MM-DD HH:MM:SS. Defaults to the current time.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "to",
        nulls = Nulls.SKIP
    )
    public _FinalStage to(Optional<String> to) {
      this.to = to;
      return this;
    }

    /**
     * <p>Start date for the export. Format: YYYY-MM-DD HH:MM:SS. Defaults to 7 days ago.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage from(String from) {
      this.from = Optional.ofNullable(from);
      return this;
    }

    /**
     * <p>Start date for the export. Format: YYYY-MM-DD HH:MM:SS. Defaults to 7 days ago.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "from",
        nulls = Nulls.SKIP
    )
    public _FinalStage from(Optional<String> from) {
      this.from = from;
      return this;
    }

    @java.lang.Override
    public BulkExportRecordingsRequest build() {
      return new BulkExportRecordingsRequest(recipient, from, to, recordingStorageDuration, recordingStorageDurationGte, recordingStorageDurationGt, recordingStorageDurationLte, recordingStorageDurationLt, fromNumber, toNumber, callUuid, conferenceName, recordingFormat, recordingId, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
