/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.conferencerecording.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class StartConferenceRecordingRequestFileFormat {
  public static final StartConferenceRecordingRequestFileFormat WAV = new StartConferenceRecordingRequestFileFormat(Value.WAV, "wav");

  public static final StartConferenceRecordingRequestFileFormat MP3 = new StartConferenceRecordingRequestFileFormat(Value.MP3, "mp3");

  private final Value value;

  private final String string;

  StartConferenceRecordingRequestFileFormat(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof StartConferenceRecordingRequestFileFormat && this.string.equals(((StartConferenceRecordingRequestFileFormat) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case WAV:
        return visitor.visitWav();
      case MP3:
        return visitor.visitMp3();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static StartConferenceRecordingRequestFileFormat valueOf(String value) {
    switch (value) {
      case "wav":
        return WAV;
      case "mp3":
        return MP3;
      default:
        return new StartConferenceRecordingRequestFileFormat(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    MP3,

    WAV,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitMp3();

    T visitWav();

    T visitUnknown(String unknownType);
  }
}
