/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.livecalls.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetLiveCallResponse.Builder.class
)
public final class GetLiveCallResponse {
  private final String apiId;

  private final String callStatus;

  private final String callUuid;

  private final String callerName;

  private final String direction;

  private final String from;

  private final String requestUuid;

  private final String sessionStart;

  private final String stirAttestation;

  private final String stirVerification;

  private final String to;

  private final Map<String, Object> additionalProperties;

  private GetLiveCallResponse(String apiId, String callStatus, String callUuid, String callerName,
      String direction, String from, String requestUuid, String sessionStart,
      String stirAttestation, String stirVerification, String to,
      Map<String, Object> additionalProperties) {
    this.apiId = apiId;
    this.callStatus = callStatus;
    this.callUuid = callUuid;
    this.callerName = callerName;
    this.direction = direction;
    this.from = from;
    this.requestUuid = requestUuid;
    this.sessionStart = sessionStart;
    this.stirAttestation = stirAttestation;
    this.stirVerification = stirVerification;
    this.to = to;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Unique identifier for this API request
   */
  @JsonProperty("api_id")
  public String getApiId() {
    return apiId;
  }

  /**
   * @return Current state of the call (e.g. in-progress)
   */
  @JsonProperty("call_status")
  public String getCallStatus() {
    return callStatus;
  }

  @JsonProperty("call_uuid")
  public String getCallUuid() {
    return callUuid;
  }

  @JsonProperty("caller_name")
  public String getCallerName() {
    return callerName;
  }

  @JsonProperty("direction")
  public String getDirection() {
    return direction;
  }

  @JsonProperty("from")
  public String getFrom() {
    return from;
  }

  @JsonProperty("request_uuid")
  public String getRequestUuid() {
    return requestUuid;
  }

  @JsonProperty("session_start")
  public String getSessionStart() {
    return sessionStart;
  }

  @JsonProperty("stir_attestation")
  public String getStirAttestation() {
    return stirAttestation;
  }

  @JsonProperty("stir_verification")
  public String getStirVerification() {
    return stirVerification;
  }

  @JsonProperty("to")
  public String getTo() {
    return to;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetLiveCallResponse && equalTo((GetLiveCallResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetLiveCallResponse other) {
    return apiId.equals(other.apiId) && callStatus.equals(other.callStatus) && callUuid.equals(other.callUuid) && callerName.equals(other.callerName) && direction.equals(other.direction) && from.equals(other.from) && requestUuid.equals(other.requestUuid) && sessionStart.equals(other.sessionStart) && stirAttestation.equals(other.stirAttestation) && stirVerification.equals(other.stirVerification) && to.equals(other.to);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.apiId, this.callStatus, this.callUuid, this.callerName, this.direction, this.from, this.requestUuid, this.sessionStart, this.stirAttestation, this.stirVerification, this.to);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ApiIdStage builder() {
    return new Builder();
  }

  public interface ApiIdStage {
    /**
     * <p>Unique identifier for this API request</p>
     */
    CallStatusStage apiId(@NotNull String apiId);

    Builder from(GetLiveCallResponse other);
  }

  public interface CallStatusStage {
    /**
     * <p>Current state of the call (e.g. in-progress)</p>
     */
    CallUuidStage callStatus(@NotNull String callStatus);
  }

  public interface CallUuidStage {
    CallerNameStage callUuid(@NotNull String callUuid);
  }

  public interface CallerNameStage {
    DirectionStage callerName(@NotNull String callerName);
  }

  public interface DirectionStage {
    FromStage direction(@NotNull String direction);
  }

  public interface FromStage {
    RequestUuidStage from(@NotNull String from);
  }

  public interface RequestUuidStage {
    SessionStartStage requestUuid(@NotNull String requestUuid);
  }

  public interface SessionStartStage {
    StirAttestationStage sessionStart(@NotNull String sessionStart);
  }

  public interface StirAttestationStage {
    StirVerificationStage stirAttestation(@NotNull String stirAttestation);
  }

  public interface StirVerificationStage {
    ToStage stirVerification(@NotNull String stirVerification);
  }

  public interface ToStage {
    _FinalStage to(@NotNull String to);
  }

  public interface _FinalStage {
    GetLiveCallResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ApiIdStage, CallStatusStage, CallUuidStage, CallerNameStage, DirectionStage, FromStage, RequestUuidStage, SessionStartStage, StirAttestationStage, StirVerificationStage, ToStage, _FinalStage {
    private String apiId;

    private String callStatus;

    private String callUuid;

    private String callerName;

    private String direction;

    private String from;

    private String requestUuid;

    private String sessionStart;

    private String stirAttestation;

    private String stirVerification;

    private String to;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GetLiveCallResponse other) {
      apiId(other.getApiId());
      callStatus(other.getCallStatus());
      callUuid(other.getCallUuid());
      callerName(other.getCallerName());
      direction(other.getDirection());
      from(other.getFrom());
      requestUuid(other.getRequestUuid());
      sessionStart(other.getSessionStart());
      stirAttestation(other.getStirAttestation());
      stirVerification(other.getStirVerification());
      to(other.getTo());
      return this;
    }

    /**
     * <p>Unique identifier for this API request</p>
     * <p>Unique identifier for this API request</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("api_id")
    public CallStatusStage apiId(@NotNull String apiId) {
      this.apiId = Objects.requireNonNull(apiId, "apiId must not be null");
      return this;
    }

    /**
     * <p>Current state of the call (e.g. in-progress)</p>
     * <p>Current state of the call (e.g. in-progress)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("call_status")
    public CallUuidStage callStatus(@NotNull String callStatus) {
      this.callStatus = Objects.requireNonNull(callStatus, "callStatus must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("call_uuid")
    public CallerNameStage callUuid(@NotNull String callUuid) {
      this.callUuid = Objects.requireNonNull(callUuid, "callUuid must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("caller_name")
    public DirectionStage callerName(@NotNull String callerName) {
      this.callerName = Objects.requireNonNull(callerName, "callerName must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("direction")
    public FromStage direction(@NotNull String direction) {
      this.direction = Objects.requireNonNull(direction, "direction must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("from")
    public RequestUuidStage from(@NotNull String from) {
      this.from = Objects.requireNonNull(from, "from must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("request_uuid")
    public SessionStartStage requestUuid(@NotNull String requestUuid) {
      this.requestUuid = Objects.requireNonNull(requestUuid, "requestUuid must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("session_start")
    public StirAttestationStage sessionStart(@NotNull String sessionStart) {
      this.sessionStart = Objects.requireNonNull(sessionStart, "sessionStart must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("stir_attestation")
    public StirVerificationStage stirAttestation(@NotNull String stirAttestation) {
      this.stirAttestation = Objects.requireNonNull(stirAttestation, "stirAttestation must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("stir_verification")
    public ToStage stirVerification(@NotNull String stirVerification) {
      this.stirVerification = Objects.requireNonNull(stirVerification, "stirVerification must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("to")
    public _FinalStage to(@NotNull String to) {
      this.to = Objects.requireNonNull(to, "to must not be null");
      return this;
    }

    @java.lang.Override
    public GetLiveCallResponse build() {
      return new GetLiveCallResponse(apiId, callStatus, callUuid, callerName, direction, from, requestUuid, sessionStart, stirAttestation, stirVerification, to, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
