/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.partnerapi.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import resources.partnerapi.types.CreateKycSessionRequestFlowType;
import resources.partnerapi.types.CreateKycSessionRequestReminderScheduleItem;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateKycSessionRequest.Builder.class
)
public final class CreateKycSessionRequest {
  private final String accountAuthId;

  private final Optional<CreateKycSessionRequestFlowType> flowType;

  private final Optional<String> customerEmail;

  private final Optional<String> redirectUrl;

  private final Optional<String> webhookUrl;

  private final Optional<Integer> expiresInDays;

  private final Optional<List<CreateKycSessionRequestReminderScheduleItem>> reminderSchedule;

  private final Optional<Map<String, Object>> metadata;

  private final Map<String, Object> additionalProperties;

  private CreateKycSessionRequest(String accountAuthId,
      Optional<CreateKycSessionRequestFlowType> flowType, Optional<String> customerEmail,
      Optional<String> redirectUrl, Optional<String> webhookUrl, Optional<Integer> expiresInDays,
      Optional<List<CreateKycSessionRequestReminderScheduleItem>> reminderSchedule,
      Optional<Map<String, Object>> metadata, Map<String, Object> additionalProperties) {
    this.accountAuthId = accountAuthId;
    this.flowType = flowType;
    this.customerEmail = customerEmail;
    this.redirectUrl = redirectUrl;
    this.webhookUrl = webhookUrl;
    this.expiresInDays = expiresInDays;
    this.reminderSchedule = reminderSchedule;
    this.metadata = metadata;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Customer's auth_id (from create-customer-account).
   */
  @JsonProperty("account_auth_id")
  public String getAccountAuthId() {
    return accountAuthId;
  }

  /**
   * @return Delivery mode. <code>email</code> (default) emails the customer the KYC link.
   * <code>redirect</code> returns a <code>widget_url</code> in the response for immediate redirect.
   */
  @JsonProperty("flow_type")
  public Optional<CreateKycSessionRequestFlowType> getFlowType() {
    return flowType;
  }

  /**
   * @return Required when <code>flow_type</code> is <code>email</code>. Ignored otherwise.
   */
  @JsonProperty("customer_email")
  public Optional<String> getCustomerEmail() {
    return customerEmail;
  }

  /**
   * @return Required when <code>flow_type</code> is <code>redirect</code>. After verification the customer's
   * browser is sent to this URL with query params <code>session_id</code>, <code>status</code>, <code>auth_id</code>.
   */
  @JsonProperty("redirect_url")
  public Optional<String> getRedirectUrl() {
    return redirectUrl;
  }

  /**
   * @return VoBiz POSTs the KYC result here.
   */
  @JsonProperty("webhook_url")
  public Optional<String> getWebhookUrl() {
    return webhookUrl;
  }

  /**
   * @return Days before the KYC link expires.
   */
  @JsonProperty("expires_in_days")
  public Optional<Integer> getExpiresInDays() {
    return expiresInDays;
  }

  /**
   * @return Auto reminder emails before expiry. Email flow only.
   */
  @JsonProperty("reminder_schedule")
  public Optional<List<CreateKycSessionRequestReminderScheduleItem>> getReminderSchedule() {
    return reminderSchedule;
  }

  /**
   * @return Free-form key/value object echoed back on GET and webhooks.
   */
  @JsonProperty("metadata")
  public Optional<Map<String, Object>> getMetadata() {
    return metadata;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateKycSessionRequest && equalTo((CreateKycSessionRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateKycSessionRequest other) {
    return accountAuthId.equals(other.accountAuthId) && flowType.equals(other.flowType) && customerEmail.equals(other.customerEmail) && redirectUrl.equals(other.redirectUrl) && webhookUrl.equals(other.webhookUrl) && expiresInDays.equals(other.expiresInDays) && reminderSchedule.equals(other.reminderSchedule) && metadata.equals(other.metadata);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.accountAuthId, this.flowType, this.customerEmail, this.redirectUrl, this.webhookUrl, this.expiresInDays, this.reminderSchedule, this.metadata);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static AccountAuthIdStage builder() {
    return new Builder();
  }

  public interface AccountAuthIdStage {
    /**
     * <p>Customer's auth_id (from create-customer-account).</p>
     */
    _FinalStage accountAuthId(@NotNull String accountAuthId);

    Builder from(CreateKycSessionRequest other);
  }

  public interface _FinalStage {
    CreateKycSessionRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Delivery mode. <code>email</code> (default) emails the customer the KYC link.
     * <code>redirect</code> returns a <code>widget_url</code> in the response for immediate redirect.</p>
     */
    _FinalStage flowType(Optional<CreateKycSessionRequestFlowType> flowType);

    _FinalStage flowType(CreateKycSessionRequestFlowType flowType);

    /**
     * <p>Required when <code>flow_type</code> is <code>email</code>. Ignored otherwise.</p>
     */
    _FinalStage customerEmail(Optional<String> customerEmail);

    _FinalStage customerEmail(String customerEmail);

    /**
     * <p>Required when <code>flow_type</code> is <code>redirect</code>. After verification the customer's
     * browser is sent to this URL with query params <code>session_id</code>, <code>status</code>, <code>auth_id</code>.</p>
     */
    _FinalStage redirectUrl(Optional<String> redirectUrl);

    _FinalStage redirectUrl(String redirectUrl);

    /**
     * <p>VoBiz POSTs the KYC result here.</p>
     */
    _FinalStage webhookUrl(Optional<String> webhookUrl);

    _FinalStage webhookUrl(String webhookUrl);

    /**
     * <p>Days before the KYC link expires.</p>
     */
    _FinalStage expiresInDays(Optional<Integer> expiresInDays);

    _FinalStage expiresInDays(Integer expiresInDays);

    /**
     * <p>Auto reminder emails before expiry. Email flow only.</p>
     */
    _FinalStage reminderSchedule(
        Optional<List<CreateKycSessionRequestReminderScheduleItem>> reminderSchedule);

    _FinalStage reminderSchedule(
        List<CreateKycSessionRequestReminderScheduleItem> reminderSchedule);

    /**
     * <p>Free-form key/value object echoed back on GET and webhooks.</p>
     */
    _FinalStage metadata(Optional<Map<String, Object>> metadata);

    _FinalStage metadata(Map<String, Object> metadata);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements AccountAuthIdStage, _FinalStage {
    private String accountAuthId;

    private Optional<Map<String, Object>> metadata = Optional.empty();

    private Optional<List<CreateKycSessionRequestReminderScheduleItem>> reminderSchedule = Optional.empty();

    private Optional<Integer> expiresInDays = Optional.empty();

    private Optional<String> webhookUrl = Optional.empty();

    private Optional<String> redirectUrl = Optional.empty();

    private Optional<String> customerEmail = Optional.empty();

    private Optional<CreateKycSessionRequestFlowType> flowType = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateKycSessionRequest other) {
      accountAuthId(other.getAccountAuthId());
      flowType(other.getFlowType());
      customerEmail(other.getCustomerEmail());
      redirectUrl(other.getRedirectUrl());
      webhookUrl(other.getWebhookUrl());
      expiresInDays(other.getExpiresInDays());
      reminderSchedule(other.getReminderSchedule());
      metadata(other.getMetadata());
      return this;
    }

    /**
     * <p>Customer's auth_id (from create-customer-account).</p>
     * <p>Customer's auth_id (from create-customer-account).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("account_auth_id")
    public _FinalStage accountAuthId(@NotNull String accountAuthId) {
      this.accountAuthId = Objects.requireNonNull(accountAuthId, "accountAuthId must not be null");
      return this;
    }

    /**
     * <p>Free-form key/value object echoed back on GET and webhooks.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metadata(Map<String, Object> metadata) {
      this.metadata = Optional.ofNullable(metadata);
      return this;
    }

    /**
     * <p>Free-form key/value object echoed back on GET and webhooks.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "metadata",
        nulls = Nulls.SKIP
    )
    public _FinalStage metadata(Optional<Map<String, Object>> metadata) {
      this.metadata = metadata;
      return this;
    }

    /**
     * <p>Auto reminder emails before expiry. Email flow only.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage reminderSchedule(
        List<CreateKycSessionRequestReminderScheduleItem> reminderSchedule) {
      this.reminderSchedule = Optional.ofNullable(reminderSchedule);
      return this;
    }

    /**
     * <p>Auto reminder emails before expiry. Email flow only.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "reminder_schedule",
        nulls = Nulls.SKIP
    )
    public _FinalStage reminderSchedule(
        Optional<List<CreateKycSessionRequestReminderScheduleItem>> reminderSchedule) {
      this.reminderSchedule = reminderSchedule;
      return this;
    }

    /**
     * <p>Days before the KYC link expires.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage expiresInDays(Integer expiresInDays) {
      this.expiresInDays = Optional.ofNullable(expiresInDays);
      return this;
    }

    /**
     * <p>Days before the KYC link expires.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "expires_in_days",
        nulls = Nulls.SKIP
    )
    public _FinalStage expiresInDays(Optional<Integer> expiresInDays) {
      this.expiresInDays = expiresInDays;
      return this;
    }

    /**
     * <p>VoBiz POSTs the KYC result here.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage webhookUrl(String webhookUrl) {
      this.webhookUrl = Optional.ofNullable(webhookUrl);
      return this;
    }

    /**
     * <p>VoBiz POSTs the KYC result here.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "webhook_url",
        nulls = Nulls.SKIP
    )
    public _FinalStage webhookUrl(Optional<String> webhookUrl) {
      this.webhookUrl = webhookUrl;
      return this;
    }

    /**
     * <p>Required when <code>flow_type</code> is <code>redirect</code>. After verification the customer's
     * browser is sent to this URL with query params <code>session_id</code>, <code>status</code>, <code>auth_id</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage redirectUrl(String redirectUrl) {
      this.redirectUrl = Optional.ofNullable(redirectUrl);
      return this;
    }

    /**
     * <p>Required when <code>flow_type</code> is <code>redirect</code>. After verification the customer's
     * browser is sent to this URL with query params <code>session_id</code>, <code>status</code>, <code>auth_id</code>.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "redirect_url",
        nulls = Nulls.SKIP
    )
    public _FinalStage redirectUrl(Optional<String> redirectUrl) {
      this.redirectUrl = redirectUrl;
      return this;
    }

    /**
     * <p>Required when <code>flow_type</code> is <code>email</code>. Ignored otherwise.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage customerEmail(String customerEmail) {
      this.customerEmail = Optional.ofNullable(customerEmail);
      return this;
    }

    /**
     * <p>Required when <code>flow_type</code> is <code>email</code>. Ignored otherwise.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "customer_email",
        nulls = Nulls.SKIP
    )
    public _FinalStage customerEmail(Optional<String> customerEmail) {
      this.customerEmail = customerEmail;
      return this;
    }

    /**
     * <p>Delivery mode. <code>email</code> (default) emails the customer the KYC link.
     * <code>redirect</code> returns a <code>widget_url</code> in the response for immediate redirect.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage flowType(CreateKycSessionRequestFlowType flowType) {
      this.flowType = Optional.ofNullable(flowType);
      return this;
    }

    /**
     * <p>Delivery mode. <code>email</code> (default) emails the customer the KYC link.
     * <code>redirect</code> returns a <code>widget_url</code> in the response for immediate redirect.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "flow_type",
        nulls = Nulls.SKIP
    )
    public _FinalStage flowType(Optional<CreateKycSessionRequestFlowType> flowType) {
      this.flowType = flowType;
      return this;
    }

    @java.lang.Override
    public CreateKycSessionRequest build() {
      return new CreateKycSessionRequest(accountAuthId, flowType, customerEmail, redirectUrl, webhookUrl, expiresInDays, reminderSchedule, metadata, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
