/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.partnerapi.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateCustomerAccountRequest.Builder.class
)
public final class CreateCustomerAccountRequest {
  private final String name;

  private final String email;

  private final String phone;

  private final String password;

  private final Optional<String> company;

  private final String country;

  private final Map<String, Object> additionalProperties;

  private CreateCustomerAccountRequest(String name, String email, String phone, String password,
      Optional<String> company, String country, Map<String, Object> additionalProperties) {
    this.name = name;
    this.email = email;
    this.phone = phone;
    this.password = password;
    this.company = company;
    this.country = country;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Customer's full name.
   */
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  /**
   * @return Customer's email. KYC link is sent here.
   */
  @JsonProperty("email")
  public String getEmail() {
    return email;
  }

  /**
   * @return E.164 format.
   */
  @JsonProperty("phone")
  public String getPhone() {
    return phone;
  }

  /**
   * @return Min 8 chars, must include a number and a special character.
   */
  @JsonProperty("password")
  public String getPassword() {
    return password;
  }

  /**
   * @return Legal company or business name.
   */
  @JsonProperty("company")
  public Optional<String> getCompany() {
    return company;
  }

  /**
   * @return ISO 2-letter country code.
   */
  @JsonProperty("country")
  public String getCountry() {
    return country;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateCustomerAccountRequest && equalTo((CreateCustomerAccountRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateCustomerAccountRequest other) {
    return name.equals(other.name) && email.equals(other.email) && phone.equals(other.phone) && password.equals(other.password) && company.equals(other.company) && country.equals(other.country);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.email, this.phone, this.password, this.company, this.country);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    /**
     * <p>Customer's full name.</p>
     */
    EmailStage name(@NotNull String name);

    Builder from(CreateCustomerAccountRequest other);
  }

  public interface EmailStage {
    /**
     * <p>Customer's email. KYC link is sent here.</p>
     */
    PhoneStage email(@NotNull String email);
  }

  public interface PhoneStage {
    /**
     * <p>E.164 format.</p>
     */
    PasswordStage phone(@NotNull String phone);
  }

  public interface PasswordStage {
    /**
     * <p>Min 8 chars, must include a number and a special character.</p>
     */
    CountryStage password(@NotNull String password);
  }

  public interface CountryStage {
    /**
     * <p>ISO 2-letter country code.</p>
     */
    _FinalStage country(@NotNull String country);
  }

  public interface _FinalStage {
    CreateCustomerAccountRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Legal company or business name.</p>
     */
    _FinalStage company(Optional<String> company);

    _FinalStage company(String company);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, EmailStage, PhoneStage, PasswordStage, CountryStage, _FinalStage {
    private String name;

    private String email;

    private String phone;

    private String password;

    private String country;

    private Optional<String> company = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateCustomerAccountRequest other) {
      name(other.getName());
      email(other.getEmail());
      phone(other.getPhone());
      password(other.getPassword());
      company(other.getCompany());
      country(other.getCountry());
      return this;
    }

    /**
     * <p>Customer's full name.</p>
     * <p>Customer's full name.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("name")
    public EmailStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    /**
     * <p>Customer's email. KYC link is sent here.</p>
     * <p>Customer's email. KYC link is sent here.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("email")
    public PhoneStage email(@NotNull String email) {
      this.email = Objects.requireNonNull(email, "email must not be null");
      return this;
    }

    /**
     * <p>E.164 format.</p>
     * <p>E.164 format.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("phone")
    public PasswordStage phone(@NotNull String phone) {
      this.phone = Objects.requireNonNull(phone, "phone must not be null");
      return this;
    }

    /**
     * <p>Min 8 chars, must include a number and a special character.</p>
     * <p>Min 8 chars, must include a number and a special character.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("password")
    public CountryStage password(@NotNull String password) {
      this.password = Objects.requireNonNull(password, "password must not be null");
      return this;
    }

    /**
     * <p>ISO 2-letter country code.</p>
     * <p>ISO 2-letter country code.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("country")
    public _FinalStage country(@NotNull String country) {
      this.country = Objects.requireNonNull(country, "country must not be null");
      return this;
    }

    /**
     * <p>Legal company or business name.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage company(String company) {
      this.company = Optional.ofNullable(company);
      return this;
    }

    /**
     * <p>Legal company or business name.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "company",
        nulls = Nulls.SKIP
    )
    public _FinalStage company(Optional<String> company) {
      this.company = company;
      return this;
    }

    @java.lang.Override
    public CreateCustomerAccountRequest build() {
      return new CreateCustomerAccountRequest(name, email, phone, password, company, country, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
