/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.partnerapi.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import resources.partnerapi.types.ListCustomerCdrsRequestCallDirection;
import resources.partnerapi.types.ListCustomerCdrsRequestStatus;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListCustomerCdrsRequest.Builder.class
)
public final class ListCustomerCdrsRequest {
  private final Optional<String> startDate;

  private final Optional<String> endDate;

  private final Optional<ListCustomerCdrsRequestCallDirection> callDirection;

  private final Optional<ListCustomerCdrsRequestStatus> status;

  private final Optional<Integer> minDuration;

  private final Optional<String> hangupCause;

  private final Optional<Integer> perPage;

  private final Map<String, Object> additionalProperties;

  private ListCustomerCdrsRequest(Optional<String> startDate, Optional<String> endDate,
      Optional<ListCustomerCdrsRequestCallDirection> callDirection,
      Optional<ListCustomerCdrsRequestStatus> status, Optional<Integer> minDuration,
      Optional<String> hangupCause, Optional<Integer> perPage,
      Map<String, Object> additionalProperties) {
    this.startDate = startDate;
    this.endDate = endDate;
    this.callDirection = callDirection;
    this.status = status;
    this.minDuration = minDuration;
    this.hangupCause = hangupCause;
    this.perPage = perPage;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("start_date")
  public Optional<String> getStartDate() {
    return startDate;
  }

  @JsonProperty("end_date")
  public Optional<String> getEndDate() {
    return endDate;
  }

  @JsonProperty("call_direction")
  public Optional<ListCustomerCdrsRequestCallDirection> getCallDirection() {
    return callDirection;
  }

  @JsonProperty("status")
  public Optional<ListCustomerCdrsRequestStatus> getStatus() {
    return status;
  }

  @JsonProperty("min_duration")
  public Optional<Integer> getMinDuration() {
    return minDuration;
  }

  @JsonProperty("hangup_cause")
  public Optional<String> getHangupCause() {
    return hangupCause;
  }

  @JsonProperty("per_page")
  public Optional<Integer> getPerPage() {
    return perPage;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListCustomerCdrsRequest && equalTo((ListCustomerCdrsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListCustomerCdrsRequest other) {
    return startDate.equals(other.startDate) && endDate.equals(other.endDate) && callDirection.equals(other.callDirection) && status.equals(other.status) && minDuration.equals(other.minDuration) && hangupCause.equals(other.hangupCause) && perPage.equals(other.perPage);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.startDate, this.endDate, this.callDirection, this.status, this.minDuration, this.hangupCause, this.perPage);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> startDate = Optional.empty();

    private Optional<String> endDate = Optional.empty();

    private Optional<ListCustomerCdrsRequestCallDirection> callDirection = Optional.empty();

    private Optional<ListCustomerCdrsRequestStatus> status = Optional.empty();

    private Optional<Integer> minDuration = Optional.empty();

    private Optional<String> hangupCause = Optional.empty();

    private Optional<Integer> perPage = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ListCustomerCdrsRequest other) {
      startDate(other.getStartDate());
      endDate(other.getEndDate());
      callDirection(other.getCallDirection());
      status(other.getStatus());
      minDuration(other.getMinDuration());
      hangupCause(other.getHangupCause());
      perPage(other.getPerPage());
      return this;
    }

    @JsonSetter(
        value = "start_date",
        nulls = Nulls.SKIP
    )
    public Builder startDate(Optional<String> startDate) {
      this.startDate = startDate;
      return this;
    }

    public Builder startDate(String startDate) {
      this.startDate = Optional.ofNullable(startDate);
      return this;
    }

    @JsonSetter(
        value = "end_date",
        nulls = Nulls.SKIP
    )
    public Builder endDate(Optional<String> endDate) {
      this.endDate = endDate;
      return this;
    }

    public Builder endDate(String endDate) {
      this.endDate = Optional.ofNullable(endDate);
      return this;
    }

    @JsonSetter(
        value = "call_direction",
        nulls = Nulls.SKIP
    )
    public Builder callDirection(Optional<ListCustomerCdrsRequestCallDirection> callDirection) {
      this.callDirection = callDirection;
      return this;
    }

    public Builder callDirection(ListCustomerCdrsRequestCallDirection callDirection) {
      this.callDirection = Optional.ofNullable(callDirection);
      return this;
    }

    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<ListCustomerCdrsRequestStatus> status) {
      this.status = status;
      return this;
    }

    public Builder status(ListCustomerCdrsRequestStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    @JsonSetter(
        value = "min_duration",
        nulls = Nulls.SKIP
    )
    public Builder minDuration(Optional<Integer> minDuration) {
      this.minDuration = minDuration;
      return this;
    }

    public Builder minDuration(Integer minDuration) {
      this.minDuration = Optional.ofNullable(minDuration);
      return this;
    }

    @JsonSetter(
        value = "hangup_cause",
        nulls = Nulls.SKIP
    )
    public Builder hangupCause(Optional<String> hangupCause) {
      this.hangupCause = hangupCause;
      return this;
    }

    public Builder hangupCause(String hangupCause) {
      this.hangupCause = Optional.ofNullable(hangupCause);
      return this;
    }

    @JsonSetter(
        value = "per_page",
        nulls = Nulls.SKIP
    )
    public Builder perPage(Optional<Integer> perPage) {
      this.perPage = perPage;
      return this;
    }

    public Builder perPage(Integer perPage) {
      this.perPage = Optional.ofNullable(perPage);
      return this;
    }

    public ListCustomerCdrsRequest build() {
      return new ListCustomerCdrsRequest(startDate, endDate, callDirection, status, minDuration, hangupCause, perPage, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
