/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.partnerapi.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListCustomerNumbersRequest.Builder.class
)
public final class ListCustomerNumbersRequest {
  private final Optional<String> search;

  private final Optional<Integer> page;

  private final Optional<Integer> perPage;

  private final Map<String, Object> additionalProperties;

  private ListCustomerNumbersRequest(Optional<String> search, Optional<Integer> page,
      Optional<Integer> perPage, Map<String, Object> additionalProperties) {
    this.search = search;
    this.page = page;
    this.perPage = perPage;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Substring match against the E.164 number.
   */
  @JsonProperty("search")
  public Optional<String> getSearch() {
    return search;
  }

  @JsonProperty("page")
  public Optional<Integer> getPage() {
    return page;
  }

  @JsonProperty("per_page")
  public Optional<Integer> getPerPage() {
    return perPage;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListCustomerNumbersRequest && equalTo((ListCustomerNumbersRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListCustomerNumbersRequest other) {
    return search.equals(other.search) && page.equals(other.page) && perPage.equals(other.perPage);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.search, this.page, this.perPage);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> search = Optional.empty();

    private Optional<Integer> page = Optional.empty();

    private Optional<Integer> perPage = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ListCustomerNumbersRequest other) {
      search(other.getSearch());
      page(other.getPage());
      perPage(other.getPerPage());
      return this;
    }

    /**
     * <p>Substring match against the E.164 number.</p>
     */
    @JsonSetter(
        value = "search",
        nulls = Nulls.SKIP
    )
    public Builder search(Optional<String> search) {
      this.search = search;
      return this;
    }

    public Builder search(String search) {
      this.search = Optional.ofNullable(search);
      return this;
    }

    @JsonSetter(
        value = "page",
        nulls = Nulls.SKIP
    )
    public Builder page(Optional<Integer> page) {
      this.page = page;
      return this;
    }

    public Builder page(Integer page) {
      this.page = Optional.ofNullable(page);
      return this;
    }

    @JsonSetter(
        value = "per_page",
        nulls = Nulls.SKIP
    )
    public Builder perPage(Optional<Integer> perPage) {
      this.perPage = perPage;
      return this;
    }

    public Builder perPage(Integer perPage) {
      this.perPage = Optional.ofNullable(perPage);
      return this;
    }

    public ListCustomerNumbersRequest build() {
      return new ListCustomerNumbersRequest(search, page, perPage, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
