/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.partnerapi.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import resources.partnerapi.types.ListKycSessionsRequestStatus;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListKycSessionsRequest.Builder.class
)
public final class ListKycSessionsRequest {
  private final Optional<ListKycSessionsRequestStatus> status;

  private final Optional<String> accountAuthId;

  private final Optional<Integer> page;

  private final Optional<Integer> size;

  private final Map<String, Object> additionalProperties;

  private ListKycSessionsRequest(Optional<ListKycSessionsRequestStatus> status,
      Optional<String> accountAuthId, Optional<Integer> page, Optional<Integer> size,
      Map<String, Object> additionalProperties) {
    this.status = status;
    this.accountAuthId = accountAuthId;
    this.page = page;
    this.size = size;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("status")
  public Optional<ListKycSessionsRequestStatus> getStatus() {
    return status;
  }

  @JsonProperty("account_auth_id")
  public Optional<String> getAccountAuthId() {
    return accountAuthId;
  }

  @JsonProperty("page")
  public Optional<Integer> getPage() {
    return page;
  }

  @JsonProperty("size")
  public Optional<Integer> getSize() {
    return size;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListKycSessionsRequest && equalTo((ListKycSessionsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListKycSessionsRequest other) {
    return status.equals(other.status) && accountAuthId.equals(other.accountAuthId) && page.equals(other.page) && size.equals(other.size);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.status, this.accountAuthId, this.page, this.size);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<ListKycSessionsRequestStatus> status = Optional.empty();

    private Optional<String> accountAuthId = Optional.empty();

    private Optional<Integer> page = Optional.empty();

    private Optional<Integer> size = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ListKycSessionsRequest other) {
      status(other.getStatus());
      accountAuthId(other.getAccountAuthId());
      page(other.getPage());
      size(other.getSize());
      return this;
    }

    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<ListKycSessionsRequestStatus> status) {
      this.status = status;
      return this;
    }

    public Builder status(ListKycSessionsRequestStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    @JsonSetter(
        value = "account_auth_id",
        nulls = Nulls.SKIP
    )
    public Builder accountAuthId(Optional<String> accountAuthId) {
      this.accountAuthId = accountAuthId;
      return this;
    }

    public Builder accountAuthId(String accountAuthId) {
      this.accountAuthId = Optional.ofNullable(accountAuthId);
      return this;
    }

    @JsonSetter(
        value = "page",
        nulls = Nulls.SKIP
    )
    public Builder page(Optional<Integer> page) {
      this.page = page;
      return this;
    }

    public Builder page(Integer page) {
      this.page = Optional.ofNullable(page);
      return this;
    }

    @JsonSetter(
        value = "size",
        nulls = Nulls.SKIP
    )
    public Builder size(Optional<Integer> size) {
      this.size = size;
      return this;
    }

    public Builder size(Integer size) {
      this.size = Optional.ofNullable(size);
      return this;
    }

    public ListKycSessionsRequest build() {
      return new ListKycSessionsRequest(status, accountAuthId, page, size, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
